import { AuditLogService } from './audit-log.service';
import { QueryAuditLogDto } from './dto/query-audit-log.dto';
import { CreateAuditLogDto } from './dto/create-audit-log.dto';
export declare class AuditLogController {
    private readonly auditLogService;
    constructor(auditLogService: AuditLogService);
    findAll(query: QueryAuditLogDto): Promise<{
        data: {
            url: string;
            id: string;
            createdAt: Date;
            tenantId: string | null;
            buyerId: string | null;
            dealId: string | null;
            vehicleId: string | null;
            userId: string | null;
            userEmail: string;
            action: string;
            resource: string;
            resourceId: string | null;
            method: string;
            ipAddress: string;
            userAgent: string | null;
            status: string;
            duration: number | null;
            errorMessage: string | null;
            errorCode: number | null;
            level: string;
            pii: boolean;
            compliance: string[];
            metadata: import("@prisma/client/runtime/client").JsonValue | null;
        }[];
        meta: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNextPage: boolean;
            hasPreviousPage: boolean;
        };
    }>;
    create(dto: CreateAuditLogDto, req: any): Promise<{
        url: string;
        id: string;
        createdAt: Date;
        tenantId: string | null;
        buyerId: string | null;
        dealId: string | null;
        vehicleId: string | null;
        userId: string | null;
        userEmail: string;
        action: string;
        resource: string;
        resourceId: string | null;
        method: string;
        ipAddress: string;
        userAgent: string | null;
        status: string;
        duration: number | null;
        errorMessage: string | null;
        errorCode: number | null;
        level: string;
        pii: boolean;
        compliance: string[];
        metadata: import("@prisma/client/runtime/client").JsonValue | null;
    }>;
    findOne(id: string): Promise<{
        url: string;
        id: string;
        createdAt: Date;
        tenantId: string | null;
        buyerId: string | null;
        dealId: string | null;
        vehicleId: string | null;
        userId: string | null;
        userEmail: string;
        action: string;
        resource: string;
        resourceId: string | null;
        method: string;
        ipAddress: string;
        userAgent: string | null;
        status: string;
        duration: number | null;
        errorMessage: string | null;
        errorCode: number | null;
        level: string;
        pii: boolean;
        compliance: string[];
        metadata: import("@prisma/client/runtime/client").JsonValue | null;
    }>;
}
