import { PrismaService } from '@htownautos/prisma';
import { QueryAuditLogDto } from './dto/query-audit-log.dto';
import { Prisma } from '@prisma/client';
export declare class AuditLogService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    findAll(query: QueryAuditLogDto): Promise<{
        data: {
            url: string;
            id: string;
            createdAt: Date;
            tenantId: string | null;
            buyerId: string | null;
            dealId: string | null;
            vehicleId: string | null;
            userId: string | null;
            userEmail: string;
            action: string;
            resource: string;
            resourceId: string | null;
            method: string;
            ipAddress: string;
            userAgent: string | null;
            status: string;
            duration: number | null;
            errorMessage: string | null;
            errorCode: number | null;
            level: string;
            pii: boolean;
            compliance: string[];
            metadata: Prisma.JsonValue | null;
        }[];
        meta: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNextPage: boolean;
            hasPreviousPage: boolean;
        };
    }>;
    findOne(id: string): Promise<{
        url: string;
        id: string;
        createdAt: Date;
        tenantId: string | null;
        buyerId: string | null;
        dealId: string | null;
        vehicleId: string | null;
        userId: string | null;
        userEmail: string;
        action: string;
        resource: string;
        resourceId: string | null;
        method: string;
        ipAddress: string;
        userAgent: string | null;
        status: string;
        duration: number | null;
        errorMessage: string | null;
        errorCode: number | null;
        level: string;
        pii: boolean;
        compliance: string[];
        metadata: Prisma.JsonValue | null;
    }>;
    create(data: {
        action: string;
        resource: string;
        vehicleId?: string;
        buyerId?: string;
        dealId?: string;
        userId?: string;
        userEmail?: string;
        tenantId?: string;
        ipAddress?: string;
        userAgent?: string;
        level?: string;
        piiAccessed?: boolean;
        details?: any;
    }): Promise<{
        url: string;
        id: string;
        createdAt: Date;
        tenantId: string | null;
        buyerId: string | null;
        dealId: string | null;
        vehicleId: string | null;
        userId: string | null;
        userEmail: string;
        action: string;
        resource: string;
        resourceId: string | null;
        method: string;
        ipAddress: string;
        userAgent: string | null;
        status: string;
        duration: number | null;
        errorMessage: string | null;
        errorCode: number | null;
        level: string;
        pii: boolean;
        compliance: string[];
        metadata: Prisma.JsonValue | null;
    }>;
}
