import { Media } from '@prisma/client';
export declare class MediaEntity implements Media {
    id: string;
    filename: string;
    url: string;
    path: string | null;
    mimeType: string;
    size: number;
    width: number | null;
    height: number | null;
    duration: number | null;
    title: string | null;
    description: string | null;
    alt: string | null;
    mediaType: string;
    category: string | null;
    storageProvider: string | null;
    storageBucket: string | null;
    storageKey: string | null;
    isPublic: boolean;
    isActive: boolean;
    vehicleId: string | null;
    buyerId: string | null;
    partId: string | null;
    mainImageId: string | null;
    metaValue: any;
    tenantId: string | null;
    createdAt: Date;
    updatedAt: Date;
    inspectionId: string | null;
    inspectionChecklistItemId: string | null;
    inspectionRequestItemId: string | null;
    inspectionErrorCodeId: string | null;
    carfaxReportId: string | null;
    constructor(partial: Partial<MediaEntity>);
}
