import { PrismaService } from '@htownautos/prisma';
import { MetaService } from '../meta/meta.service';
import { CreateVehicleDto } from './dto/create-vehicle.dto';
import { UpdateVehicleDto } from './dto/update-vehicle.dto';
import { QueryVehicleDto } from './dto/query-vehicle.dto';
import { Prisma } from '@prisma/client';
export declare class VehicleService {
    private prisma;
    private metaService;
    constructor(prisma: PrismaService, metaService: MetaService);
    private getDefaultStatusId;
    private getDefaultMileageUnitId;
    private generateStockNumber;
    create(createVehicleDto: CreateVehicleDto, tenantId: string, createdById: string): Promise<{
        model: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            makeId: string;
            metaValue: Prisma.JsonValue | null;
        };
        trim: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            modelId: string;
            metaValue: Prisma.JsonValue | null;
        } | null;
        vehicleStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        vehicleCondition: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        bodyType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        fuelType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        driveType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        transmissionType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        titleBrand: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        mileageUnit: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleEngine: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        source: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        make: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            yearId: string;
            metaValue: Prisma.JsonValue | null;
        };
        mainImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: Prisma.JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
        year: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            metaValue: Prisma.JsonValue | null;
            year: number;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        vin: string;
        stockNumber: string | null;
        mileage: number | null;
        exteriorColor: string | null;
        interiorColor: string | null;
        vehicleTypeId: string | null;
        bodyTypeId: string | null;
        fuelTypeId: string | null;
        driveTypeId: string | null;
        transmissionTypeId: string | null;
        vehicleConditionId: string | null;
        vehicleStatusId: string | null;
        sourceId: string | null;
        costPrice: Prisma.Decimal | null;
        listPrice: Prisma.Decimal | null;
        salePrice: Prisma.Decimal | null;
        engine: string | null;
        cylinders: number | null;
        doors: number | null;
        passengers: number | null;
        description: string | null;
        features: string | null;
        notes: string | null;
        mainImageId: string | null;
        makeId: string;
        modelId: string;
        trimId: string | null;
        yearId: string;
        metaValue: Prisma.JsonValue | null;
        createdById: string | null;
        titleBrandId: string | null;
        advertisingPrice: Prisma.Decimal | null;
        askingPrice: Prisma.Decimal | null;
        bidIncrement: Prisma.Decimal | null;
        buyNowPrice: Prisma.Decimal | null;
        floorPrice: Prisma.Decimal | null;
        minDepositAmount: Prisma.Decimal | null;
        minDepositPercent: Prisma.Decimal | null;
        minDepositType: string | null;
        minDownAmount: Prisma.Decimal | null;
        minDownPercent: Prisma.Decimal | null;
        minDownType: string | null;
        msrp: Prisma.Decimal | null;
        purchaseDate: Date | null;
        specialPrice: Prisma.Decimal | null;
        specialPriceEndDate: Date | null;
        specialPriceStartDate: Date | null;
        startBid: Prisma.Decimal | null;
        startBidEqualsFloor: boolean;
        vehicleCost: Prisma.Decimal;
        wholesalePrice: Prisma.Decimal | null;
        mileageUnitId: string | null;
        bodySubtypeId: string | null;
        engineId: string | null;
    }>;
    findAll(query: QueryVehicleDto, tenantId: string): Promise<{
        data: any[];
        meta: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNextPage: boolean;
            hasPreviousPage: boolean;
        };
    }>;
    findOne(id: string, tenantId: string): Promise<{
        model: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            makeId: string;
            metaValue: Prisma.JsonValue | null;
        };
        trim: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            modelId: string;
            metaValue: Prisma.JsonValue | null;
        } | null;
        vehicleStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        vehicleCondition: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        bodyType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        fuelType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        driveType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        transmissionType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        titleBrand: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        mileageUnit: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleEngine: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        source: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        make: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            yearId: string;
            metaValue: Prisma.JsonValue | null;
        };
        mainImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: Prisma.JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
        year: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            metaValue: Prisma.JsonValue | null;
            year: number;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        vin: string;
        stockNumber: string | null;
        mileage: number | null;
        exteriorColor: string | null;
        interiorColor: string | null;
        vehicleTypeId: string | null;
        bodyTypeId: string | null;
        fuelTypeId: string | null;
        driveTypeId: string | null;
        transmissionTypeId: string | null;
        vehicleConditionId: string | null;
        vehicleStatusId: string | null;
        sourceId: string | null;
        costPrice: Prisma.Decimal | null;
        listPrice: Prisma.Decimal | null;
        salePrice: Prisma.Decimal | null;
        engine: string | null;
        cylinders: number | null;
        doors: number | null;
        passengers: number | null;
        description: string | null;
        features: string | null;
        notes: string | null;
        mainImageId: string | null;
        makeId: string;
        modelId: string;
        trimId: string | null;
        yearId: string;
        metaValue: Prisma.JsonValue | null;
        createdById: string | null;
        titleBrandId: string | null;
        advertisingPrice: Prisma.Decimal | null;
        askingPrice: Prisma.Decimal | null;
        bidIncrement: Prisma.Decimal | null;
        buyNowPrice: Prisma.Decimal | null;
        floorPrice: Prisma.Decimal | null;
        minDepositAmount: Prisma.Decimal | null;
        minDepositPercent: Prisma.Decimal | null;
        minDepositType: string | null;
        minDownAmount: Prisma.Decimal | null;
        minDownPercent: Prisma.Decimal | null;
        minDownType: string | null;
        msrp: Prisma.Decimal | null;
        purchaseDate: Date | null;
        specialPrice: Prisma.Decimal | null;
        specialPriceEndDate: Date | null;
        specialPriceStartDate: Date | null;
        startBid: Prisma.Decimal | null;
        startBidEqualsFloor: boolean;
        vehicleCost: Prisma.Decimal;
        wholesalePrice: Prisma.Decimal | null;
        mileageUnitId: string | null;
        bodySubtypeId: string | null;
        engineId: string | null;
    }>;
    findOneWithMetas(id: string, tenantId: string): Promise<{
        metas: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            entityType: string;
            entityId: string;
            userId: string | null;
            isPublic: boolean;
            key: string;
            value: string;
            valueType: string;
            isSystem: boolean;
            isDeleted: boolean;
        }[];
        model: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            makeId: string;
            metaValue: Prisma.JsonValue | null;
        };
        trim: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            modelId: string;
            metaValue: Prisma.JsonValue | null;
        } | null;
        vehicleStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        vehicleCondition: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        bodyType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        fuelType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        driveType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        transmissionType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        titleBrand: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        mileageUnit: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleEngine: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        source: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        make: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            yearId: string;
            metaValue: Prisma.JsonValue | null;
        };
        mainImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: Prisma.JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
        year: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            metaValue: Prisma.JsonValue | null;
            year: number;
        };
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        vin: string;
        stockNumber: string | null;
        mileage: number | null;
        exteriorColor: string | null;
        interiorColor: string | null;
        vehicleTypeId: string | null;
        bodyTypeId: string | null;
        fuelTypeId: string | null;
        driveTypeId: string | null;
        transmissionTypeId: string | null;
        vehicleConditionId: string | null;
        vehicleStatusId: string | null;
        sourceId: string | null;
        costPrice: Prisma.Decimal | null;
        listPrice: Prisma.Decimal | null;
        salePrice: Prisma.Decimal | null;
        engine: string | null;
        cylinders: number | null;
        doors: number | null;
        passengers: number | null;
        description: string | null;
        features: string | null;
        notes: string | null;
        mainImageId: string | null;
        makeId: string;
        modelId: string;
        trimId: string | null;
        yearId: string;
        metaValue: Prisma.JsonValue | null;
        createdById: string | null;
        titleBrandId: string | null;
        advertisingPrice: Prisma.Decimal | null;
        askingPrice: Prisma.Decimal | null;
        bidIncrement: Prisma.Decimal | null;
        buyNowPrice: Prisma.Decimal | null;
        floorPrice: Prisma.Decimal | null;
        minDepositAmount: Prisma.Decimal | null;
        minDepositPercent: Prisma.Decimal | null;
        minDepositType: string | null;
        minDownAmount: Prisma.Decimal | null;
        minDownPercent: Prisma.Decimal | null;
        minDownType: string | null;
        msrp: Prisma.Decimal | null;
        purchaseDate: Date | null;
        specialPrice: Prisma.Decimal | null;
        specialPriceEndDate: Date | null;
        specialPriceStartDate: Date | null;
        startBid: Prisma.Decimal | null;
        startBidEqualsFloor: boolean;
        vehicleCost: Prisma.Decimal;
        wholesalePrice: Prisma.Decimal | null;
        mileageUnitId: string | null;
        bodySubtypeId: string | null;
        engineId: string | null;
    }>;
    findByVin(vin: string, tenantId: string): Promise<{
        model: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            makeId: string;
            metaValue: Prisma.JsonValue | null;
        };
        trim: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            modelId: string;
            metaValue: Prisma.JsonValue | null;
        } | null;
        vehicleStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        vehicleCondition: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        bodyType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        fuelType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        driveType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        transmissionType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        titleBrand: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        mileageUnit: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleEngine: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        source: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        make: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            yearId: string;
            metaValue: Prisma.JsonValue | null;
        };
        mainImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: Prisma.JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
        year: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            metaValue: Prisma.JsonValue | null;
            year: number;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        vin: string;
        stockNumber: string | null;
        mileage: number | null;
        exteriorColor: string | null;
        interiorColor: string | null;
        vehicleTypeId: string | null;
        bodyTypeId: string | null;
        fuelTypeId: string | null;
        driveTypeId: string | null;
        transmissionTypeId: string | null;
        vehicleConditionId: string | null;
        vehicleStatusId: string | null;
        sourceId: string | null;
        costPrice: Prisma.Decimal | null;
        listPrice: Prisma.Decimal | null;
        salePrice: Prisma.Decimal | null;
        engine: string | null;
        cylinders: number | null;
        doors: number | null;
        passengers: number | null;
        description: string | null;
        features: string | null;
        notes: string | null;
        mainImageId: string | null;
        makeId: string;
        modelId: string;
        trimId: string | null;
        yearId: string;
        metaValue: Prisma.JsonValue | null;
        createdById: string | null;
        titleBrandId: string | null;
        advertisingPrice: Prisma.Decimal | null;
        askingPrice: Prisma.Decimal | null;
        bidIncrement: Prisma.Decimal | null;
        buyNowPrice: Prisma.Decimal | null;
        floorPrice: Prisma.Decimal | null;
        minDepositAmount: Prisma.Decimal | null;
        minDepositPercent: Prisma.Decimal | null;
        minDepositType: string | null;
        minDownAmount: Prisma.Decimal | null;
        minDownPercent: Prisma.Decimal | null;
        minDownType: string | null;
        msrp: Prisma.Decimal | null;
        purchaseDate: Date | null;
        specialPrice: Prisma.Decimal | null;
        specialPriceEndDate: Date | null;
        specialPriceStartDate: Date | null;
        startBid: Prisma.Decimal | null;
        startBidEqualsFloor: boolean;
        vehicleCost: Prisma.Decimal;
        wholesalePrice: Prisma.Decimal | null;
        mileageUnitId: string | null;
        bodySubtypeId: string | null;
        engineId: string | null;
    }>;
    findOnePublic(id: string): Promise<{
        id: string;
        vin: string;
        stockNumber: string | null;
        year: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            metaValue: Prisma.JsonValue | null;
            year: number;
        };
        make: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            yearId: string;
            metaValue: Prisma.JsonValue | null;
        };
        model: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            makeId: string;
            metaValue: Prisma.JsonValue | null;
        };
        trim: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            modelId: string;
            metaValue: Prisma.JsonValue | null;
        } | null;
        vehicleType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        bodyType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        fuelType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        driveType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        transmissionType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleCondition: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        vehicleEngine: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        mileage: number | null;
        mileageUnit: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        exteriorColor: string | null;
        interiorColor: string | null;
        engine: string | null;
        cylinders: number | null;
        doors: number | null;
        passengers: number | null;
        askingPrice: Prisma.Decimal | null;
        advertisingPrice: Prisma.Decimal | null;
        specialPrice: Prisma.Decimal | null;
        specialPriceStartDate: Date | null;
        specialPriceEndDate: Date | null;
        msrp: Prisma.Decimal | null;
        description: string | null;
        features: string | null;
        mainImage: {
            url: string;
            id: string;
            filename: string;
            mimeType: string;
        } | null;
        gallery: {
            url: string;
            id: string;
            filename: string;
            mimeType: string;
        }[];
        metas: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            entityType: string;
            entityId: string;
            userId: string | null;
            isPublic: boolean;
            key: string;
            value: string;
            valueType: string;
            isSystem: boolean;
            isDeleted: boolean;
        }[];
    }>;
    update(id: string, updateVehicleDto: UpdateVehicleDto, tenantId: string): Promise<{
        model: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            makeId: string;
            metaValue: Prisma.JsonValue | null;
        };
        trim: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            modelId: string;
            metaValue: Prisma.JsonValue | null;
        } | null;
        vehicleStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        vehicleCondition: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        bodyType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        fuelType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        driveType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        transmissionType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        titleBrand: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        mileageUnit: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleEngine: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        source: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        make: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            yearId: string;
            metaValue: Prisma.JsonValue | null;
        };
        mainImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: Prisma.JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
        year: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            metaValue: Prisma.JsonValue | null;
            year: number;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        vin: string;
        stockNumber: string | null;
        mileage: number | null;
        exteriorColor: string | null;
        interiorColor: string | null;
        vehicleTypeId: string | null;
        bodyTypeId: string | null;
        fuelTypeId: string | null;
        driveTypeId: string | null;
        transmissionTypeId: string | null;
        vehicleConditionId: string | null;
        vehicleStatusId: string | null;
        sourceId: string | null;
        costPrice: Prisma.Decimal | null;
        listPrice: Prisma.Decimal | null;
        salePrice: Prisma.Decimal | null;
        engine: string | null;
        cylinders: number | null;
        doors: number | null;
        passengers: number | null;
        description: string | null;
        features: string | null;
        notes: string | null;
        mainImageId: string | null;
        makeId: string;
        modelId: string;
        trimId: string | null;
        yearId: string;
        metaValue: Prisma.JsonValue | null;
        createdById: string | null;
        titleBrandId: string | null;
        advertisingPrice: Prisma.Decimal | null;
        askingPrice: Prisma.Decimal | null;
        bidIncrement: Prisma.Decimal | null;
        buyNowPrice: Prisma.Decimal | null;
        floorPrice: Prisma.Decimal | null;
        minDepositAmount: Prisma.Decimal | null;
        minDepositPercent: Prisma.Decimal | null;
        minDepositType: string | null;
        minDownAmount: Prisma.Decimal | null;
        minDownPercent: Prisma.Decimal | null;
        minDownType: string | null;
        msrp: Prisma.Decimal | null;
        purchaseDate: Date | null;
        specialPrice: Prisma.Decimal | null;
        specialPriceEndDate: Date | null;
        specialPriceStartDate: Date | null;
        startBid: Prisma.Decimal | null;
        startBidEqualsFloor: boolean;
        vehicleCost: Prisma.Decimal;
        wholesalePrice: Prisma.Decimal | null;
        mileageUnitId: string | null;
        bodySubtypeId: string | null;
        engineId: string | null;
    }>;
    remove(id: string, tenantId: string): Promise<{
        message: string;
    }>;
    removeBulk(ids: string[], tenantId: string): Promise<{
        message: string;
        count: number;
    }>;
    getStats(tenantId: string): Promise<{
        totalVehicles: number;
        totalValue: number | Prisma.Decimal;
        avgMileage: number;
        byStatus: (Prisma.PickEnumerable<Prisma.VehicleGroupByOutputType, "vehicleStatusId"[]> & {
            _count: number;
        })[];
        topMakes: (Prisma.PickEnumerable<Prisma.VehicleGroupByOutputType, "makeId"[]> & {
            _count: number;
        })[];
        recentVehicles: ({
            model: {
                name: string;
                id: string;
                slug: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                makeId: string;
                metaValue: Prisma.JsonValue | null;
            };
            make: {
                name: string;
                id: string;
                slug: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                yearId: string;
                metaValue: Prisma.JsonValue | null;
            };
            year: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                metaValue: Prisma.JsonValue | null;
                year: number;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            vin: string;
            stockNumber: string | null;
            mileage: number | null;
            exteriorColor: string | null;
            interiorColor: string | null;
            vehicleTypeId: string | null;
            bodyTypeId: string | null;
            fuelTypeId: string | null;
            driveTypeId: string | null;
            transmissionTypeId: string | null;
            vehicleConditionId: string | null;
            vehicleStatusId: string | null;
            sourceId: string | null;
            costPrice: Prisma.Decimal | null;
            listPrice: Prisma.Decimal | null;
            salePrice: Prisma.Decimal | null;
            engine: string | null;
            cylinders: number | null;
            doors: number | null;
            passengers: number | null;
            description: string | null;
            features: string | null;
            notes: string | null;
            mainImageId: string | null;
            makeId: string;
            modelId: string;
            trimId: string | null;
            yearId: string;
            metaValue: Prisma.JsonValue | null;
            createdById: string | null;
            titleBrandId: string | null;
            advertisingPrice: Prisma.Decimal | null;
            askingPrice: Prisma.Decimal | null;
            bidIncrement: Prisma.Decimal | null;
            buyNowPrice: Prisma.Decimal | null;
            floorPrice: Prisma.Decimal | null;
            minDepositAmount: Prisma.Decimal | null;
            minDepositPercent: Prisma.Decimal | null;
            minDepositType: string | null;
            minDownAmount: Prisma.Decimal | null;
            minDownPercent: Prisma.Decimal | null;
            minDownType: string | null;
            msrp: Prisma.Decimal | null;
            purchaseDate: Date | null;
            specialPrice: Prisma.Decimal | null;
            specialPriceEndDate: Date | null;
            specialPriceStartDate: Date | null;
            startBid: Prisma.Decimal | null;
            startBidEqualsFloor: boolean;
            vehicleCost: Prisma.Decimal;
            wholesalePrice: Prisma.Decimal | null;
            mileageUnitId: string | null;
            bodySubtypeId: string | null;
            engineId: string | null;
        })[];
    }>;
    private syncPricingFields;
    private validateRelatedEntities;
    private getIncludeRelations;
}
