import { VehicleService } from './vehicle.service';
import { CreateVehicleDto } from './dto/create-vehicle.dto';
import { UpdateVehicleDto } from './dto/update-vehicle.dto';
import { QueryVehicleDto } from './dto/query-vehicle.dto';
export declare class VehicleController {
    private readonly vehicleService;
    constructor(vehicleService: VehicleService);
    create(tenantId: string, user: {
        id: string;
    }, createVehicleDto: CreateVehicleDto): Promise<{
        model: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            makeId: string;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        };
        trim: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            modelId: string;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        } | null;
        vehicleStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        vehicleCondition: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        bodyType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        fuelType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        driveType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        transmissionType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        titleBrand: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        mileageUnit: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleEngine: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        source: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        make: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            yearId: string;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        };
        mainImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
        year: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            year: number;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        vin: string;
        stockNumber: string | null;
        mileage: number | null;
        exteriorColor: string | null;
        interiorColor: string | null;
        vehicleTypeId: string | null;
        bodyTypeId: string | null;
        fuelTypeId: string | null;
        driveTypeId: string | null;
        transmissionTypeId: string | null;
        vehicleConditionId: string | null;
        vehicleStatusId: string | null;
        sourceId: string | null;
        costPrice: import("@prisma/client-runtime-utils").Decimal | null;
        listPrice: import("@prisma/client-runtime-utils").Decimal | null;
        salePrice: import("@prisma/client-runtime-utils").Decimal | null;
        engine: string | null;
        cylinders: number | null;
        doors: number | null;
        passengers: number | null;
        description: string | null;
        features: string | null;
        notes: string | null;
        mainImageId: string | null;
        makeId: string;
        modelId: string;
        trimId: string | null;
        yearId: string;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        createdById: string | null;
        titleBrandId: string | null;
        advertisingPrice: import("@prisma/client-runtime-utils").Decimal | null;
        askingPrice: import("@prisma/client-runtime-utils").Decimal | null;
        bidIncrement: import("@prisma/client-runtime-utils").Decimal | null;
        buyNowPrice: import("@prisma/client-runtime-utils").Decimal | null;
        floorPrice: import("@prisma/client-runtime-utils").Decimal | null;
        minDepositAmount: import("@prisma/client-runtime-utils").Decimal | null;
        minDepositPercent: import("@prisma/client-runtime-utils").Decimal | null;
        minDepositType: string | null;
        minDownAmount: import("@prisma/client-runtime-utils").Decimal | null;
        minDownPercent: import("@prisma/client-runtime-utils").Decimal | null;
        minDownType: string | null;
        msrp: import("@prisma/client-runtime-utils").Decimal | null;
        purchaseDate: Date | null;
        specialPrice: import("@prisma/client-runtime-utils").Decimal | null;
        specialPriceEndDate: Date | null;
        specialPriceStartDate: Date | null;
        startBid: import("@prisma/client-runtime-utils").Decimal | null;
        startBidEqualsFloor: boolean;
        vehicleCost: import("@prisma/client-runtime-utils").Decimal;
        wholesalePrice: import("@prisma/client-runtime-utils").Decimal | null;
        mileageUnitId: string | null;
        bodySubtypeId: string | null;
        engineId: string | null;
    }>;
    findAll(tenantId: string, query: QueryVehicleDto): Promise<{
        data: any[];
        meta: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNextPage: boolean;
            hasPreviousPage: boolean;
        };
    }>;
    getStats(tenantId: string): Promise<{
        totalVehicles: number;
        totalValue: number | import("@prisma/client-runtime-utils").Decimal;
        avgMileage: number;
        byStatus: (import("@prisma/client").Prisma.PickEnumerable<import("@prisma/client").Prisma.VehicleGroupByOutputType, "vehicleStatusId"[]> & {
            _count: number;
        })[];
        topMakes: (import("@prisma/client").Prisma.PickEnumerable<import("@prisma/client").Prisma.VehicleGroupByOutputType, "makeId"[]> & {
            _count: number;
        })[];
        recentVehicles: ({
            model: {
                name: string;
                id: string;
                slug: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                makeId: string;
                metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            };
            make: {
                name: string;
                id: string;
                slug: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                yearId: string;
                metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            };
            year: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                metaValue: import("@prisma/client/runtime/client").JsonValue | null;
                year: number;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            vin: string;
            stockNumber: string | null;
            mileage: number | null;
            exteriorColor: string | null;
            interiorColor: string | null;
            vehicleTypeId: string | null;
            bodyTypeId: string | null;
            fuelTypeId: string | null;
            driveTypeId: string | null;
            transmissionTypeId: string | null;
            vehicleConditionId: string | null;
            vehicleStatusId: string | null;
            sourceId: string | null;
            costPrice: import("@prisma/client-runtime-utils").Decimal | null;
            listPrice: import("@prisma/client-runtime-utils").Decimal | null;
            salePrice: import("@prisma/client-runtime-utils").Decimal | null;
            engine: string | null;
            cylinders: number | null;
            doors: number | null;
            passengers: number | null;
            description: string | null;
            features: string | null;
            notes: string | null;
            mainImageId: string | null;
            makeId: string;
            modelId: string;
            trimId: string | null;
            yearId: string;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            createdById: string | null;
            titleBrandId: string | null;
            advertisingPrice: import("@prisma/client-runtime-utils").Decimal | null;
            askingPrice: import("@prisma/client-runtime-utils").Decimal | null;
            bidIncrement: import("@prisma/client-runtime-utils").Decimal | null;
            buyNowPrice: import("@prisma/client-runtime-utils").Decimal | null;
            floorPrice: import("@prisma/client-runtime-utils").Decimal | null;
            minDepositAmount: import("@prisma/client-runtime-utils").Decimal | null;
            minDepositPercent: import("@prisma/client-runtime-utils").Decimal | null;
            minDepositType: string | null;
            minDownAmount: import("@prisma/client-runtime-utils").Decimal | null;
            minDownPercent: import("@prisma/client-runtime-utils").Decimal | null;
            minDownType: string | null;
            msrp: import("@prisma/client-runtime-utils").Decimal | null;
            purchaseDate: Date | null;
            specialPrice: import("@prisma/client-runtime-utils").Decimal | null;
            specialPriceEndDate: Date | null;
            specialPriceStartDate: Date | null;
            startBid: import("@prisma/client-runtime-utils").Decimal | null;
            startBidEqualsFloor: boolean;
            vehicleCost: import("@prisma/client-runtime-utils").Decimal;
            wholesalePrice: import("@prisma/client-runtime-utils").Decimal | null;
            mileageUnitId: string | null;
            bodySubtypeId: string | null;
            engineId: string | null;
        })[];
    }>;
    findByVin(tenantId: string, vin: string): Promise<{
        model: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            makeId: string;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        };
        trim: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            modelId: string;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        } | null;
        vehicleStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        vehicleCondition: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        bodyType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        fuelType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        driveType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        transmissionType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        titleBrand: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        mileageUnit: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleEngine: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        source: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        make: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            yearId: string;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        };
        mainImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
        year: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            year: number;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        vin: string;
        stockNumber: string | null;
        mileage: number | null;
        exteriorColor: string | null;
        interiorColor: string | null;
        vehicleTypeId: string | null;
        bodyTypeId: string | null;
        fuelTypeId: string | null;
        driveTypeId: string | null;
        transmissionTypeId: string | null;
        vehicleConditionId: string | null;
        vehicleStatusId: string | null;
        sourceId: string | null;
        costPrice: import("@prisma/client-runtime-utils").Decimal | null;
        listPrice: import("@prisma/client-runtime-utils").Decimal | null;
        salePrice: import("@prisma/client-runtime-utils").Decimal | null;
        engine: string | null;
        cylinders: number | null;
        doors: number | null;
        passengers: number | null;
        description: string | null;
        features: string | null;
        notes: string | null;
        mainImageId: string | null;
        makeId: string;
        modelId: string;
        trimId: string | null;
        yearId: string;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        createdById: string | null;
        titleBrandId: string | null;
        advertisingPrice: import("@prisma/client-runtime-utils").Decimal | null;
        askingPrice: import("@prisma/client-runtime-utils").Decimal | null;
        bidIncrement: import("@prisma/client-runtime-utils").Decimal | null;
        buyNowPrice: import("@prisma/client-runtime-utils").Decimal | null;
        floorPrice: import("@prisma/client-runtime-utils").Decimal | null;
        minDepositAmount: import("@prisma/client-runtime-utils").Decimal | null;
        minDepositPercent: import("@prisma/client-runtime-utils").Decimal | null;
        minDepositType: string | null;
        minDownAmount: import("@prisma/client-runtime-utils").Decimal | null;
        minDownPercent: import("@prisma/client-runtime-utils").Decimal | null;
        minDownType: string | null;
        msrp: import("@prisma/client-runtime-utils").Decimal | null;
        purchaseDate: Date | null;
        specialPrice: import("@prisma/client-runtime-utils").Decimal | null;
        specialPriceEndDate: Date | null;
        specialPriceStartDate: Date | null;
        startBid: import("@prisma/client-runtime-utils").Decimal | null;
        startBidEqualsFloor: boolean;
        vehicleCost: import("@prisma/client-runtime-utils").Decimal;
        wholesalePrice: import("@prisma/client-runtime-utils").Decimal | null;
        mileageUnitId: string | null;
        bodySubtypeId: string | null;
        engineId: string | null;
    }>;
    findOneWithMetas(tenantId: string, id: string): Promise<{
        metas: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            entityType: string;
            entityId: string;
            userId: string | null;
            isPublic: boolean;
            key: string;
            value: string;
            valueType: string;
            isSystem: boolean;
            isDeleted: boolean;
        }[];
        model: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            makeId: string;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        };
        trim: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            modelId: string;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        } | null;
        vehicleStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        vehicleCondition: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        bodyType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        fuelType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        driveType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        transmissionType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        titleBrand: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        mileageUnit: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleEngine: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        source: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        make: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            yearId: string;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        };
        mainImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
        year: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            year: number;
        };
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        vin: string;
        stockNumber: string | null;
        mileage: number | null;
        exteriorColor: string | null;
        interiorColor: string | null;
        vehicleTypeId: string | null;
        bodyTypeId: string | null;
        fuelTypeId: string | null;
        driveTypeId: string | null;
        transmissionTypeId: string | null;
        vehicleConditionId: string | null;
        vehicleStatusId: string | null;
        sourceId: string | null;
        costPrice: import("@prisma/client-runtime-utils").Decimal | null;
        listPrice: import("@prisma/client-runtime-utils").Decimal | null;
        salePrice: import("@prisma/client-runtime-utils").Decimal | null;
        engine: string | null;
        cylinders: number | null;
        doors: number | null;
        passengers: number | null;
        description: string | null;
        features: string | null;
        notes: string | null;
        mainImageId: string | null;
        makeId: string;
        modelId: string;
        trimId: string | null;
        yearId: string;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        createdById: string | null;
        titleBrandId: string | null;
        advertisingPrice: import("@prisma/client-runtime-utils").Decimal | null;
        askingPrice: import("@prisma/client-runtime-utils").Decimal | null;
        bidIncrement: import("@prisma/client-runtime-utils").Decimal | null;
        buyNowPrice: import("@prisma/client-runtime-utils").Decimal | null;
        floorPrice: import("@prisma/client-runtime-utils").Decimal | null;
        minDepositAmount: import("@prisma/client-runtime-utils").Decimal | null;
        minDepositPercent: import("@prisma/client-runtime-utils").Decimal | null;
        minDepositType: string | null;
        minDownAmount: import("@prisma/client-runtime-utils").Decimal | null;
        minDownPercent: import("@prisma/client-runtime-utils").Decimal | null;
        minDownType: string | null;
        msrp: import("@prisma/client-runtime-utils").Decimal | null;
        purchaseDate: Date | null;
        specialPrice: import("@prisma/client-runtime-utils").Decimal | null;
        specialPriceEndDate: Date | null;
        specialPriceStartDate: Date | null;
        startBid: import("@prisma/client-runtime-utils").Decimal | null;
        startBidEqualsFloor: boolean;
        vehicleCost: import("@prisma/client-runtime-utils").Decimal;
        wholesalePrice: import("@prisma/client-runtime-utils").Decimal | null;
        mileageUnitId: string | null;
        bodySubtypeId: string | null;
        engineId: string | null;
    }>;
    findOne(tenantId: string, id: string): Promise<{
        model: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            makeId: string;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        };
        trim: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            modelId: string;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        } | null;
        vehicleStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        vehicleCondition: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        bodyType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        fuelType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        driveType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        transmissionType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        titleBrand: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        mileageUnit: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleEngine: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        source: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        make: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            yearId: string;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        };
        mainImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
        year: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            year: number;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        vin: string;
        stockNumber: string | null;
        mileage: number | null;
        exteriorColor: string | null;
        interiorColor: string | null;
        vehicleTypeId: string | null;
        bodyTypeId: string | null;
        fuelTypeId: string | null;
        driveTypeId: string | null;
        transmissionTypeId: string | null;
        vehicleConditionId: string | null;
        vehicleStatusId: string | null;
        sourceId: string | null;
        costPrice: import("@prisma/client-runtime-utils").Decimal | null;
        listPrice: import("@prisma/client-runtime-utils").Decimal | null;
        salePrice: import("@prisma/client-runtime-utils").Decimal | null;
        engine: string | null;
        cylinders: number | null;
        doors: number | null;
        passengers: number | null;
        description: string | null;
        features: string | null;
        notes: string | null;
        mainImageId: string | null;
        makeId: string;
        modelId: string;
        trimId: string | null;
        yearId: string;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        createdById: string | null;
        titleBrandId: string | null;
        advertisingPrice: import("@prisma/client-runtime-utils").Decimal | null;
        askingPrice: import("@prisma/client-runtime-utils").Decimal | null;
        bidIncrement: import("@prisma/client-runtime-utils").Decimal | null;
        buyNowPrice: import("@prisma/client-runtime-utils").Decimal | null;
        floorPrice: import("@prisma/client-runtime-utils").Decimal | null;
        minDepositAmount: import("@prisma/client-runtime-utils").Decimal | null;
        minDepositPercent: import("@prisma/client-runtime-utils").Decimal | null;
        minDepositType: string | null;
        minDownAmount: import("@prisma/client-runtime-utils").Decimal | null;
        minDownPercent: import("@prisma/client-runtime-utils").Decimal | null;
        minDownType: string | null;
        msrp: import("@prisma/client-runtime-utils").Decimal | null;
        purchaseDate: Date | null;
        specialPrice: import("@prisma/client-runtime-utils").Decimal | null;
        specialPriceEndDate: Date | null;
        specialPriceStartDate: Date | null;
        startBid: import("@prisma/client-runtime-utils").Decimal | null;
        startBidEqualsFloor: boolean;
        vehicleCost: import("@prisma/client-runtime-utils").Decimal;
        wholesalePrice: import("@prisma/client-runtime-utils").Decimal | null;
        mileageUnitId: string | null;
        bodySubtypeId: string | null;
        engineId: string | null;
    }>;
    update(tenantId: string, id: string, updateVehicleDto: UpdateVehicleDto): Promise<{
        model: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            makeId: string;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        };
        trim: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            modelId: string;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        } | null;
        vehicleStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        vehicleCondition: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        bodyType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        fuelType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        driveType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        transmissionType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        titleBrand: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        mileageUnit: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        vehicleEngine: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        source: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        } | null;
        make: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            yearId: string;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        };
        mainImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
        year: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            year: number;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        vin: string;
        stockNumber: string | null;
        mileage: number | null;
        exteriorColor: string | null;
        interiorColor: string | null;
        vehicleTypeId: string | null;
        bodyTypeId: string | null;
        fuelTypeId: string | null;
        driveTypeId: string | null;
        transmissionTypeId: string | null;
        vehicleConditionId: string | null;
        vehicleStatusId: string | null;
        sourceId: string | null;
        costPrice: import("@prisma/client-runtime-utils").Decimal | null;
        listPrice: import("@prisma/client-runtime-utils").Decimal | null;
        salePrice: import("@prisma/client-runtime-utils").Decimal | null;
        engine: string | null;
        cylinders: number | null;
        doors: number | null;
        passengers: number | null;
        description: string | null;
        features: string | null;
        notes: string | null;
        mainImageId: string | null;
        makeId: string;
        modelId: string;
        trimId: string | null;
        yearId: string;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        createdById: string | null;
        titleBrandId: string | null;
        advertisingPrice: import("@prisma/client-runtime-utils").Decimal | null;
        askingPrice: import("@prisma/client-runtime-utils").Decimal | null;
        bidIncrement: import("@prisma/client-runtime-utils").Decimal | null;
        buyNowPrice: import("@prisma/client-runtime-utils").Decimal | null;
        floorPrice: import("@prisma/client-runtime-utils").Decimal | null;
        minDepositAmount: import("@prisma/client-runtime-utils").Decimal | null;
        minDepositPercent: import("@prisma/client-runtime-utils").Decimal | null;
        minDepositType: string | null;
        minDownAmount: import("@prisma/client-runtime-utils").Decimal | null;
        minDownPercent: import("@prisma/client-runtime-utils").Decimal | null;
        minDownType: string | null;
        msrp: import("@prisma/client-runtime-utils").Decimal | null;
        purchaseDate: Date | null;
        specialPrice: import("@prisma/client-runtime-utils").Decimal | null;
        specialPriceEndDate: Date | null;
        specialPriceStartDate: Date | null;
        startBid: import("@prisma/client-runtime-utils").Decimal | null;
        startBidEqualsFloor: boolean;
        vehicleCost: import("@prisma/client-runtime-utils").Decimal;
        wholesalePrice: import("@prisma/client-runtime-utils").Decimal | null;
        mileageUnitId: string | null;
        bodySubtypeId: string | null;
        engineId: string | null;
    }>;
    removeBulk(tenantId: string, body: {
        ids: string[];
    }): Promise<{
        message: string;
        count: number;
    }>;
    remove(tenantId: string, id: string): Promise<{
        message: string;
    }>;
}
