import { VehiclePartsService } from './vehicle-parts.service';
import { CreateVehiclePartDto, CreatePartAndAssociateDto, UpdateVehiclePartDto } from './dto/vehicle-part.dto';
export declare class VehiclePartsController {
    private readonly vehiclePartsService;
    constructor(vehiclePartsService: VehiclePartsService);
    findByVehicle(tenantId: string, vehicleId: string): Promise<{
        data: ({
            part: {
                status: {
                    id: string;
                    slug: string;
                    title: string;
                };
                category: {
                    id: string;
                    slug: string;
                    title: string;
                } | null;
                condition: {
                    id: string;
                    slug: string;
                    title: string;
                };
                mainImage: {
                    url: string;
                    id: string;
                    filename: string;
                } | null;
            } & {
                length: import("@prisma/client-runtime-utils").Decimal | null;
                name: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                description: string | null;
                notes: string | null;
                mainImageId: string | null;
                makeId: string | null;
                modelId: string | null;
                trimId: string | null;
                yearId: string | null;
                metaValue: import("@prisma/client/runtime/client").JsonValue | null;
                purchaseDate: Date | null;
                price: import("@prisma/client-runtime-utils").Decimal;
                width: import("@prisma/client-runtime-utils").Decimal | null;
                height: import("@prisma/client-runtime-utils").Decimal | null;
                partNumber: string | null;
                sku: string | null;
                categoryId: string | null;
                conditionId: string;
                statusId: string;
                cost: import("@prisma/client-runtime-utils").Decimal | null;
                quantity: number;
                minQuantity: number;
                location: string | null;
                warehouseSection: string | null;
                sourceVin: string | null;
                sourceMiles: number | null;
                sourceVehicleId: string | null;
                weight: import("@prisma/client-runtime-utils").Decimal | null;
                warrantyDays: number | null;
                warrantyNotes: string | null;
                supplier: string | null;
                supplierPartNumber: string | null;
                purchaseOrderNumber: string | null;
                brand: string | null;
                manufacturer: string | null;
                countryOfOrigin: string | null;
                isOem: boolean;
                isAftermarket: boolean;
                soldAt: Date | null;
                soldToId: string | null;
                soldPrice: import("@prisma/client-runtime-utils").Decimal | null;
                soldDealId: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            notes: string | null;
            vehicleId: string;
            partId: string;
            quantity: number;
            priceAtTime: import("@prisma/client-runtime-utils").Decimal;
            installedAt: Date;
        })[];
        total: number;
        count: number;
    }>;
    getAvailableParts(tenantId: string, vehicleId: string, search?: string): Promise<({
        status: {
            id: string;
            slug: string;
            title: string;
        };
        category: {
            id: string;
            slug: string;
            title: string;
        } | null;
        condition: {
            id: string;
            slug: string;
            title: string;
        };
        mainImage: {
            url: string;
            id: string;
            filename: string;
        } | null;
    } & {
        length: import("@prisma/client-runtime-utils").Decimal | null;
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        description: string | null;
        notes: string | null;
        mainImageId: string | null;
        makeId: string | null;
        modelId: string | null;
        trimId: string | null;
        yearId: string | null;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        purchaseDate: Date | null;
        price: import("@prisma/client-runtime-utils").Decimal;
        width: import("@prisma/client-runtime-utils").Decimal | null;
        height: import("@prisma/client-runtime-utils").Decimal | null;
        partNumber: string | null;
        sku: string | null;
        categoryId: string | null;
        conditionId: string;
        statusId: string;
        cost: import("@prisma/client-runtime-utils").Decimal | null;
        quantity: number;
        minQuantity: number;
        location: string | null;
        warehouseSection: string | null;
        sourceVin: string | null;
        sourceMiles: number | null;
        sourceVehicleId: string | null;
        weight: import("@prisma/client-runtime-utils").Decimal | null;
        warrantyDays: number | null;
        warrantyNotes: string | null;
        supplier: string | null;
        supplierPartNumber: string | null;
        purchaseOrderNumber: string | null;
        brand: string | null;
        manufacturer: string | null;
        countryOfOrigin: string | null;
        isOem: boolean;
        isAftermarket: boolean;
        soldAt: Date | null;
        soldToId: string | null;
        soldPrice: import("@prisma/client-runtime-utils").Decimal | null;
        soldDealId: string | null;
    })[]>;
    associatePart(tenantId: string, vehicleId: string, dto: CreateVehiclePartDto): Promise<any>;
    createAndAssociate(tenantId: string, vehicleId: string, dto: CreatePartAndAssociateDto): Promise<any>;
    updateAssociation(tenantId: string, vehicleId: string, vehiclePartId: string, dto: UpdateVehiclePartDto): Promise<{
        part: {
            length: import("@prisma/client-runtime-utils").Decimal | null;
            name: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            description: string | null;
            notes: string | null;
            mainImageId: string | null;
            makeId: string | null;
            modelId: string | null;
            trimId: string | null;
            yearId: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            purchaseDate: Date | null;
            price: import("@prisma/client-runtime-utils").Decimal;
            width: import("@prisma/client-runtime-utils").Decimal | null;
            height: import("@prisma/client-runtime-utils").Decimal | null;
            partNumber: string | null;
            sku: string | null;
            categoryId: string | null;
            conditionId: string;
            statusId: string;
            cost: import("@prisma/client-runtime-utils").Decimal | null;
            quantity: number;
            minQuantity: number;
            location: string | null;
            warehouseSection: string | null;
            sourceVin: string | null;
            sourceMiles: number | null;
            sourceVehicleId: string | null;
            weight: import("@prisma/client-runtime-utils").Decimal | null;
            warrantyDays: number | null;
            warrantyNotes: string | null;
            supplier: string | null;
            supplierPartNumber: string | null;
            purchaseOrderNumber: string | null;
            brand: string | null;
            manufacturer: string | null;
            countryOfOrigin: string | null;
            isOem: boolean;
            isAftermarket: boolean;
            soldAt: Date | null;
            soldToId: string | null;
            soldPrice: import("@prisma/client-runtime-utils").Decimal | null;
            soldDealId: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        vehicleId: string;
        partId: string;
        quantity: number;
        priceAtTime: import("@prisma/client-runtime-utils").Decimal;
        installedAt: Date;
    }>;
    removeAssociation(tenantId: string, vehicleId: string, vehiclePartId: string, restoreStock?: string): Promise<{
        message: string;
    }>;
}
