import Stripe from 'stripe';
import { Prisma } from '@prisma/client';
import { PrismaService } from '@htownautos/prisma';
import { S3Service } from '@htownautos/common';
import type { PortalBuyer } from '@htownautos/auth';
import { CopartService } from '../copart/copart.service';
import { QueryCopartDto } from '../copart/dto/query-copart.dto';
import { AuctionSearchService } from '../opensearch/auction-search.service';
import { VehicleInspectionsService } from '../vehicle-inspections/vehicle-inspections.service';
import { UpdatePortalProfileDto } from './dto/update-portal-profile.dto';
import { CreateDepositDto } from './dto/create-deposit.dto';
import { InspectionCartDto, CartItemDto } from './dto/inspection-cart.dto';
import { PortalPricingService, PortalPricing } from './portal-pricing.service';
import { FindACarCheckoutDto } from './dto/find-a-car-checkout.dto';
import { AuctionAnalysisService } from '../auction-analysis/auction-analysis.service';
import { NotificationsService } from '../notifications/notifications.service';
export interface InspectionQuote {
    items: CartItemDto[];
    byYard: Array<{
        yardId: string;
        yardName?: string;
        cars: number;
        travelFeeCents: number;
        minCars: number;
    }>;
    carsCount: number;
    yardsCount: number;
    inspectionFeeCents: number;
    travelFeeCents: number;
    inspectionSubtotalCents: number;
    travelSubtotalCents: number;
    totalCents: number;
    currency: 'usd';
    minCarsViolations: Array<{
        yardId: string;
        yardName: string;
        required: number;
        actual: number;
    }>;
}
export interface OrderReceiptDetail {
    id: string;
    type: 'INSPECTION' | 'DEPOSIT' | 'SERVICE';
    receiptNumber: string;
    status: string;
    description: string | null;
    totalCents: number;
    carsCount: number;
    yardsCount: number;
    inspectionSubtotalCents: number;
    travelSubtotalCents: number;
    inspectionFeeCents: number;
    byYard: Array<{
        yardId: string;
        yardName: string | null;
        location: {
            city: string | null;
            state: string | null;
        } | null;
        cars: number;
        inspectionFeeCents: number;
        inspectionSubtotalCents: number;
        travelFeeCents: number;
        vehicles: Array<{
            inspectionId: string | null;
            lotNumber: string | null;
            vin: string | null;
            year: number | null;
            make: string | null;
            model: string | null;
        }>;
    }>;
    inspections: Array<{
        id: string;
        vin: string | null;
        lotNumber: string | null;
        year: number | null;
        make: string | null;
        model: string | null;
        yardName: string | null;
    }>;
}
export declare class PortalService {
    private readonly prisma;
    private readonly copartService;
    private readonly inspectionsService;
    private readonly pricingService;
    private readonly auctionSearchService;
    private readonly s3;
    private readonly auctionAnalysis;
    private readonly notifications;
    private readonly logger;
    private readonly stripe;
    constructor(prisma: PrismaService, copartService: CopartService, inspectionsService: VehicleInspectionsService, pricingService: PortalPricingService, auctionSearchService: AuctionSearchService, s3: S3Service, auctionAnalysis: AuctionAnalysisService, notifications: NotificationsService);
    getProfile(buyer: PortalBuyer): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        email: string;
        firstName: string;
        lastName: string;
        phoneMain: string;
        phoneSecondary: string | null;
        phoneMobile: string | null;
        currentAddress: string;
        currentCity: string;
        currentState: string;
        currentZipCode: string;
        currentCountry: string;
    }>;
    updateProfile(buyer: PortalBuyer, dto: UpdatePortalProfileDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        email: string;
        firstName: string;
        lastName: string;
        phoneMain: string;
        phoneSecondary: string | null;
        phoneMobile: string | null;
        currentAddress: string;
        currentCity: string;
        currentState: string;
        currentZipCode: string;
        currentCountry: string;
    }>;
    getListings(query: QueryCopartDto): Promise<{
        data: {
            lotNumber: string;
            inspectable: boolean;
            trim: string | null;
            createdAt: Date;
            updatedAt: Date;
            vehicleType: string | null;
            fuelType: string | null;
            vin: string | null;
            engine: string | null;
            cylinders: string | null;
            odometerBrand: string | null;
            yardName: string | null;
            yardNumber: number | null;
            yardId: string | null;
            make: string | null;
            damageDescription: string | null;
            year: number | null;
            lastSeenAt: Date | null;
            auctionName: string | null;
            copartId: number | null;
            saleDate: number | null;
            dayOfWeek: string | null;
            saleTime: string | null;
            timeZone: string | null;
            itemNumber: number | null;
            modelGroup: string | null;
            modelDetail: string | null;
            bodyStyle: string | null;
            color: string | null;
            secondaryDamage: string | null;
            saleTitleState: string | null;
            saleTitleType: string | null;
            hasKeys: string | null;
            lotCondCode: string | null;
            odometer: Prisma.Decimal | null;
            estRetailValue: Prisma.Decimal | null;
            repairCost: Prisma.Decimal | null;
            drive: string | null;
            transmission: string | null;
            runsDrives: string | null;
            saleStatus: string | null;
            highBid: Prisma.Decimal | null;
            specialNote: string | null;
            locationCity: string | null;
            locationState: string | null;
            locationZip: string | null;
            locationCountry: string | null;
            currencyCode: string | null;
            images: string | null;
            galleryCache: string | null;
            galleryCachedAt: Date | null;
            createDateTime: string | null;
            gridRow: string | null;
            makeOfferEligible: string | null;
            buyItNowPrice: Prisma.Decimal | null;
            lastUpdatedTime: Date | null;
            rentals: string | null;
            wholesale: string | null;
            sellerName: string | null;
            offsiteAddress1: string | null;
            offsiteState: string | null;
            offsiteCity: string | null;
            offsiteZip: string | null;
            saleLight: string | null;
            autoGrade: string | null;
            announcements: string | null;
            sellerCategory: string | null;
            engineSizeL: Prisma.Decimal | null;
            locationLat: number | null;
            locationLng: number | null;
            isStale: boolean;
            discarded: boolean;
            discardReason: string | null;
            discardedAt: Date | null;
            discardedById: string | null;
        }[];
        meta: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNextPage: boolean;
            hasPreviousPage: boolean;
        };
    }>;
    getListingByLotNumber(lotNumber: string): Promise<{
        carfax: {
            id: any;
            aiSummary: any;
            analysis: any;
            signedUrl: any;
            date: any;
            createdAt: any;
        }[];
        lotNumber: string;
        inspectable: boolean;
        trim: string | null;
        createdAt: Date;
        updatedAt: Date;
        vehicleType: string | null;
        fuelType: string | null;
        vin: string | null;
        engine: string | null;
        cylinders: string | null;
        odometerBrand: string | null;
        yardName: string | null;
        yardNumber: number | null;
        yardId: string | null;
        make: string | null;
        damageDescription: string | null;
        year: number | null;
        lastSeenAt: Date | null;
        auctionName: string | null;
        copartId: number | null;
        saleDate: number | null;
        dayOfWeek: string | null;
        saleTime: string | null;
        timeZone: string | null;
        itemNumber: number | null;
        modelGroup: string | null;
        modelDetail: string | null;
        bodyStyle: string | null;
        color: string | null;
        secondaryDamage: string | null;
        saleTitleState: string | null;
        saleTitleType: string | null;
        hasKeys: string | null;
        lotCondCode: string | null;
        odometer: Prisma.Decimal | null;
        estRetailValue: Prisma.Decimal | null;
        repairCost: Prisma.Decimal | null;
        drive: string | null;
        transmission: string | null;
        runsDrives: string | null;
        saleStatus: string | null;
        highBid: Prisma.Decimal | null;
        specialNote: string | null;
        locationCity: string | null;
        locationState: string | null;
        locationZip: string | null;
        locationCountry: string | null;
        currencyCode: string | null;
        images: string | null;
        galleryCache: string | null;
        galleryCachedAt: Date | null;
        createDateTime: string | null;
        gridRow: string | null;
        makeOfferEligible: string | null;
        buyItNowPrice: Prisma.Decimal | null;
        lastUpdatedTime: Date | null;
        rentals: string | null;
        wholesale: string | null;
        sellerName: string | null;
        offsiteAddress1: string | null;
        offsiteState: string | null;
        offsiteCity: string | null;
        offsiteZip: string | null;
        saleLight: string | null;
        autoGrade: string | null;
        announcements: string | null;
        sellerCategory: string | null;
        engineSizeL: Prisma.Decimal | null;
        locationLat: number | null;
        locationLng: number | null;
        isStale: boolean;
        discarded: boolean;
        discardReason: string | null;
        discardedAt: Date | null;
        discardedById: string | null;
    }>;
    getFilters(): Promise<{
        makes: any;
        damageTypes: any;
        saleStatuses: any;
        states: any;
        years: any;
        titleTypes: any;
    }>;
    getPortalFilters(opts: {
        year?: number;
        make?: string;
        model?: string;
        trim?: string;
    }): Promise<import("../copart/copart.service").PortalFiltersResult>;
    getListingGallery(lotNumber: string): Promise<import("../opensearch/auction-search.service").GalleryResponse>;
    getPricingForBuyer(buyer: PortalBuyer): Promise<PortalPricing>;
    getInspections(buyer: PortalBuyer): Promise<{
        data: any[];
        meta: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    }>;
    getInspection(id: string, buyer: PortalBuyer): Promise<any>;
    private signInspectionMedia;
    private fetchAndSignCarfax;
    addInspectionRequest(id: string, buyer: PortalBuyer, text: string): Promise<{
        media: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: Prisma.JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        note: string;
        inspectionId: string;
        sortOrder: number;
    }>;
    cancelInspection(id: string, buyer: PortalBuyer, reason?: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        vin: string;
        notes: string | null;
        buyerId: string | null;
        vehicleId: string | null;
        completedAt: Date | null;
        status: import("@prisma/client").$Enums.VehicleInspectionStatus;
        lotNumber: string | null;
        yardName: string | null;
        yardNumber: string | null;
        yardId: string | null;
        requestedAt: Date;
        dueAt: Date | null;
        inspectedAt: Date | null;
        inspectorId: string | null;
        specificRequest: string | null;
        overallRating: number | null;
        marketPrice: Prisma.Decimal | null;
        cancelledAt: Date | null;
        cancelReason: string | null;
        cancelledByCustomer: boolean;
        createdBy: string | null;
    }>;
    confirmOrderBySession(buyer: PortalBuyer, sessionId: string): Promise<{
        orderId: string;
        receiptNumber: string;
        type: import("@prisma/client").$Enums.PortalOrderType;
        status: import("@prisma/client").$Enums.PortalOrderStatus;
        amountCents: number;
        currency: string;
        description: string | null;
        items: any;
        breakdown: OrderReceiptDetail | null;
        createdAt: Date;
    }>;
    buildOrderReceiptDetail(order: {
        id: string;
        type: string;
        status: string;
        description: string | null;
        amount: Prisma.Decimal | number | string;
        tenantId: string | null;
        metadata: unknown;
    }): Promise<OrderReceiptDetail | null>;
    quoteInspections(buyer: PortalBuyer, dto: InspectionCartDto): Promise<InspectionQuote>;
    quotePublic(dto: InspectionCartDto): Promise<InspectionQuote>;
    checkoutInspections(buyer: PortalBuyer, dto: InspectionCartDto): Promise<{
        orderId: string;
        url: string | null;
        checkoutUrl: string | null;
        totalCents: number;
        currency: "usd";
        breakdown: InspectionQuote;
    }>;
    getLedger(buyer: PortalBuyer): Promise<{
        entries: {
            amount: string;
            id: string;
            createdAt: Date;
            description: string | null;
            status: import("@prisma/client").$Enums.CustomerLedgerEntryStatus;
            source: string | null;
            type: import("@prisma/client").$Enums.CustomerLedgerEntryType;
            stripePaymentIntentId: string | null;
            currency: string;
            relatedInspectionId: string | null;
        }[];
        balanceCents: number;
        balanceFormatted: string;
    }>;
    createDeposit(buyer: PortalBuyer, dto: CreateDepositDto): Promise<{
        orderId: string;
        url: string | null;
        checkoutUrl: string | null;
        amountCents: number;
    }>;
    checkoutFindACar(buyer: PortalBuyer, dto: FindACarCheckoutDto): Promise<{
        orderId: string;
        url: string | null;
        checkoutUrl: string | null;
    }>;
    fulfillPortalOrder(session: Stripe.Checkout.Session): Promise<void>;
    private fulfillInspectionOrder;
    private fulfillDepositOrder;
    private fulfillFindACarOrder;
    private resolveYardFees;
    private computeQuote;
    createDepositReleaseRequest(buyer: PortalBuyer, note?: string): Promise<{
        amount: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        note: string | null;
        tenantId: string | null;
        buyerId: string;
        status: import("@prisma/client").$Enums.DepositReleaseStatus;
        currency: string;
        decisionNote: string | null;
        stripeRefundId: string | null;
        decidedById: string | null;
        decidedAt: Date | null;
    }>;
    getLatestDepositReleaseRequest(buyer: PortalBuyer): Promise<{
        amount: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        note: string | null;
        tenantId: string | null;
        buyerId: string;
        status: import("@prisma/client").$Enums.DepositReleaseStatus;
        currency: string;
        decisionNote: string | null;
        stripeRefundId: string | null;
        decidedById: string | null;
        decidedAt: Date | null;
    } | null>;
    submitContactForm(data: {
        name: string;
        email: string;
        phone?: string;
        subject?: string;
        message: string;
        tenantSlug?: string;
        buyerId?: string;
    }): Promise<{
        ok: boolean;
    }>;
    getOrderForBuyer(orderId: string, buyer: PortalBuyer): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        description: string | null;
        buyerId: string;
        status: import("@prisma/client").$Enums.PortalOrderStatus;
        metadata: Prisma.JsonValue | null;
        type: import("@prisma/client").$Enums.PortalOrderType;
        amount: Prisma.Decimal;
        stripePaymentIntentId: string | null;
        currency: string;
        relatedInspectionId: string | null;
        stripeCheckoutSessionId: string | null;
    }>;
    private portalBaseUrl;
    private dashboardBaseUrl;
    private getOrCreateStripeCustomer;
}
