import { PortalService } from './portal.service';
import { PortalPricingService } from './portal-pricing.service';
import { QueryCopartDto } from '../copart/dto/query-copart.dto';
import { InspectionCartDto } from './dto/inspection-cart.dto';
import { PortalFiltersQueryDto } from './dto/portal-filters-query.dto';
import { ContactFormDto } from './dto/contact-form.dto';
export declare class PortalPublicController {
    private readonly portalService;
    private readonly pricingService;
    constructor(portalService: PortalService, pricingService: PortalPricingService);
    getFilters(query: PortalFiltersQueryDto): Promise<import("../copart/copart.service").PortalFiltersResult>;
    getListings(query: QueryCopartDto): Promise<{
        data: {
            lotNumber: string;
            inspectable: boolean;
            trim: string | null;
            createdAt: Date;
            updatedAt: Date;
            vehicleType: string | null;
            fuelType: string | null;
            vin: string | null;
            engine: string | null;
            cylinders: string | null;
            odometerBrand: string | null;
            yardName: string | null;
            yardNumber: number | null;
            yardId: string | null;
            make: string | null;
            damageDescription: string | null;
            year: number | null;
            lastSeenAt: Date | null;
            auctionName: string | null;
            copartId: number | null;
            saleDate: number | null;
            dayOfWeek: string | null;
            saleTime: string | null;
            timeZone: string | null;
            itemNumber: number | null;
            modelGroup: string | null;
            modelDetail: string | null;
            bodyStyle: string | null;
            color: string | null;
            secondaryDamage: string | null;
            saleTitleState: string | null;
            saleTitleType: string | null;
            hasKeys: string | null;
            lotCondCode: string | null;
            odometer: import("@prisma/client-runtime-utils").Decimal | null;
            estRetailValue: import("@prisma/client-runtime-utils").Decimal | null;
            repairCost: import("@prisma/client-runtime-utils").Decimal | null;
            drive: string | null;
            transmission: string | null;
            runsDrives: string | null;
            saleStatus: string | null;
            highBid: import("@prisma/client-runtime-utils").Decimal | null;
            specialNote: string | null;
            locationCity: string | null;
            locationState: string | null;
            locationZip: string | null;
            locationCountry: string | null;
            currencyCode: string | null;
            images: string | null;
            galleryCache: string | null;
            galleryCachedAt: Date | null;
            createDateTime: string | null;
            gridRow: string | null;
            makeOfferEligible: string | null;
            buyItNowPrice: import("@prisma/client-runtime-utils").Decimal | null;
            lastUpdatedTime: Date | null;
            rentals: string | null;
            wholesale: string | null;
            sellerName: string | null;
            offsiteAddress1: string | null;
            offsiteState: string | null;
            offsiteCity: string | null;
            offsiteZip: string | null;
            saleLight: string | null;
            autoGrade: string | null;
            announcements: string | null;
            sellerCategory: string | null;
            engineSizeL: import("@prisma/client-runtime-utils").Decimal | null;
            locationLat: number | null;
            locationLng: number | null;
            isStale: boolean;
            discarded: boolean;
            discardReason: string | null;
            discardedAt: Date | null;
            discardedById: string | null;
        }[];
        meta: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNextPage: boolean;
            hasPreviousPage: boolean;
        };
    }>;
    getListingGallery(lotNumber: string): Promise<import("../opensearch/auction-search.service").GalleryResponse>;
    getListingByLotNumber(lotNumber: string): Promise<{
        carfax: {
            id: any;
            aiSummary: any;
            analysis: any;
            signedUrl: any;
            date: any;
            createdAt: any;
        }[];
        lotNumber: string;
        inspectable: boolean;
        trim: string | null;
        createdAt: Date;
        updatedAt: Date;
        vehicleType: string | null;
        fuelType: string | null;
        vin: string | null;
        engine: string | null;
        cylinders: string | null;
        odometerBrand: string | null;
        yardName: string | null;
        yardNumber: number | null;
        yardId: string | null;
        make: string | null;
        damageDescription: string | null;
        year: number | null;
        lastSeenAt: Date | null;
        auctionName: string | null;
        copartId: number | null;
        saleDate: number | null;
        dayOfWeek: string | null;
        saleTime: string | null;
        timeZone: string | null;
        itemNumber: number | null;
        modelGroup: string | null;
        modelDetail: string | null;
        bodyStyle: string | null;
        color: string | null;
        secondaryDamage: string | null;
        saleTitleState: string | null;
        saleTitleType: string | null;
        hasKeys: string | null;
        lotCondCode: string | null;
        odometer: import("@prisma/client-runtime-utils").Decimal | null;
        estRetailValue: import("@prisma/client-runtime-utils").Decimal | null;
        repairCost: import("@prisma/client-runtime-utils").Decimal | null;
        drive: string | null;
        transmission: string | null;
        runsDrives: string | null;
        saleStatus: string | null;
        highBid: import("@prisma/client-runtime-utils").Decimal | null;
        specialNote: string | null;
        locationCity: string | null;
        locationState: string | null;
        locationZip: string | null;
        locationCountry: string | null;
        currencyCode: string | null;
        images: string | null;
        galleryCache: string | null;
        galleryCachedAt: Date | null;
        createDateTime: string | null;
        gridRow: string | null;
        makeOfferEligible: string | null;
        buyItNowPrice: import("@prisma/client-runtime-utils").Decimal | null;
        lastUpdatedTime: Date | null;
        rentals: string | null;
        wholesale: string | null;
        sellerName: string | null;
        offsiteAddress1: string | null;
        offsiteState: string | null;
        offsiteCity: string | null;
        offsiteZip: string | null;
        saleLight: string | null;
        autoGrade: string | null;
        announcements: string | null;
        sellerCategory: string | null;
        engineSizeL: import("@prisma/client-runtime-utils").Decimal | null;
        locationLat: number | null;
        locationLng: number | null;
        isStale: boolean;
        discarded: boolean;
        discardReason: string | null;
        discardedAt: Date | null;
        discardedById: string | null;
    }>;
    getPricing(): Promise<import("./portal-pricing.service").PortalPricing>;
    quote(dto: InspectionCartDto): Promise<import("./portal.service").InspectionQuote>;
    submitContact(dto: ContactFormDto): Promise<{
        ok: boolean;
    }>;
}
