import { PrismaService } from '@htownautos/prisma';
import { CreatePhoneCallDto, UpdatePhoneCallDto } from './dto/create-phone-call.dto';
import { QueryPhoneCallDto } from './dto/query-phone-call.dto';
import { Prisma } from '@prisma/client';
export declare class PhoneCallsService {
    private prisma;
    private readonly logger;
    constructor(prisma: PrismaService);
    canUserAccessRecordings(tenantId: string, userId: string): Promise<boolean>;
    private filterSensitiveData;
    private readonly includeRelations;
    create(tenantId: string, createPhoneCallDto: CreatePhoneCallDto, callerId: string): Promise<{
        buyer: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            phoneMain: string;
            phoneMobile: string | null;
        } | null;
        transferredFrom: ({
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
                avatar: string | null;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: Prisma.JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
        transferredTo: ({
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
                avatar: string | null;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: Prisma.JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
        caller: ({
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
                avatar: string | null;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: Prisma.JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        metaValue: Prisma.JsonValue | null;
        buyerId: string | null;
        status: string;
        duration: number | null;
        callerId: string | null;
        direction: string;
        fromNumber: string;
        toNumber: string;
        startedAt: Date;
        answeredAt: Date | null;
        endedAt: Date | null;
        outcome: string | null;
        twilioCallSid: string | null;
        twilioRecordingSid: string | null;
        conferenceSid: string | null;
        conferenceName: string | null;
        segmentNumber: number;
        recordingUrl: string | null;
        recordingDuration: number | null;
        transcription: string | null;
        transcriptionStatus: string | null;
        aiSummary: string | null;
        aiSentiment: string | null;
        aiKeyPoints: Prisma.JsonValue | null;
        aiNextSteps: Prisma.JsonValue | null;
        transferredAt: Date | null;
        transferredToUserId: string | null;
        transferredFromUserId: string | null;
        transferReason: string | null;
        parentCallId: string | null;
    }>;
    findAll(tenantId: string, query: QueryPhoneCallDto, canAccessRecordings?: boolean): Promise<{
        data: ({
            buyer: {
                id: string;
                email: string;
                firstName: string;
                lastName: string;
                phoneMain: string;
                phoneMobile: string | null;
            } | null;
            transferredFrom: ({
                user: {
                    id: string;
                    email: string;
                    firstName: string | null;
                    lastName: string | null;
                    avatar: string | null;
                };
            } & {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                userId: string;
                status: string;
                username: string | null;
                tenantEmail: string | null;
                extension: string | null;
                permissions: Prisma.JsonValue | null;
                roleId: string;
                acceptedAt: Date | null;
                invitationCode: string | null;
                invitationSentAt: Date | null;
                invitedBy: string | null;
                removedAt: Date | null;
            }) | null;
            transferredTo: ({
                user: {
                    id: string;
                    email: string;
                    firstName: string | null;
                    lastName: string | null;
                    avatar: string | null;
                };
            } & {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                userId: string;
                status: string;
                username: string | null;
                tenantEmail: string | null;
                extension: string | null;
                permissions: Prisma.JsonValue | null;
                roleId: string;
                acceptedAt: Date | null;
                invitationCode: string | null;
                invitationSentAt: Date | null;
                invitedBy: string | null;
                removedAt: Date | null;
            }) | null;
            caller: ({
                user: {
                    id: string;
                    email: string;
                    firstName: string | null;
                    lastName: string | null;
                    avatar: string | null;
                };
            } & {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                userId: string;
                status: string;
                username: string | null;
                tenantEmail: string | null;
                extension: string | null;
                permissions: Prisma.JsonValue | null;
                roleId: string;
                acceptedAt: Date | null;
                invitationCode: string | null;
                invitationSentAt: Date | null;
                invitedBy: string | null;
                removedAt: Date | null;
            }) | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            notes: string | null;
            metaValue: Prisma.JsonValue | null;
            buyerId: string | null;
            status: string;
            duration: number | null;
            callerId: string | null;
            direction: string;
            fromNumber: string;
            toNumber: string;
            startedAt: Date;
            answeredAt: Date | null;
            endedAt: Date | null;
            outcome: string | null;
            twilioCallSid: string | null;
            twilioRecordingSid: string | null;
            conferenceSid: string | null;
            conferenceName: string | null;
            segmentNumber: number;
            recordingUrl: string | null;
            recordingDuration: number | null;
            transcription: string | null;
            transcriptionStatus: string | null;
            aiSummary: string | null;
            aiSentiment: string | null;
            aiKeyPoints: Prisma.JsonValue | null;
            aiNextSteps: Prisma.JsonValue | null;
            transferredAt: Date | null;
            transferredToUserId: string | null;
            transferredFromUserId: string | null;
            transferReason: string | null;
            parentCallId: string | null;
        })[];
        total: number;
        page: number;
        limit: number;
        totalPages: number;
        canAccessRecordings: boolean;
    }>;
    findOne(tenantId: string, id: string, canAccessRecordings?: boolean): Promise<{
        buyer: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            phoneMain: string;
            phoneMobile: string | null;
        } | null;
        transferredFrom: ({
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
                avatar: string | null;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: Prisma.JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
        transferredTo: ({
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
                avatar: string | null;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: Prisma.JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
        caller: ({
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
                avatar: string | null;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: Prisma.JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        metaValue: Prisma.JsonValue | null;
        buyerId: string | null;
        status: string;
        duration: number | null;
        callerId: string | null;
        direction: string;
        fromNumber: string;
        toNumber: string;
        startedAt: Date;
        answeredAt: Date | null;
        endedAt: Date | null;
        outcome: string | null;
        twilioCallSid: string | null;
        twilioRecordingSid: string | null;
        conferenceSid: string | null;
        conferenceName: string | null;
        segmentNumber: number;
        recordingUrl: string | null;
        recordingDuration: number | null;
        transcription: string | null;
        transcriptionStatus: string | null;
        aiSummary: string | null;
        aiSentiment: string | null;
        aiKeyPoints: Prisma.JsonValue | null;
        aiNextSteps: Prisma.JsonValue | null;
        transferredAt: Date | null;
        transferredToUserId: string | null;
        transferredFromUserId: string | null;
        transferReason: string | null;
        parentCallId: string | null;
    }>;
    update(tenantId: string, id: string, updatePhoneCallDto: UpdatePhoneCallDto): Promise<{
        buyer: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            phoneMain: string;
            phoneMobile: string | null;
        } | null;
        transferredFrom: ({
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
                avatar: string | null;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: Prisma.JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
        transferredTo: ({
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
                avatar: string | null;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: Prisma.JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
        caller: ({
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
                avatar: string | null;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: Prisma.JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        metaValue: Prisma.JsonValue | null;
        buyerId: string | null;
        status: string;
        duration: number | null;
        callerId: string | null;
        direction: string;
        fromNumber: string;
        toNumber: string;
        startedAt: Date;
        answeredAt: Date | null;
        endedAt: Date | null;
        outcome: string | null;
        twilioCallSid: string | null;
        twilioRecordingSid: string | null;
        conferenceSid: string | null;
        conferenceName: string | null;
        segmentNumber: number;
        recordingUrl: string | null;
        recordingDuration: number | null;
        transcription: string | null;
        transcriptionStatus: string | null;
        aiSummary: string | null;
        aiSentiment: string | null;
        aiKeyPoints: Prisma.JsonValue | null;
        aiNextSteps: Prisma.JsonValue | null;
        transferredAt: Date | null;
        transferredToUserId: string | null;
        transferredFromUserId: string | null;
        transferReason: string | null;
        parentCallId: string | null;
    }>;
    remove(tenantId: string, id: string): Promise<{
        message: string;
    }>;
    findByBuyer(tenantId: string, buyerId: string, query: QueryPhoneCallDto, canAccessRecordings?: boolean): Promise<{
        data: ({
            buyer: {
                id: string;
                email: string;
                firstName: string;
                lastName: string;
                phoneMain: string;
                phoneMobile: string | null;
            } | null;
            transferredFrom: ({
                user: {
                    id: string;
                    email: string;
                    firstName: string | null;
                    lastName: string | null;
                    avatar: string | null;
                };
            } & {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                userId: string;
                status: string;
                username: string | null;
                tenantEmail: string | null;
                extension: string | null;
                permissions: Prisma.JsonValue | null;
                roleId: string;
                acceptedAt: Date | null;
                invitationCode: string | null;
                invitationSentAt: Date | null;
                invitedBy: string | null;
                removedAt: Date | null;
            }) | null;
            transferredTo: ({
                user: {
                    id: string;
                    email: string;
                    firstName: string | null;
                    lastName: string | null;
                    avatar: string | null;
                };
            } & {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                userId: string;
                status: string;
                username: string | null;
                tenantEmail: string | null;
                extension: string | null;
                permissions: Prisma.JsonValue | null;
                roleId: string;
                acceptedAt: Date | null;
                invitationCode: string | null;
                invitationSentAt: Date | null;
                invitedBy: string | null;
                removedAt: Date | null;
            }) | null;
            caller: ({
                user: {
                    id: string;
                    email: string;
                    firstName: string | null;
                    lastName: string | null;
                    avatar: string | null;
                };
            } & {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                userId: string;
                status: string;
                username: string | null;
                tenantEmail: string | null;
                extension: string | null;
                permissions: Prisma.JsonValue | null;
                roleId: string;
                acceptedAt: Date | null;
                invitationCode: string | null;
                invitationSentAt: Date | null;
                invitedBy: string | null;
                removedAt: Date | null;
            }) | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            notes: string | null;
            metaValue: Prisma.JsonValue | null;
            buyerId: string | null;
            status: string;
            duration: number | null;
            callerId: string | null;
            direction: string;
            fromNumber: string;
            toNumber: string;
            startedAt: Date;
            answeredAt: Date | null;
            endedAt: Date | null;
            outcome: string | null;
            twilioCallSid: string | null;
            twilioRecordingSid: string | null;
            conferenceSid: string | null;
            conferenceName: string | null;
            segmentNumber: number;
            recordingUrl: string | null;
            recordingDuration: number | null;
            transcription: string | null;
            transcriptionStatus: string | null;
            aiSummary: string | null;
            aiSentiment: string | null;
            aiKeyPoints: Prisma.JsonValue | null;
            aiNextSteps: Prisma.JsonValue | null;
            transferredAt: Date | null;
            transferredToUserId: string | null;
            transferredFromUserId: string | null;
            transferReason: string | null;
            parentCallId: string | null;
        })[];
        total: number;
        page: number;
        limit: number;
        totalPages: number;
        canAccessRecordings: boolean;
    }>;
    findByPhoneNumbers(tenantId: string, phoneNumbers: string[], query: QueryPhoneCallDto, canAccessRecordings?: boolean): Promise<{
        data: ({
            buyer: {
                id: string;
                email: string;
                firstName: string;
                lastName: string;
                phoneMain: string;
                phoneMobile: string | null;
            } | null;
            transferredFrom: ({
                user: {
                    id: string;
                    email: string;
                    firstName: string | null;
                    lastName: string | null;
                    avatar: string | null;
                };
            } & {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                userId: string;
                status: string;
                username: string | null;
                tenantEmail: string | null;
                extension: string | null;
                permissions: Prisma.JsonValue | null;
                roleId: string;
                acceptedAt: Date | null;
                invitationCode: string | null;
                invitationSentAt: Date | null;
                invitedBy: string | null;
                removedAt: Date | null;
            }) | null;
            transferredTo: ({
                user: {
                    id: string;
                    email: string;
                    firstName: string | null;
                    lastName: string | null;
                    avatar: string | null;
                };
            } & {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                userId: string;
                status: string;
                username: string | null;
                tenantEmail: string | null;
                extension: string | null;
                permissions: Prisma.JsonValue | null;
                roleId: string;
                acceptedAt: Date | null;
                invitationCode: string | null;
                invitationSentAt: Date | null;
                invitedBy: string | null;
                removedAt: Date | null;
            }) | null;
            caller: ({
                user: {
                    id: string;
                    email: string;
                    firstName: string | null;
                    lastName: string | null;
                    avatar: string | null;
                };
            } & {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                userId: string;
                status: string;
                username: string | null;
                tenantEmail: string | null;
                extension: string | null;
                permissions: Prisma.JsonValue | null;
                roleId: string;
                acceptedAt: Date | null;
                invitationCode: string | null;
                invitationSentAt: Date | null;
                invitedBy: string | null;
                removedAt: Date | null;
            }) | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            notes: string | null;
            metaValue: Prisma.JsonValue | null;
            buyerId: string | null;
            status: string;
            duration: number | null;
            callerId: string | null;
            direction: string;
            fromNumber: string;
            toNumber: string;
            startedAt: Date;
            answeredAt: Date | null;
            endedAt: Date | null;
            outcome: string | null;
            twilioCallSid: string | null;
            twilioRecordingSid: string | null;
            conferenceSid: string | null;
            conferenceName: string | null;
            segmentNumber: number;
            recordingUrl: string | null;
            recordingDuration: number | null;
            transcription: string | null;
            transcriptionStatus: string | null;
            aiSummary: string | null;
            aiSentiment: string | null;
            aiKeyPoints: Prisma.JsonValue | null;
            aiNextSteps: Prisma.JsonValue | null;
            transferredAt: Date | null;
            transferredToUserId: string | null;
            transferredFromUserId: string | null;
            transferReason: string | null;
            parentCallId: string | null;
        })[];
        total: number;
        page: number;
        limit: number;
        totalPages: number;
        canAccessRecordings: boolean;
    }>;
    getCallStats(tenantId: string, buyerId?: string, callerId?: string): Promise<{
        total: number;
        completed: number;
        missed: number;
        totalDuration: number;
        averageDuration: number;
    }>;
}
