import { OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { PrismaService } from '@htownautos/prisma';
import { AuctionSyncService } from '@htownautos/opensearch';
import { WantedMatchNotifierService } from './wanted-match-notifier.service';
export declare class CopartImportService implements OnModuleInit {
    private readonly configService;
    private readonly prisma;
    private readonly syncService;
    private readonly wantedMatchNotifier;
    onModuleInit(): Promise<void>;
    private readonly logger;
    private readonly pool;
    private activeSyncRunId;
    private lastWrittenProgress;
    private lastProgressWriteTs;
    constructor(configService: ConfigService, prisma: PrismaService, syncService: AuctionSyncService, wantedMatchNotifier: WantedMatchNotifierService);
    private updateProgress;
    private _lastPhase;
    private notifySyncFailure;
    handleCopartSyncCron(): Promise<void>;
    runSync(): Promise<void>;
    private importFromCopartUrl;
    private downloadCsvWithRetry;
    private downloadCsvOnce;
    private parseCsv;
    private assertFeedSanity;
    private validateRows;
    private insertIntoStaging;
    private assertSingleResult;
    private mapStagingToAuctionListings;
    private markStaleListings;
    private deriveAuctionAttributes;
    private truncateStaging;
    private sleep;
}
