import { PrismaService } from '@htownautos/prisma';
import { MediaService } from '@htownautos/media';
import { Prisma } from '@prisma/client';
import { CreateInventoryAssetDto, UpdateInventoryAssetDto, QueryInventoryAssetDto } from './dto';
export declare class InventoryAssetsService {
    private prisma;
    private readonly mediaService;
    private readonly logger;
    private readonly openai;
    constructor(prisma: PrismaService, mediaService: MediaService);
    private generateAssetTag;
    create(tenantId: string, dto: CreateInventoryAssetDto): Promise<{
        model: string | null;
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        description: string | null;
        notes: string | null;
        purchaseDate: Date | null;
        status: string;
        shippingCost: Prisma.Decimal | null;
        tax: Prisma.Decimal | null;
        category: string | null;
        quantity: number;
        location: string | null;
        supplier: string | null;
        brand: string | null;
        assetTag: string | null;
        serialNumber: string | null;
        condition: string;
        assignedTo: string | null;
        purchasePrice: Prisma.Decimal | null;
        currentValue: Prisma.Decimal | null;
        warrantyExpiry: Date | null;
        receiptIds: string[];
        imageUrl: string | null;
    }>;
    getStats(tenantId: string): Promise<{
        totalItems: number;
        totalValue: number;
    }>;
    findAll(tenantId: string, query: QueryInventoryAssetDto): Promise<{
        data: {
            model: string | null;
            name: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            description: string | null;
            notes: string | null;
            purchaseDate: Date | null;
            status: string;
            shippingCost: Prisma.Decimal | null;
            tax: Prisma.Decimal | null;
            category: string | null;
            quantity: number;
            location: string | null;
            supplier: string | null;
            brand: string | null;
            assetTag: string | null;
            serialNumber: string | null;
            condition: string;
            assignedTo: string | null;
            purchasePrice: Prisma.Decimal | null;
            currentValue: Prisma.Decimal | null;
            warrantyExpiry: Date | null;
            receiptIds: string[];
            imageUrl: string | null;
        }[];
        meta: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
            hasNextPage: boolean;
            hasPreviousPage: boolean;
        };
    }>;
    findOne(tenantId: string, id: string): Promise<{
        model: string | null;
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        description: string | null;
        notes: string | null;
        purchaseDate: Date | null;
        status: string;
        shippingCost: Prisma.Decimal | null;
        tax: Prisma.Decimal | null;
        category: string | null;
        quantity: number;
        location: string | null;
        supplier: string | null;
        brand: string | null;
        assetTag: string | null;
        serialNumber: string | null;
        condition: string;
        assignedTo: string | null;
        purchasePrice: Prisma.Decimal | null;
        currentValue: Prisma.Decimal | null;
        warrantyExpiry: Date | null;
        receiptIds: string[];
        imageUrl: string | null;
    }>;
    update(tenantId: string, id: string, dto: UpdateInventoryAssetDto): Promise<{
        model: string | null;
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        description: string | null;
        notes: string | null;
        purchaseDate: Date | null;
        status: string;
        shippingCost: Prisma.Decimal | null;
        tax: Prisma.Decimal | null;
        category: string | null;
        quantity: number;
        location: string | null;
        supplier: string | null;
        brand: string | null;
        assetTag: string | null;
        serialNumber: string | null;
        condition: string;
        assignedTo: string | null;
        purchasePrice: Prisma.Decimal | null;
        currentValue: Prisma.Decimal | null;
        warrantyExpiry: Date | null;
        receiptIds: string[];
        imageUrl: string | null;
    }>;
    remove(tenantId: string, id: string): Promise<{
        message: string;
    }>;
    private extractStructuredData;
    analyzeUrl(url: string): Promise<any>;
    analyzeReceiptItems(mediaIds: string[]): Promise<any>;
    bulkCreate(tenantId: string, assets: CreateInventoryAssetDto[]): Promise<{
        count: number;
        assets: any[];
    }>;
    analyzeImages(mediaIds: string[]): Promise<any>;
}
