import { PrismaService } from '@htownautos/prisma';
import { CreateTitleDto } from './dto/create-title.dto';
import { UpdateTitleDto } from './dto/update-title.dto';
export declare class TitleService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    private readonly includeRelations;
    findByVehicle(vehicleId: string): Promise<({
        titleStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        brandStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        backImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
        frontImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        notes: string | null;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        vehicleId: string;
        titleFee: import("@prisma/client-runtime-utils").Decimal | null;
        totalFees: import("@prisma/client-runtime-utils").Decimal | null;
        form8300Filed: boolean;
        internalNotes: string | null;
        titleNumber: string | null;
        titleState: string | null;
        titleType: string | null;
        titleStatusId: string | null;
        brandStatusId: string | null;
        titleIssueDate: Date | null;
        titleReceivedDate: Date | null;
        titleSentDate: Date | null;
        ownerName: string | null;
        ownerAddress: string | null;
        ownerCity: string | null;
        ownerState: string | null;
        ownerZipCode: string | null;
        coOwnerName: string | null;
        coOwnerAddress: string | null;
        hasLien: boolean;
        lienHolder: string | null;
        lienHolderAddress: string | null;
        lienHolderCity: string | null;
        lienHolderState: string | null;
        lienHolderZipCode: string | null;
        lienAmount: import("@prisma/client-runtime-utils").Decimal | null;
        lienDate: Date | null;
        lienReleaseDate: Date | null;
        hasSecondLien: boolean;
        secondLienHolder: string | null;
        secondLienAmount: import("@prisma/client-runtime-utils").Decimal | null;
        odometerReading: number | null;
        odometerDate: Date | null;
        odometerDisclosure: string | null;
        odometerBrand: string | null;
        titleVIN: string | null;
        titleYear: number | null;
        titleMake: string | null;
        titleModel: string | null;
        titleBodyStyle: string | null;
        titleColor: string | null;
        isPendingTransfer: boolean;
        transferDate: Date | null;
        transferredFrom: string | null;
        transferredTo: string | null;
        fileId: string | null;
        lienReleaseFileId: string | null;
        billOfSaleFileId: string | null;
        odometerStatementFileId: string | null;
        titleVerified: boolean;
        titleVerifiedDate: Date | null;
        titleVerifiedBy: string | null;
        isElectronic: boolean;
        electronicTitleId: string | null;
        nmvtisChecked: boolean;
        nmvtisCheckDate: Date | null;
        nmvtisStatus: string | null;
        currentLocation: string | null;
        shippingTracking: string | null;
        expectedReturnDate: Date | null;
        transferFee: import("@prisma/client-runtime-utils").Decimal | null;
        liensatisfactionFee: import("@prisma/client-runtime-utils").Decimal | null;
        form8300Required: boolean;
        backImageId: string | null;
        frontImageId: string | null;
        titleAppNumber: string | null;
    }) | null>;
    upsert(vehicleId: string, dto: CreateTitleDto | UpdateTitleDto): Promise<{
        titleStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        brandStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        backImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
        frontImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        notes: string | null;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        vehicleId: string;
        titleFee: import("@prisma/client-runtime-utils").Decimal | null;
        totalFees: import("@prisma/client-runtime-utils").Decimal | null;
        form8300Filed: boolean;
        internalNotes: string | null;
        titleNumber: string | null;
        titleState: string | null;
        titleType: string | null;
        titleStatusId: string | null;
        brandStatusId: string | null;
        titleIssueDate: Date | null;
        titleReceivedDate: Date | null;
        titleSentDate: Date | null;
        ownerName: string | null;
        ownerAddress: string | null;
        ownerCity: string | null;
        ownerState: string | null;
        ownerZipCode: string | null;
        coOwnerName: string | null;
        coOwnerAddress: string | null;
        hasLien: boolean;
        lienHolder: string | null;
        lienHolderAddress: string | null;
        lienHolderCity: string | null;
        lienHolderState: string | null;
        lienHolderZipCode: string | null;
        lienAmount: import("@prisma/client-runtime-utils").Decimal | null;
        lienDate: Date | null;
        lienReleaseDate: Date | null;
        hasSecondLien: boolean;
        secondLienHolder: string | null;
        secondLienAmount: import("@prisma/client-runtime-utils").Decimal | null;
        odometerReading: number | null;
        odometerDate: Date | null;
        odometerDisclosure: string | null;
        odometerBrand: string | null;
        titleVIN: string | null;
        titleYear: number | null;
        titleMake: string | null;
        titleModel: string | null;
        titleBodyStyle: string | null;
        titleColor: string | null;
        isPendingTransfer: boolean;
        transferDate: Date | null;
        transferredFrom: string | null;
        transferredTo: string | null;
        fileId: string | null;
        lienReleaseFileId: string | null;
        billOfSaleFileId: string | null;
        odometerStatementFileId: string | null;
        titleVerified: boolean;
        titleVerifiedDate: Date | null;
        titleVerifiedBy: string | null;
        isElectronic: boolean;
        electronicTitleId: string | null;
        nmvtisChecked: boolean;
        nmvtisCheckDate: Date | null;
        nmvtisStatus: string | null;
        currentLocation: string | null;
        shippingTracking: string | null;
        expectedReturnDate: Date | null;
        transferFee: import("@prisma/client-runtime-utils").Decimal | null;
        liensatisfactionFee: import("@prisma/client-runtime-utils").Decimal | null;
        form8300Required: boolean;
        backImageId: string | null;
        frontImageId: string | null;
        titleAppNumber: string | null;
    }>;
    findOne(id: string): Promise<{
        titleStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        brandStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        backImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
        frontImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        notes: string | null;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        vehicleId: string;
        titleFee: import("@prisma/client-runtime-utils").Decimal | null;
        totalFees: import("@prisma/client-runtime-utils").Decimal | null;
        form8300Filed: boolean;
        internalNotes: string | null;
        titleNumber: string | null;
        titleState: string | null;
        titleType: string | null;
        titleStatusId: string | null;
        brandStatusId: string | null;
        titleIssueDate: Date | null;
        titleReceivedDate: Date | null;
        titleSentDate: Date | null;
        ownerName: string | null;
        ownerAddress: string | null;
        ownerCity: string | null;
        ownerState: string | null;
        ownerZipCode: string | null;
        coOwnerName: string | null;
        coOwnerAddress: string | null;
        hasLien: boolean;
        lienHolder: string | null;
        lienHolderAddress: string | null;
        lienHolderCity: string | null;
        lienHolderState: string | null;
        lienHolderZipCode: string | null;
        lienAmount: import("@prisma/client-runtime-utils").Decimal | null;
        lienDate: Date | null;
        lienReleaseDate: Date | null;
        hasSecondLien: boolean;
        secondLienHolder: string | null;
        secondLienAmount: import("@prisma/client-runtime-utils").Decimal | null;
        odometerReading: number | null;
        odometerDate: Date | null;
        odometerDisclosure: string | null;
        odometerBrand: string | null;
        titleVIN: string | null;
        titleYear: number | null;
        titleMake: string | null;
        titleModel: string | null;
        titleBodyStyle: string | null;
        titleColor: string | null;
        isPendingTransfer: boolean;
        transferDate: Date | null;
        transferredFrom: string | null;
        transferredTo: string | null;
        fileId: string | null;
        lienReleaseFileId: string | null;
        billOfSaleFileId: string | null;
        odometerStatementFileId: string | null;
        titleVerified: boolean;
        titleVerifiedDate: Date | null;
        titleVerifiedBy: string | null;
        isElectronic: boolean;
        electronicTitleId: string | null;
        nmvtisChecked: boolean;
        nmvtisCheckDate: Date | null;
        nmvtisStatus: string | null;
        currentLocation: string | null;
        shippingTracking: string | null;
        expectedReturnDate: Date | null;
        transferFee: import("@prisma/client-runtime-utils").Decimal | null;
        liensatisfactionFee: import("@prisma/client-runtime-utils").Decimal | null;
        form8300Required: boolean;
        backImageId: string | null;
        frontImageId: string | null;
        titleAppNumber: string | null;
    }>;
    update(id: string, dto: UpdateTitleDto): Promise<{
        titleStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        brandStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        backImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
        frontImage: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        notes: string | null;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        vehicleId: string;
        titleFee: import("@prisma/client-runtime-utils").Decimal | null;
        totalFees: import("@prisma/client-runtime-utils").Decimal | null;
        form8300Filed: boolean;
        internalNotes: string | null;
        titleNumber: string | null;
        titleState: string | null;
        titleType: string | null;
        titleStatusId: string | null;
        brandStatusId: string | null;
        titleIssueDate: Date | null;
        titleReceivedDate: Date | null;
        titleSentDate: Date | null;
        ownerName: string | null;
        ownerAddress: string | null;
        ownerCity: string | null;
        ownerState: string | null;
        ownerZipCode: string | null;
        coOwnerName: string | null;
        coOwnerAddress: string | null;
        hasLien: boolean;
        lienHolder: string | null;
        lienHolderAddress: string | null;
        lienHolderCity: string | null;
        lienHolderState: string | null;
        lienHolderZipCode: string | null;
        lienAmount: import("@prisma/client-runtime-utils").Decimal | null;
        lienDate: Date | null;
        lienReleaseDate: Date | null;
        hasSecondLien: boolean;
        secondLienHolder: string | null;
        secondLienAmount: import("@prisma/client-runtime-utils").Decimal | null;
        odometerReading: number | null;
        odometerDate: Date | null;
        odometerDisclosure: string | null;
        odometerBrand: string | null;
        titleVIN: string | null;
        titleYear: number | null;
        titleMake: string | null;
        titleModel: string | null;
        titleBodyStyle: string | null;
        titleColor: string | null;
        isPendingTransfer: boolean;
        transferDate: Date | null;
        transferredFrom: string | null;
        transferredTo: string | null;
        fileId: string | null;
        lienReleaseFileId: string | null;
        billOfSaleFileId: string | null;
        odometerStatementFileId: string | null;
        titleVerified: boolean;
        titleVerifiedDate: Date | null;
        titleVerifiedBy: string | null;
        isElectronic: boolean;
        electronicTitleId: string | null;
        nmvtisChecked: boolean;
        nmvtisCheckDate: Date | null;
        nmvtisStatus: string | null;
        currentLocation: string | null;
        shippingTracking: string | null;
        expectedReturnDate: Date | null;
        transferFee: import("@prisma/client-runtime-utils").Decimal | null;
        liensatisfactionFee: import("@prisma/client-runtime-utils").Decimal | null;
        form8300Required: boolean;
        backImageId: string | null;
        frontImageId: string | null;
        titleAppNumber: string | null;
    }>;
}
