import { VehicleInspectionsService } from './vehicle-inspections.service';
import { CreateVehicleInspectionDto } from './dto/create-vehicle-inspection.dto';
import { UpdateVehicleInspectionDto } from './dto/update-vehicle-inspection.dto';
import { ListVehicleInspectionsDto } from './dto/list-vehicle-inspections.dto';
import { CreateChecklistItemDto } from './dto/create-checklist-item.dto';
import { UpdateChecklistItemDto } from './dto/update-checklist-item.dto';
import { CreateRequestItemDto } from './dto/create-request-item.dto';
import { UpdateRequestItemDto } from './dto/update-request-item.dto';
import { CreateInspectionErrorCodeDto } from './dto/create-inspection-error-code.dto';
import { UpdateInspectionErrorCodeDto } from './dto/update-inspection-error-code.dto';
export declare class VehicleInspectionsController {
    private readonly service;
    constructor(service: VehicleInspectionsService);
    list(tenantId: string, userId: string, query: ListVehicleInspectionsDto): Promise<{
        data: any[];
        meta: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    }>;
    get(tenantId: string, userId: string, id: string): Promise<any>;
    create(tenantId: string, userId: string, dto: CreateVehicleInspectionDto): Promise<any>;
    update(tenantId: string, id: string, dto: UpdateVehicleInspectionDto): Promise<any>;
    remove(tenantId: string, id: string): Promise<{
        deleted: boolean;
        mediaCleaned: number;
    }>;
    removeMany(tenantId: string, body: {
        ids: string[];
    }): Promise<{
        deleted: number;
        mediaCleaned: number;
    }>;
    addChecklistItem(tenantId: string, id: string, dto: CreateChecklistItemDto): Promise<{
        media: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        part: string;
        notes: string | null;
        category: import("@prisma/client").$Enums.ChecklistCategory;
        inspectionId: string;
        sortOrder: number;
        quality: number | null;
        voiceNoteTranscription: string | null;
    }>;
    updateChecklistItem(tenantId: string, id: string, itemId: string, dto: UpdateChecklistItemDto): Promise<{
        media: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        part: string;
        notes: string | null;
        category: import("@prisma/client").$Enums.ChecklistCategory;
        inspectionId: string;
        sortOrder: number;
        quality: number | null;
        voiceNoteTranscription: string | null;
    }>;
    removeChecklistItem(tenantId: string, id: string, itemId: string): Promise<{
        deleted: boolean;
    }>;
    addRequestItem(tenantId: string, id: string, dto: CreateRequestItemDto): Promise<{
        media: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        note: string;
        inspectionId: string;
        sortOrder: number;
    }>;
    updateRequestItem(tenantId: string, id: string, itemId: string, dto: UpdateRequestItemDto): Promise<{
        media: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        note: string;
        inspectionId: string;
        sortOrder: number;
    }>;
    removeRequestItem(tenantId: string, id: string, itemId: string): Promise<{
        deleted: boolean;
    }>;
    addErrorCode(tenantId: string, id: string, dto: CreateInspectionErrorCodeDto): Promise<{
        media: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        note: string | null;
        description: string | null;
        level: import("@prisma/client").$Enums.InspectionErrorLevel;
        inspectionId: string;
        code: string;
        sortOrder: number;
        voiceNoteTranscription: string | null;
    }>;
    updateErrorCode(tenantId: string, id: string, itemId: string, dto: UpdateInspectionErrorCodeDto): Promise<{
        media: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        note: string | null;
        description: string | null;
        level: import("@prisma/client").$Enums.InspectionErrorLevel;
        inspectionId: string;
        code: string;
        sortOrder: number;
        voiceNoteTranscription: string | null;
    }>;
    removeErrorCode(tenantId: string, id: string, itemId: string): Promise<{
        deleted: boolean;
    }>;
}
