import { Prisma } from '@prisma/client';
import { PrismaService } from '@htownautos/prisma';
import { S3Service } from '@htownautos/common';
import { CreateVehicleInspectionDto } from './dto/create-vehicle-inspection.dto';
import { UpdateVehicleInspectionDto } from './dto/update-vehicle-inspection.dto';
import { ListVehicleInspectionsDto } from './dto/list-vehicle-inspections.dto';
import { CreateChecklistItemDto } from './dto/create-checklist-item.dto';
import { UpdateChecklistItemDto } from './dto/update-checklist-item.dto';
import { CreateRequestItemDto } from './dto/create-request-item.dto';
import { UpdateRequestItemDto } from './dto/update-request-item.dto';
import { CreateInspectionErrorCodeDto } from './dto/create-inspection-error-code.dto';
import { UpdateInspectionErrorCodeDto } from './dto/update-inspection-error-code.dto';
export declare class VehicleInspectionsService {
    private readonly prisma;
    private readonly s3;
    private readonly logger;
    constructor(prisma: PrismaService, s3: S3Service);
    list(tenantId: string, userId: string | null, query: ListVehicleInspectionsDto): Promise<{
        data: any[];
        meta: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    }>;
    get(id: string, tenantId: string, userId: string | null): Promise<any>;
    create(tenantId: string, userId: string | null, dto: CreateVehicleInspectionDto): Promise<any>;
    update(id: string, tenantId: string, dto: UpdateVehicleInspectionDto): Promise<any>;
    remove(id: string, tenantId: string): Promise<{
        deleted: boolean;
        mediaCleaned: number;
    }>;
    removeMany(ids: string[], tenantId: string): Promise<{
        deleted: number;
        mediaCleaned: number;
    }>;
    private collectInspectionStorageKeys;
    private cleanupS3Keys;
    addChecklistItem(inspectionId: string, tenantId: string, dto: CreateChecklistItemDto): Promise<{
        media: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: Prisma.JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        part: string;
        notes: string | null;
        category: import("@prisma/client").$Enums.ChecklistCategory;
        inspectionId: string;
        sortOrder: number;
        quality: number | null;
        voiceNoteTranscription: string | null;
    }>;
    updateChecklistItem(itemId: string, inspectionId: string, tenantId: string, dto: UpdateChecklistItemDto): Promise<{
        media: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: Prisma.JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        part: string;
        notes: string | null;
        category: import("@prisma/client").$Enums.ChecklistCategory;
        inspectionId: string;
        sortOrder: number;
        quality: number | null;
        voiceNoteTranscription: string | null;
    }>;
    removeChecklistItem(itemId: string, inspectionId: string, tenantId: string): Promise<{
        deleted: boolean;
    }>;
    addRequestItem(inspectionId: string, tenantId: string, dto: CreateRequestItemDto): Promise<{
        media: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: Prisma.JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        note: string;
        inspectionId: string;
        sortOrder: number;
    }>;
    updateRequestItem(itemId: string, inspectionId: string, tenantId: string, dto: UpdateRequestItemDto): Promise<{
        media: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: Prisma.JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        note: string;
        inspectionId: string;
        sortOrder: number;
    }>;
    removeRequestItem(itemId: string, inspectionId: string, tenantId: string): Promise<{
        deleted: boolean;
    }>;
    addErrorCode(inspectionId: string, tenantId: string, dto: CreateInspectionErrorCodeDto): Promise<{
        media: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: Prisma.JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        note: string | null;
        description: string | null;
        level: import("@prisma/client").$Enums.InspectionErrorLevel;
        inspectionId: string;
        code: string;
        sortOrder: number;
        voiceNoteTranscription: string | null;
    }>;
    updateErrorCode(itemId: string, inspectionId: string, tenantId: string, dto: UpdateInspectionErrorCodeDto): Promise<{
        media: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: Prisma.JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        note: string | null;
        description: string | null;
        level: import("@prisma/client").$Enums.InspectionErrorLevel;
        inspectionId: string;
        code: string;
        sortOrder: number;
        voiceNoteTranscription: string | null;
    }>;
    removeErrorCode(itemId: string, inspectionId: string, tenantId: string): Promise<{
        deleted: boolean;
    }>;
    private validateYardPhysicalInspection;
    private validateRequestedWindow;
    private ensureInspection;
    private ensureChecklistItem;
    private ensureRequestItem;
    private ensureErrorCode;
}
