import { MetaService } from './meta.service';
import { CreateMetaDto } from './dto/create-meta.dto';
import { UpdateMetaDto } from './dto/update-meta.dto';
import { QueryMetaDto } from './dto/query-meta.dto';
export declare class MetaController {
    private readonly metaService;
    constructor(metaService: MetaService);
    create(createMetaDto: CreateMetaDto): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        description: string | null;
        entityType: string;
        entityId: string;
        userId: string | null;
        isPublic: boolean;
        key: string;
        value: string;
        valueType: string;
        isSystem: boolean;
        isDeleted: boolean;
    }>;
    bulkCreate(createMetaDtos: CreateMetaDto[]): Promise<any>;
    findAll(queryDto: QueryMetaDto): Promise<{
        data: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            entityType: string;
            entityId: string;
            userId: string | null;
            isPublic: boolean;
            key: string;
            value: string;
            valueType: string;
            isSystem: boolean;
            isDeleted: boolean;
        }[];
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    }>;
    findByEntity(entityType: string, entityId: string): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        description: string | null;
        entityType: string;
        entityId: string;
        userId: string | null;
        isPublic: boolean;
        key: string;
        value: string;
        valueType: string;
        isSystem: boolean;
        isDeleted: boolean;
    }[]>;
    findByEntityAndKey(entityType: string, entityId: string, key: string): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        description: string | null;
        entityType: string;
        entityId: string;
        userId: string | null;
        isPublic: boolean;
        key: string;
        value: string;
        valueType: string;
        isSystem: boolean;
        isDeleted: boolean;
    }>;
    findOne(id: string): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        description: string | null;
        entityType: string;
        entityId: string;
        userId: string | null;
        isPublic: boolean;
        key: string;
        value: string;
        valueType: string;
        isSystem: boolean;
        isDeleted: boolean;
    }>;
    update(id: string, updateMetaDto: UpdateMetaDto): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        description: string | null;
        entityType: string;
        entityId: string;
        userId: string | null;
        isPublic: boolean;
        key: string;
        value: string;
        valueType: string;
        isSystem: boolean;
        isDeleted: boolean;
    }>;
    remove(id: string): Promise<void>;
    deleteByEntity(entityType: string, entityId: string): Promise<void>;
    hardDelete(id: string): Promise<void>;
}
