import { Buyer } from '@prisma/client';
export declare class BuyerEntity implements Omit<Buyer, 'monthlyHousingCost' | 'monthlyIncome' | 'additionalIncome' | 'previousMonthlyIncome' | 'currentMonthlyDebts' | 'alimonyChildSupport' | 'businessAnnualRevenue'> {
    id: string;
    firstName: string;
    middleName: string | null;
    lastName: string;
    suffix: string | null;
    dateOfBirth: Date;
    genderId: string | null;
    ssn: string | null;
    itin: string | null;
    citizenship: string | null;
    email: string;
    phoneMain: string;
    phoneSecondary: string | null;
    phoneMobile: string | null;
    preferredLanguageId: string | null;
    currentAddress: string;
    currentCity: string;
    currentState: string;
    currentZipCode: string;
    currentCountry: string;
    yearsAtAddress: number | null;
    monthsAtAddress: number | null;
    housingStatus: string | null;
    monthlyHousingCost: number | null;
    previousAddress: string | null;
    previousCity: string | null;
    previousState: string | null;
    previousZipCode: string | null;
    previousCountry: string | null;
    yearsAtPreviousAddress: number | null;
    monthsAtPreviousAddress: number | null;
    idTypeId: string | null;
    idNumber: string | null;
    idStateId: string | null;
    idExpirationDate: Date | null;
    idIssueDate: Date | null;
    driversLicenseNumber: string | null;
    driversLicenseState: string | null;
    driversLicenseExpiration: Date | null;
    employmentStatusId: string | null;
    currentEmployer: string | null;
    employerPhone: string | null;
    occupationId: string | null;
    jobTitle: string | null;
    employerAddress: string | null;
    employerCity: string | null;
    employerState: string | null;
    employerZipCode: string | null;
    monthlyIncome: number | null;
    yearsEmployed: number | null;
    monthsEmployed: number | null;
    additionalIncome: number | null;
    additionalIncomeSource: string | null;
    previousEmployer: string | null;
    previousEmployerPhone: string | null;
    previousJobTitle: string | null;
    previousEmployerAddress: string | null;
    previousEmployerCity: string | null;
    previousEmployerState: string | null;
    previousEmployerZipCode: string | null;
    previousMonthlyIncome: number | null;
    previousYearsEmployed: number | null;
    previousMonthsEmployed: number | null;
    bankName: string | null;
    bankAccountType: string | null;
    bankRoutingNumber: string | null;
    bankAccountNumber: string | null;
    yearsWithBank: number | null;
    monthsWithBank: number | null;
    creditScore: number | null;
    bankruptcyHistory: boolean;
    bankruptcyDate: Date | null;
    bankruptcyType: string | null;
    bankruptcyDischargeDate: Date | null;
    repoHistory: boolean;
    repoDate: Date | null;
    foreclosureHistory: boolean;
    foreclosureDate: Date | null;
    currentMonthlyDebts: number | null;
    alimonyChildSupport: number | null;
    reference1Name: string | null;
    reference1Phone: string | null;
    reference1Relation: string | null;
    reference1Address: string | null;
    reference1YearsKnown: number | null;
    reference2Name: string | null;
    reference2Phone: string | null;
    reference2Relation: string | null;
    reference2Address: string | null;
    reference2YearsKnown: number | null;
    reference3Name: string | null;
    reference3Phone: string | null;
    reference3Relation: string | null;
    reference3Address: string | null;
    reference3YearsKnown: number | null;
    reference4Name: string | null;
    reference4Phone: string | null;
    reference4Relation: string | null;
    reference4Address: string | null;
    reference4YearsKnown: number | null;
    reference5Name: string | null;
    reference5Phone: string | null;
    reference5Relation: string | null;
    reference5Address: string | null;
    reference5YearsKnown: number | null;
    isBusinessBuyer: boolean;
    businessName: string | null;
    businessType: string | null;
    businessEIN: string | null;
    businessYearsInBusiness: number | null;
    businessAnnualRevenue: number | null;
    ofacCheckCompleted: boolean;
    ofacCheckDate: Date | null;
    ofacCheckResult: string | null;
    ofacNotes: string | null;
    identityVerified: boolean;
    identityVerifiedDate: Date | null;
    identityVerifiedBy: string | null;
    source: string | null;
    leadType: string | null;
    leadSource: string | null;
    inquiryType: string | null;
    contactMethod: string | null;
    contactTime: string | null;
    notes: string | null;
    createdAt: Date;
    updatedAt: Date;
    metaValue: any;
    tenantId: string | null;
    salesPersonId: string | null;
    bdcAgentId: string | null;
    stripeCustomerId: string | null;
    clerkUserId: string | null;
    fullName: string;
    constructor(partial: Partial<BuyerEntity> & Record<string, any>);
}
