"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.validateScopes = exports.hasScope = exports.ALL_API_SCOPES = exports.API_SCOPE_ACTIONS = exports.API_SCOPE_RESOURCES = exports.API_SCOPES_KEY = exports.RequireApiScopes = exports.PERMISSIONS_KEY = exports.RequirePermissions = exports.OWNER_ONLY = exports.ADMIN_ROLES = exports.ROLES_KEY = exports.RequireRoles = exports.CustomerAuth = exports.CurrentBuyer = exports.TenantOptional = exports.CurrentTenant = exports.CurrentUser = exports.IS_PUBLIC_KEY = exports.Public = exports.PORTAL_TENANT_ID = exports.CustomerGuard = exports.PermissionsGuard = exports.RolesGuard = exports.TENANT_ERROR_CODE = exports.TENANT_OPTIONAL_KEY = exports.TenantGuard = exports.ClerkJwtGuard = exports.ApiKeyGuard = exports.ClerkService = exports.AuthService = exports.AuthModule = void 0;
var auth_module_1 = require("./auth.module");
Object.defineProperty(exports, "AuthModule", { enumerable: true, get: function () { return auth_module_1.AuthModule; } });
var auth_service_1 = require("./auth.service");
Object.defineProperty(exports, "AuthService", { enumerable: true, get: function () { return auth_service_1.AuthService; } });
var clerk_service_1 = require("./clerk.service");
Object.defineProperty(exports, "ClerkService", { enumerable: true, get: function () { return clerk_service_1.ClerkService; } });
var api_key_guard_1 = require("./guards/api-key.guard");
Object.defineProperty(exports, "ApiKeyGuard", { enumerable: true, get: function () { return api_key_guard_1.ApiKeyGuard; } });
var clerk_jwt_guard_1 = require("./guards/clerk-jwt.guard");
Object.defineProperty(exports, "ClerkJwtGuard", { enumerable: true, get: function () { return clerk_jwt_guard_1.ClerkJwtGuard; } });
var tenant_guard_1 = require("./guards/tenant.guard");
Object.defineProperty(exports, "TenantGuard", { enumerable: true, get: function () { return tenant_guard_1.TenantGuard; } });
Object.defineProperty(exports, "TENANT_OPTIONAL_KEY", { enumerable: true, get: function () { return tenant_guard_1.TENANT_OPTIONAL_KEY; } });
Object.defineProperty(exports, "TENANT_ERROR_CODE", { enumerable: true, get: function () { return tenant_guard_1.TENANT_ERROR_CODE; } });
var roles_guard_1 = require("./guards/roles.guard");
Object.defineProperty(exports, "RolesGuard", { enumerable: true, get: function () { return roles_guard_1.RolesGuard; } });
var permissions_guard_1 = require("./guards/permissions.guard");
Object.defineProperty(exports, "PermissionsGuard", { enumerable: true, get: function () { return permissions_guard_1.PermissionsGuard; } });
var customer_guard_1 = require("./guards/customer.guard");
Object.defineProperty(exports, "CustomerGuard", { enumerable: true, get: function () { return customer_guard_1.CustomerGuard; } });
Object.defineProperty(exports, "PORTAL_TENANT_ID", { enumerable: true, get: function () { return customer_guard_1.PORTAL_TENANT_ID; } });
var public_decorator_1 = require("./decorators/public.decorator");
Object.defineProperty(exports, "Public", { enumerable: true, get: function () { return public_decorator_1.Public; } });
Object.defineProperty(exports, "IS_PUBLIC_KEY", { enumerable: true, get: function () { return public_decorator_1.IS_PUBLIC_KEY; } });
var current_user_decorator_1 = require("./decorators/current-user.decorator");
Object.defineProperty(exports, "CurrentUser", { enumerable: true, get: function () { return current_user_decorator_1.CurrentUser; } });
var current_tenant_decorator_1 = require("./decorators/current-tenant.decorator");
Object.defineProperty(exports, "CurrentTenant", { enumerable: true, get: function () { return current_tenant_decorator_1.CurrentTenant; } });
var tenant_optional_decorator_1 = require("./decorators/tenant-optional.decorator");
Object.defineProperty(exports, "TenantOptional", { enumerable: true, get: function () { return tenant_optional_decorator_1.TenantOptional; } });
var current_buyer_decorator_1 = require("./decorators/current-buyer.decorator");
Object.defineProperty(exports, "CurrentBuyer", { enumerable: true, get: function () { return current_buyer_decorator_1.CurrentBuyer; } });
var customer_auth_decorator_1 = require("./decorators/customer-auth.decorator");
Object.defineProperty(exports, "CustomerAuth", { enumerable: true, get: function () { return customer_auth_decorator_1.CustomerAuth; } });
var roles_decorator_1 = require("./decorators/roles.decorator");
Object.defineProperty(exports, "RequireRoles", { enumerable: true, get: function () { return roles_decorator_1.RequireRoles; } });
Object.defineProperty(exports, "ROLES_KEY", { enumerable: true, get: function () { return roles_decorator_1.ROLES_KEY; } });
Object.defineProperty(exports, "ADMIN_ROLES", { enumerable: true, get: function () { return roles_decorator_1.ADMIN_ROLES; } });
Object.defineProperty(exports, "OWNER_ONLY", { enumerable: true, get: function () { return roles_decorator_1.OWNER_ONLY; } });
var permissions_decorator_1 = require("./decorators/permissions.decorator");
Object.defineProperty(exports, "RequirePermissions", { enumerable: true, get: function () { return permissions_decorator_1.RequirePermissions; } });
Object.defineProperty(exports, "PERMISSIONS_KEY", { enumerable: true, get: function () { return permissions_decorator_1.PERMISSIONS_KEY; } });
var api_scopes_decorator_1 = require("./decorators/api-scopes.decorator");
Object.defineProperty(exports, "RequireApiScopes", { enumerable: true, get: function () { return api_scopes_decorator_1.RequireApiScopes; } });
Object.defineProperty(exports, "API_SCOPES_KEY", { enumerable: true, get: function () { return api_scopes_decorator_1.API_SCOPES_KEY; } });
var api_scopes_1 = require("./constants/api-scopes");
Object.defineProperty(exports, "API_SCOPE_RESOURCES", { enumerable: true, get: function () { return api_scopes_1.API_SCOPE_RESOURCES; } });
Object.defineProperty(exports, "API_SCOPE_ACTIONS", { enumerable: true, get: function () { return api_scopes_1.API_SCOPE_ACTIONS; } });
Object.defineProperty(exports, "ALL_API_SCOPES", { enumerable: true, get: function () { return api_scopes_1.ALL_API_SCOPES; } });
Object.defineProperty(exports, "hasScope", { enumerable: true, get: function () { return api_scopes_1.hasScope; } });
Object.defineProperty(exports, "validateScopes", { enumerable: true, get: function () { return api_scopes_1.validateScopes; } });
//# sourceMappingURL=index.js.map