import { PrismaService } from '@htownautos/prisma';
import { CreateTenantDto } from './dto/create-tenant.dto';
import { UpdateTenantDto } from './dto/update-tenant.dto';
import { QueryTenantDto } from './dto/query-tenant.dto';
import { AddUserToTenantDto, InviteUserToTenantDto, UpdateTenantUserDto, RegisterWithInvitationDto } from './dto/add-user-to-tenant.dto';
import { Prisma } from '@prisma/client';
import { ClerkService } from '@htownautos/auth';
import { EmailService } from '../email/email.service';
import { TwilioService } from '../twilio/twilio.service';
import { TenantEmailDomainService } from './tenant-email-domain.service';
import { NotificationsService } from '../notifications/notifications.service';
import { SearchType, PurchasePhoneNumberDto, UpdatePhoneNumberDto } from './dto/phone-number.dto';
import { FeeConfig } from './fee-config.default';
export declare const INVITATION_STATUS: {
    readonly PENDING: "pending";
    readonly ACTIVE: "active";
    readonly SUSPENDED: "suspended";
    readonly REMOVED: "removed";
};
export declare class TenantService {
    private prisma;
    private clerkService;
    private emailService;
    private twilioService;
    private tenantEmailDomainService;
    private notificationsService;
    private readonly logger;
    constructor(prisma: PrismaService, clerkService: ClerkService, emailService: EmailService, twilioService: TwilioService, tenantEmailDomainService: TenantEmailDomainService, notificationsService: NotificationsService);
    create(createTenantDto: CreateTenantDto, creatorUserId: string, ownerUsername: string): Promise<({
        users: ({
            user: {
                name: string | null;
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
            };
            role: {
                name: string;
                id: string;
                slug: string;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: Prisma.JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        })[];
    } & {
        name: string;
        id: string;
        slug: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        clerkOrgId: string | null;
        subdomain: string | null;
        businessName: string | null;
        taxId: string | null;
        phone: string | null;
        email: string | null;
        website: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        zipCode: string | null;
        country: string;
        settings: Prisma.JsonValue | null;
        feeConfig: Prisma.JsonValue | null;
        twilioMessagingServiceSid: string | null;
        logo: string | null;
        deletedAt: Date | null;
        postmarkDomainId: number | null;
        postmarkDkimVerified: boolean;
        postmarkReturnPathVerified: boolean;
        emailProvisionedAt: Date | null;
        cloudflareDnsRecordIds: Prisma.JsonValue | null;
        postmarkServerId: number | null;
        postmarkServerToken: string | null;
        postmarkWebhookId: number | null;
    }) | null>;
    findAll(query: QueryTenantDto): Promise<{
        data: {
            name: string;
            id: string;
            slug: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            clerkOrgId: string | null;
            subdomain: string | null;
            businessName: string | null;
            taxId: string | null;
            phone: string | null;
            email: string | null;
            website: string | null;
            address: string | null;
            city: string | null;
            state: string | null;
            zipCode: string | null;
            country: string;
            settings: Prisma.JsonValue | null;
            feeConfig: Prisma.JsonValue | null;
            twilioMessagingServiceSid: string | null;
            logo: string | null;
            deletedAt: Date | null;
            postmarkDomainId: number | null;
            postmarkDkimVerified: boolean;
            postmarkReturnPathVerified: boolean;
            emailProvisionedAt: Date | null;
            cloudflareDnsRecordIds: Prisma.JsonValue | null;
            postmarkServerId: number | null;
            postmarkServerToken: string | null;
            postmarkWebhookId: number | null;
        }[];
        total: number;
        page: number;
        limit: number;
        totalPages: number;
    }>;
    findOne(id: string): Promise<{
        name: string;
        id: string;
        slug: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        clerkOrgId: string | null;
        subdomain: string | null;
        businessName: string | null;
        taxId: string | null;
        phone: string | null;
        email: string | null;
        website: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        zipCode: string | null;
        country: string;
        settings: Prisma.JsonValue | null;
        feeConfig: Prisma.JsonValue | null;
        twilioMessagingServiceSid: string | null;
        logo: string | null;
        deletedAt: Date | null;
        postmarkDomainId: number | null;
        postmarkDkimVerified: boolean;
        postmarkReturnPathVerified: boolean;
        emailProvisionedAt: Date | null;
        cloudflareDnsRecordIds: Prisma.JsonValue | null;
        postmarkServerId: number | null;
        postmarkServerToken: string | null;
        postmarkWebhookId: number | null;
    }>;
    findByIdOrClerkOrgId(id: string): Promise<{
        name: string;
        id: string;
        slug: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        clerkOrgId: string | null;
        subdomain: string | null;
        businessName: string | null;
        taxId: string | null;
        phone: string | null;
        email: string | null;
        website: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        zipCode: string | null;
        country: string;
        settings: Prisma.JsonValue | null;
        feeConfig: Prisma.JsonValue | null;
        twilioMessagingServiceSid: string | null;
        logo: string | null;
        deletedAt: Date | null;
        postmarkDomainId: number | null;
        postmarkDkimVerified: boolean;
        postmarkReturnPathVerified: boolean;
        emailProvisionedAt: Date | null;
        cloudflareDnsRecordIds: Prisma.JsonValue | null;
        postmarkServerId: number | null;
        postmarkServerToken: string | null;
        postmarkWebhookId: number | null;
    }>;
    findBySlug(slug: string): Promise<{
        name: string;
        id: string;
        slug: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        clerkOrgId: string | null;
        subdomain: string | null;
        businessName: string | null;
        taxId: string | null;
        phone: string | null;
        email: string | null;
        website: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        zipCode: string | null;
        country: string;
        settings: Prisma.JsonValue | null;
        feeConfig: Prisma.JsonValue | null;
        twilioMessagingServiceSid: string | null;
        logo: string | null;
        deletedAt: Date | null;
        postmarkDomainId: number | null;
        postmarkDkimVerified: boolean;
        postmarkReturnPathVerified: boolean;
        emailProvisionedAt: Date | null;
        cloudflareDnsRecordIds: Prisma.JsonValue | null;
        postmarkServerId: number | null;
        postmarkServerToken: string | null;
        postmarkWebhookId: number | null;
    }>;
    findOneWithStats(id: string): Promise<{
        userCount: number;
        vehicleCount: number;
        dealCount: number;
        buyerCount: number;
        name: string;
        id: string;
        slug: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        clerkOrgId: string | null;
        subdomain: string | null;
        businessName: string | null;
        taxId: string | null;
        phone: string | null;
        email: string | null;
        website: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        zipCode: string | null;
        country: string;
        settings: Prisma.JsonValue | null;
        feeConfig: Prisma.JsonValue | null;
        twilioMessagingServiceSid: string | null;
        logo: string | null;
        deletedAt: Date | null;
        postmarkDomainId: number | null;
        postmarkDkimVerified: boolean;
        postmarkReturnPathVerified: boolean;
        emailProvisionedAt: Date | null;
        cloudflareDnsRecordIds: Prisma.JsonValue | null;
        postmarkServerId: number | null;
        postmarkServerToken: string | null;
        postmarkWebhookId: number | null;
    }>;
    update(id: string, updateTenantDto: UpdateTenantDto): Promise<{
        name: string;
        id: string;
        slug: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        clerkOrgId: string | null;
        subdomain: string | null;
        businessName: string | null;
        taxId: string | null;
        phone: string | null;
        email: string | null;
        website: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        zipCode: string | null;
        country: string;
        settings: Prisma.JsonValue | null;
        feeConfig: Prisma.JsonValue | null;
        twilioMessagingServiceSid: string | null;
        logo: string | null;
        deletedAt: Date | null;
        postmarkDomainId: number | null;
        postmarkDkimVerified: boolean;
        postmarkReturnPathVerified: boolean;
        emailProvisionedAt: Date | null;
        cloudflareDnsRecordIds: Prisma.JsonValue | null;
        postmarkServerId: number | null;
        postmarkServerToken: string | null;
        postmarkWebhookId: number | null;
    }>;
    updateSettings(id: string, settings: Record<string, any>): Promise<{
        name: string;
        id: string;
        slug: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        clerkOrgId: string | null;
        subdomain: string | null;
        businessName: string | null;
        taxId: string | null;
        phone: string | null;
        email: string | null;
        website: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        zipCode: string | null;
        country: string;
        settings: Prisma.JsonValue | null;
        feeConfig: Prisma.JsonValue | null;
        twilioMessagingServiceSid: string | null;
        logo: string | null;
        deletedAt: Date | null;
        postmarkDomainId: number | null;
        postmarkDkimVerified: boolean;
        postmarkReturnPathVerified: boolean;
        emailProvisionedAt: Date | null;
        cloudflareDnsRecordIds: Prisma.JsonValue | null;
        postmarkServerId: number | null;
        postmarkServerToken: string | null;
        postmarkWebhookId: number | null;
    }>;
    activate(id: string): Promise<{
        name: string;
        id: string;
        slug: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        clerkOrgId: string | null;
        subdomain: string | null;
        businessName: string | null;
        taxId: string | null;
        phone: string | null;
        email: string | null;
        website: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        zipCode: string | null;
        country: string;
        settings: Prisma.JsonValue | null;
        feeConfig: Prisma.JsonValue | null;
        twilioMessagingServiceSid: string | null;
        logo: string | null;
        deletedAt: Date | null;
        postmarkDomainId: number | null;
        postmarkDkimVerified: boolean;
        postmarkReturnPathVerified: boolean;
        emailProvisionedAt: Date | null;
        cloudflareDnsRecordIds: Prisma.JsonValue | null;
        postmarkServerId: number | null;
        postmarkServerToken: string | null;
        postmarkWebhookId: number | null;
    }>;
    deactivate(id: string): Promise<{
        name: string;
        id: string;
        slug: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        clerkOrgId: string | null;
        subdomain: string | null;
        businessName: string | null;
        taxId: string | null;
        phone: string | null;
        email: string | null;
        website: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        zipCode: string | null;
        country: string;
        settings: Prisma.JsonValue | null;
        feeConfig: Prisma.JsonValue | null;
        twilioMessagingServiceSid: string | null;
        logo: string | null;
        deletedAt: Date | null;
        postmarkDomainId: number | null;
        postmarkDkimVerified: boolean;
        postmarkReturnPathVerified: boolean;
        emailProvisionedAt: Date | null;
        cloudflareDnsRecordIds: Prisma.JsonValue | null;
        postmarkServerId: number | null;
        postmarkServerToken: string | null;
        postmarkWebhookId: number | null;
    }>;
    remove(id: string, requestingUserId: string): Promise<{
        message: string;
    }>;
    getUsers(id: string, roleSlugs?: string[]): Promise<({
        user: {
            name: string | null;
            id: string;
            isActive: boolean;
            email: string;
            firstName: string | null;
            lastName: string | null;
            avatar: string | null;
            lastLoginAt: Date | null;
        };
        role: {
            name: string;
            id: string;
            slug: string;
        };
    } & {
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        userId: string;
        status: string;
        username: string | null;
        tenantEmail: string | null;
        extension: string | null;
        permissions: Prisma.JsonValue | null;
        roleId: string;
        acceptedAt: Date | null;
        invitationCode: string | null;
        invitationSentAt: Date | null;
        invitedBy: string | null;
        removedAt: Date | null;
    })[]>;
    getPhoneNumbers(id: string): Promise<({
        assignedTo: {
            id: string;
            user: {
                name: string | null;
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
            };
        } | null;
    } & {
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        assignedToId: string | null;
        phoneNumber: string;
        twilioSid: string;
        friendlyName: string | null;
        canVoice: boolean;
        canSms: boolean;
        canMms: boolean;
        callFlowId: string | null;
        isPrimary: boolean;
    })[]>;
    checkSlugAvailability(slug: string): Promise<{
        available: boolean;
    }>;
    checkSubdomainAvailability(subdomain: string): Promise<{
        available: boolean;
    }>;
    checkUsernameAvailability(tenantId: string, username: string): Promise<{
        available: boolean;
    }>;
    getUserTenants(userId: string): Promise<{
        id: string;
        name: string;
        slug: string;
        subdomain: string | null;
        businessName: string | null;
        logo: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        isActive: boolean;
        role: {
            name: string;
            id: string;
            slug: string;
        };
        isOwner: boolean;
    }[]>;
    verifyUserTenantAccess(userId: string, tenantId: string): Promise<boolean>;
    isOwner(tenantId: string, userId: string): Promise<boolean>;
    verifyOwnership(tenantId: string, requestingUserId: string): Promise<void>;
    addUserToTenant(tenantId: string, addUserDto: AddUserToTenantDto, requestingUserId: string): Promise<{
        user: {
            name: string | null;
            id: string;
            email: string;
            firstName: string | null;
            lastName: string | null;
            avatar: string | null;
        };
        role: {
            name: string;
            id: string;
            slug: string;
        };
    } & {
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        userId: string;
        status: string;
        username: string | null;
        tenantEmail: string | null;
        extension: string | null;
        permissions: Prisma.JsonValue | null;
        roleId: string;
        acceptedAt: Date | null;
        invitationCode: string | null;
        invitationSentAt: Date | null;
        invitedBy: string | null;
        removedAt: Date | null;
    }>;
    updateTenantUser(tenantId: string, userId: string, updateDto: UpdateTenantUserDto, requestingUserId: string): Promise<{
        user: {
            name: string | null;
            id: string;
            email: string;
            firstName: string | null;
            lastName: string | null;
            avatar: string | null;
        };
        role: {
            name: string;
            id: string;
            slug: string;
        };
    } & {
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        userId: string;
        status: string;
        username: string | null;
        tenantEmail: string | null;
        extension: string | null;
        permissions: Prisma.JsonValue | null;
        roleId: string;
        acceptedAt: Date | null;
        invitationCode: string | null;
        invitationSentAt: Date | null;
        invitedBy: string | null;
        removedAt: Date | null;
    }>;
    removeUserFromTenant(tenantId: string, userId: string, requestingUserId: string): Promise<{
        message: string;
    }>;
    transferOwnership(tenantId: string, newOwnerId: string, requestingUserId: string): Promise<{
        message: string;
        previousOwnerId: string;
        newOwnerId: string;
    }>;
    getAvailableRoles(tenantId: string): Promise<{
        name: string;
        id: string;
        slug: string;
        description: string | null;
        isSystem: boolean;
    }[]>;
    private generateInvitationCode;
    inviteUserToTenant(tenantId: string, inviteDto: InviteUserToTenantDto, requestingUserId: string): Promise<{
        message: string;
        invitation: {
            id: any;
            email: any;
            status: any;
            invitationSentAt: any;
            role: any;
        };
        user: {
            id: any;
            email: any;
        };
        _debug: {
            invitationCode: string;
            invitationUrl: string;
        };
    }>;
    getInvitationByCode(code: string): Promise<{
        type: string;
        id: string;
        email: string;
        tenant: {
            name: string;
            id: string;
            slug: string;
        };
        role: {
            name: string;
            id: string;
            slug: string;
        };
        userExists: boolean;
        requiresRegistration: boolean;
    }>;
    acceptInvitation(code: string, loggedInUser: {
        id: string;
        email: string;
        clerkUserId: string;
    }): Promise<{
        message: string;
        tenantUser: {
            id: any;
            status: any;
            acceptedAt: any;
            tenant: any;
            user: any;
            role: any;
        };
    }>;
    private mapRoleToClerkRole;
    getMyInvitations(userId: string, email: string): Promise<{
        id: string;
        tenantId: string;
        tenantName: string;
        roleName: string;
        roleSlug: string;
        invitedBy: {
            id: string;
            name: string;
        } | null;
        invitedAt: Date | null;
        invitationCode: string | null;
    }[]>;
    acceptMyInvitation(tenantUserId: string, loggedInUser: {
        id: string;
        email: string;
        clerkUserId: string;
    }): Promise<{
        message: string;
        tenantUser: {
            id: any;
            status: any;
            acceptedAt: any;
            tenant: any;
            user: any;
            role: any;
        };
    }>;
    declineMyInvitation(tenantUserId: string, loggedInUser: {
        id: string;
        email: string;
    }): Promise<{
        ok: boolean;
    }>;
    registerAndAcceptInvitation(registerDto: RegisterWithInvitationDto): Promise<{
        message: string;
        user: {
            id: any;
            email: any;
            firstName: any;
            lastName: any;
        };
        tenantUser: {
            id: any;
            status: any;
            acceptedAt: any;
            tenant: any;
            role: any;
        };
    }>;
    resendInvitation(tenantId: string, userId: string, requestingUserId: string): Promise<{
        message: string;
        invitationSentAt: Date | null;
        _debug: {
            invitationCode: string;
            invitationUrl: string;
        };
    }>;
    revokeInvitation(tenantId: string, userId: string, requestingUserId: string): Promise<{
        message: string;
    }>;
    getPendingInvitations(tenantId: string, requestingUserId: string): Promise<({
        user: {
            name: string | null;
            id: string;
            email: string;
            firstName: string | null;
            lastName: string | null;
        };
        role: {
            name: string;
            id: string;
            slug: string;
        };
    } & {
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        userId: string;
        status: string;
        username: string | null;
        tenantEmail: string | null;
        extension: string | null;
        permissions: Prisma.JsonValue | null;
        roleId: string;
        acceptedAt: Date | null;
        invitationCode: string | null;
        invitationSentAt: Date | null;
        invitedBy: string | null;
        removedAt: Date | null;
    })[]>;
    searchAvailablePhoneNumbers(type: SearchType, value?: string): Promise<import("../twilio/twilio.service").AvailablePhoneNumber[]>;
    purchasePhoneNumber(tenantId: string, dto: PurchasePhoneNumberDto): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        assignedToId: string | null;
        phoneNumber: string;
        twilioSid: string;
        friendlyName: string | null;
        canVoice: boolean;
        canSms: boolean;
        canMms: boolean;
        callFlowId: string | null;
        isPrimary: boolean;
    }>;
    updatePhoneNumber(tenantId: string, phoneNumberId: string, dto: UpdatePhoneNumberDto): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        assignedToId: string | null;
        phoneNumber: string;
        twilioSid: string;
        friendlyName: string | null;
        canVoice: boolean;
        canSms: boolean;
        canMms: boolean;
        callFlowId: string | null;
        isPrimary: boolean;
    }>;
    deletePhoneNumber(tenantId: string, phoneNumberId: string): Promise<{
        message: string;
    }>;
    getFeeConfig(tenantId: string, requestingUserId: string): Promise<FeeConfig>;
    updateFeeConfig(tenantId: string, requestingUserId: string, config: FeeConfig): Promise<FeeConfig>;
}
