import { InspectionShareLinksService } from './inspection-share-links.service';
import { CreateShareLinkDto } from './dto/create-share-link.dto';
export declare class InspectionShareLinksController {
    private readonly service;
    constructor(service: InspectionShareLinksService);
    create(tenantId: string, userId: string, id: string, dto: CreateShareLinkDto): Promise<{
        shortUrlCode: string | null;
        shortUrl: string | null;
        id: string;
        createdAt: Date;
        inspectionId: string;
        createdBy: string | null;
        expiresAt: Date | null;
        token: string;
        revoked: boolean;
        lastAccessedAt: Date | null;
    }>;
    list(tenantId: string, id: string): Promise<{
        shortUrl: string | null;
        id: string;
        createdAt: Date;
        inspectionId: string;
        createdBy: string | null;
        expiresAt: Date | null;
        token: string;
        revoked: boolean;
        lastAccessedAt: Date | null;
        shortUrlCode: string | null;
    }[]>;
    revoke(tenantId: string, linkId: string): Promise<{
        id: string;
        createdAt: Date;
        inspectionId: string;
        createdBy: string | null;
        expiresAt: Date | null;
        token: string;
        revoked: boolean;
        lastAccessedAt: Date | null;
        shortUrlCode: string | null;
    }>;
    remove(tenantId: string, linkId: string): Promise<{
        deleted: boolean;
    }>;
    resolvePublic(vin: string, token: string): Promise<{
        id: string;
        vin: string;
        lotNumber: string | null;
        yardName: string | null;
        yardNumber: string | null;
        status: import("@prisma/client").$Enums.VehicleInspectionStatus;
        requestedAt: Date;
        inspectedAt: Date | null;
        completedAt: Date | null;
        overallRating: number | null;
        notes: string | null;
        media: {
            path: string | null;
            url: string;
            id: string;
            title: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            description: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            vehicleId: string | null;
            partId: string | null;
            duration: number | null;
            filename: string;
            mimeType: string;
            size: number;
            width: number | null;
            height: number | null;
            alt: string | null;
            mediaType: string;
            category: string | null;
            storageProvider: string | null;
            storageBucket: string | null;
            storageKey: string | null;
            isPublic: boolean;
            inspectionId: string | null;
            inspectionChecklistItemId: string | null;
            inspectionRequestItemId: string | null;
            inspectionErrorCodeId: string | null;
            carfaxReportId: string | null;
        }[];
        checklist: ({
            media: {
                path: string | null;
                url: string;
                id: string;
                title: string | null;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string | null;
                description: string | null;
                metaValue: import("@prisma/client/runtime/client").JsonValue | null;
                buyerId: string | null;
                vehicleId: string | null;
                partId: string | null;
                duration: number | null;
                filename: string;
                mimeType: string;
                size: number;
                width: number | null;
                height: number | null;
                alt: string | null;
                mediaType: string;
                category: string | null;
                storageProvider: string | null;
                storageBucket: string | null;
                storageKey: string | null;
                isPublic: boolean;
                inspectionId: string | null;
                inspectionChecklistItemId: string | null;
                inspectionRequestItemId: string | null;
                inspectionErrorCodeId: string | null;
                carfaxReportId: string | null;
            }[];
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            part: string;
            notes: string | null;
            category: import("@prisma/client").$Enums.ChecklistCategory;
            inspectionId: string;
            sortOrder: number;
            quality: number | null;
            voiceNoteTranscription: string | null;
        })[];
        requestItems: ({
            media: {
                path: string | null;
                url: string;
                id: string;
                title: string | null;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string | null;
                description: string | null;
                metaValue: import("@prisma/client/runtime/client").JsonValue | null;
                buyerId: string | null;
                vehicleId: string | null;
                partId: string | null;
                duration: number | null;
                filename: string;
                mimeType: string;
                size: number;
                width: number | null;
                height: number | null;
                alt: string | null;
                mediaType: string;
                category: string | null;
                storageProvider: string | null;
                storageBucket: string | null;
                storageKey: string | null;
                isPublic: boolean;
                inspectionId: string | null;
                inspectionChecklistItemId: string | null;
                inspectionRequestItemId: string | null;
                inspectionErrorCodeId: string | null;
                carfaxReportId: string | null;
            }[];
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            note: string;
            inspectionId: string;
            sortOrder: number;
        })[];
        errorCodes: any;
        carfax: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            vin: string | null;
            aiSummary: string | null;
            auctionListingId: bigint;
            s3Key: string;
            analysis: string | null;
            date: Date | null;
        }[];
        analysis: import("../auction-analysis/auction-analysis.service").InspectionAuctionAnalysis;
        vehicle: {
            images: string[];
            year: number | null;
            make: string | null;
            model: string | null;
            trim: string | null;
            color: string | null;
            bodyType: string | null;
            engine: string | null;
            transmission: string | null;
            drivetrain: string | null;
            fuelType: string | null;
            cylinders: string | null;
            odometer: string | null;
            primaryDamage: string | null;
            secondaryDamage: string | null;
            hasKeys: string | null;
            runsDrives: string | null;
            titleType: string | null;
            titleState: string | null;
            highBid: string | null;
            buyItNow: string | null;
            estValue: string | null;
            repairCost: string | null;
            saleStatus: string | null;
            saleDate: number | null;
            saleTime: string | null;
            dayOfWeek: string | null;
            locationCity: string | null;
            locationState: string | null;
            locationZip: string | null;
            yardName: string | null;
        } | null;
        shareLink: {
            expiresAt: Date | null;
        };
    }>;
}
