import { OnModuleInit, OnModuleDestroy } from '@nestjs/common';
export declare class PrismaService implements OnModuleInit, OnModuleDestroy {
    private prisma;
    private pool;
    constructor();
    get vehicleYear(): import("@prisma/client").Prisma.VehicleYearDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get vehicleMake(): import("@prisma/client").Prisma.VehicleMakeDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get vehicleModel(): import("@prisma/client").Prisma.VehicleModelDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get vehicleTrim(): import("@prisma/client").Prisma.VehicleTrimDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get vehicle(): import("@prisma/client").Prisma.VehicleDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get vehicleEngine(): import("@prisma/client").Prisma.VehicleEngineDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get vehicleStatus(): import("@prisma/client").Prisma.VehicleStatusDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get mileageUnit(): import("@prisma/client").Prisma.MileageUnitDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get meta(): import("@prisma/client").Prisma.MetaDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get user(): import("@prisma/client").Prisma.UserDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get tenant(): import("@prisma/client").Prisma.TenantDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get tenantUser(): import("@prisma/client").Prisma.TenantUserDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get tenantInvitation(): import("@prisma/client").Prisma.TenantInvitationDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get role(): import("@prisma/client").Prisma.RoleDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get permission(): import("@prisma/client").Prisma.PermissionDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get rolePermission(): import("@prisma/client").Prisma.RolePermissionDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get auditLog(): import("@prisma/client").Prisma.AuditLogDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get dealStatus(): import("@prisma/client").Prisma.DealStatusDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get financeType(): import("@prisma/client").Prisma.FinanceTypeDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get deal(): import("@prisma/client").Prisma.DealDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get buyer(): import("@prisma/client").Prisma.BuyerDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get extraExpense(): import("@prisma/client").Prisma.ExtraExpenseDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get media(): import("@prisma/client").Prisma.MediaDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get title(): import("@prisma/client").Prisma.TitleDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get part(): import("@prisma/client").Prisma.PartDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get partCondition(): import("@prisma/client").Prisma.PartConditionDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get partStatus(): import("@prisma/client").Prisma.PartStatusDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get partCategory(): import("@prisma/client").Prisma.PartCategoryDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get vehiclePart(): import("@prisma/client").Prisma.VehiclePartDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get uploadSession(): import("@prisma/client").Prisma.UploadSessionDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get auctionListing(): import("@prisma/client").Prisma.AuctionListingDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get auctionTitleTypeMapping(): import("@prisma/client").Prisma.AuctionTitleTypeMappingDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get auctionFavorite(): import("@prisma/client").Prisma.AuctionFavoriteDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get buyerFavorite(): import("@prisma/client").Prisma.BuyerFavoriteDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get task(): import("@prisma/client").Prisma.TaskDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get note(): import("@prisma/client").Prisma.NoteDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get phoneCall(): import("@prisma/client").Prisma.PhoneCallDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get smsMessage(): import("@prisma/client").Prisma.SmsMessageDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get emailMessage(): import("@prisma/client").Prisma.EmailMessageDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get unmatchedInboundEmail(): import("@prisma/client").Prisma.UnmatchedInboundEmailDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get twilioPhoneNumber(): import("@prisma/client").Prisma.TwilioPhoneNumberDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get callFlow(): import("@prisma/client").Prisma.CallFlowDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get ttsCache(): import("@prisma/client").Prisma.TtsCacheDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get damageAi(): import("@prisma/client").Prisma.DamageAiDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get auctionVehicleAnalysis(): import("@prisma/client").Prisma.AuctionVehicleAnalysisDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get auctionPartsPrice(): import("@prisma/client").Prisma.AuctionPartsPriceDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get similarAuctionCar(): import("@prisma/client").Prisma.SimilarAuctionCarDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get vehicleMarketPart(): import("@prisma/client").Prisma.VehicleMarketPartDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get carfaxReport(): import("@prisma/client").Prisma.CarfaxReportDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get maxBidRecommendation(): import("@prisma/client").Prisma.MaxBidRecommendationDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get auctionAnalysisSnapshot(): import("@prisma/client").Prisma.AuctionAnalysisSnapshotDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get shortUrl(): import("@prisma/client").Prisma.ShortUrlDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get proxy(): import("@prisma/client").Prisma.ProxyDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get auctionListingGroup(): import("@prisma/client").Prisma.AuctionListingGroupDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get auctionListingGroupItem(): import("@prisma/client").Prisma.AuctionListingGroupItemDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get auctionListingReview(): import("@prisma/client").Prisma.AuctionListingReviewDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get buyerAuctionBid(): import("@prisma/client").Prisma.BuyerAuctionBidDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get buyerVehiclePreference(): import("@prisma/client").Prisma.BuyerVehiclePreferenceDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get buyerMatchExclusion(): import("@prisma/client").Prisma.BuyerMatchExclusionDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get syncRun(): import("@prisma/client").Prisma.SyncRunDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get rebuildItem(): import("@prisma/client").Prisma.RebuildItemDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get vehicleInspection(): import("@prisma/client").Prisma.VehicleInspectionDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get yard(): import("@prisma/client").Prisma.YardDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get inspectionShareLink(): import("@prisma/client").Prisma.InspectionShareLinkDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get buyerFavoritesShareLink(): import("@prisma/client").Prisma.BuyerFavoritesShareLinkDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get inspectionChecklistItem(): import("@prisma/client").Prisma.InspectionChecklistItemDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get inspectionRequestItem(): import("@prisma/client").Prisma.InspectionRequestItemDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get inspectionErrorCode(): import("@prisma/client").Prisma.InspectionErrorCodeDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get inventoryAsset(): import("@prisma/client").Prisma.InventoryAssetDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get investment(): import("@prisma/client").Prisma.InvestmentDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get socialAccount(): import("@prisma/client").Prisma.SocialAccountDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get socialGroup(): import("@prisma/client").Prisma.SocialGroupDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get socialGroupAccount(): import("@prisma/client").Prisma.SocialGroupAccountDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get partOrder(): import("@prisma/client").Prisma.PartOrderDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get partOrderItem(): import("@prisma/client").Prisma.PartOrderItemDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get partShipment(): import("@prisma/client").Prisma.PartShipmentDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get parcelTemplate(): import("@prisma/client").Prisma.ParcelTemplateDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get apiKey(): import("@prisma/client").Prisma.ApiKeyDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get customerLedgerEntry(): import("@prisma/client").Prisma.CustomerLedgerEntryDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get portalOrder(): import("@prisma/client").Prisma.PortalOrderDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get depositReleaseRequest(): import("@prisma/client").Prisma.DepositReleaseRequestDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get notification(): import("@prisma/client").Prisma.NotificationDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get contactMessage(): import("@prisma/client").Prisma.ContactMessageDelegate<import("@prisma/client/runtime/client").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    get $transaction(): any;
    get $queryRaw(): any;
    get $queryRawUnsafe(): any;
    getModel(modelName: string): any;
    onModuleInit(): Promise<void>;
    onModuleDestroy(): Promise<void>;
}
