import { CopartService } from './copart.service';
import { QueryCopartDto } from './dto/query-copart.dto';
export declare class CopartController {
    private readonly copartService;
    constructor(copartService: CopartService);
    findAll(query: QueryCopartDto): Promise<{
        data: {
            lotNumber: string;
            inspectable: boolean;
            trim: string | null;
            createdAt: Date;
            updatedAt: Date;
            vehicleType: string | null;
            fuelType: string | null;
            vin: string | null;
            engine: string | null;
            cylinders: string | null;
            odometerBrand: string | null;
            yardName: string | null;
            yardNumber: number | null;
            yardId: string | null;
            make: string | null;
            damageDescription: string | null;
            year: number | null;
            lastSeenAt: Date | null;
            auctionName: string | null;
            copartId: number | null;
            saleDate: number | null;
            dayOfWeek: string | null;
            saleTime: string | null;
            timeZone: string | null;
            itemNumber: number | null;
            modelGroup: string | null;
            modelDetail: string | null;
            bodyStyle: string | null;
            color: string | null;
            secondaryDamage: string | null;
            saleTitleState: string | null;
            saleTitleType: string | null;
            hasKeys: string | null;
            lotCondCode: string | null;
            odometer: import("@prisma/client-runtime-utils").Decimal | null;
            estRetailValue: import("@prisma/client-runtime-utils").Decimal | null;
            repairCost: import("@prisma/client-runtime-utils").Decimal | null;
            drive: string | null;
            transmission: string | null;
            runsDrives: string | null;
            saleStatus: string | null;
            highBid: import("@prisma/client-runtime-utils").Decimal | null;
            specialNote: string | null;
            locationCity: string | null;
            locationState: string | null;
            locationZip: string | null;
            locationCountry: string | null;
            currencyCode: string | null;
            images: string | null;
            galleryCache: string | null;
            galleryCachedAt: Date | null;
            createDateTime: string | null;
            gridRow: string | null;
            makeOfferEligible: string | null;
            buyItNowPrice: import("@prisma/client-runtime-utils").Decimal | null;
            lastUpdatedTime: Date | null;
            rentals: string | null;
            wholesale: string | null;
            sellerName: string | null;
            offsiteAddress1: string | null;
            offsiteState: string | null;
            offsiteCity: string | null;
            offsiteZip: string | null;
            saleLight: string | null;
            autoGrade: string | null;
            announcements: string | null;
            sellerCategory: string | null;
            engineSizeL: import("@prisma/client-runtime-utils").Decimal | null;
            locationLat: number | null;
            locationLng: number | null;
            isStale: boolean;
            discarded: boolean;
            discardReason: string | null;
            discardedAt: Date | null;
            discardedById: string | null;
        }[];
        meta: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNextPage: boolean;
            hasPreviousPage: boolean;
        };
    }>;
    getFilterOptions(): Promise<{
        makes: any;
        damageTypes: any;
        saleStatuses: any;
        states: any;
        years: any;
        titleTypes: any;
    }>;
    getStats(): Promise<{
        total: number;
        byDamage: (import("@prisma/client").Prisma.PickEnumerable<import("@prisma/client").Prisma.AuctionListingGroupByOutputType, "damageDescription"[]> & {
            _count: number;
        })[];
        byState: (import("@prisma/client").Prisma.PickEnumerable<import("@prisma/client").Prisma.AuctionListingGroupByOutputType, "locationState"[]> & {
            _count: number;
        })[];
    }>;
    findOne(id: string): Promise<{
        lotNumber: string;
        inspectable: boolean;
        trim: string | null;
        createdAt: Date;
        updatedAt: Date;
        vehicleType: string | null;
        fuelType: string | null;
        vin: string | null;
        engine: string | null;
        cylinders: string | null;
        odometerBrand: string | null;
        yardName: string | null;
        yardNumber: number | null;
        yardId: string | null;
        make: string | null;
        damageDescription: string | null;
        year: number | null;
        lastSeenAt: Date | null;
        auctionName: string | null;
        copartId: number | null;
        saleDate: number | null;
        dayOfWeek: string | null;
        saleTime: string | null;
        timeZone: string | null;
        itemNumber: number | null;
        modelGroup: string | null;
        modelDetail: string | null;
        bodyStyle: string | null;
        color: string | null;
        secondaryDamage: string | null;
        saleTitleState: string | null;
        saleTitleType: string | null;
        hasKeys: string | null;
        lotCondCode: string | null;
        odometer: import("@prisma/client-runtime-utils").Decimal | null;
        estRetailValue: import("@prisma/client-runtime-utils").Decimal | null;
        repairCost: import("@prisma/client-runtime-utils").Decimal | null;
        drive: string | null;
        transmission: string | null;
        runsDrives: string | null;
        saleStatus: string | null;
        highBid: import("@prisma/client-runtime-utils").Decimal | null;
        specialNote: string | null;
        locationCity: string | null;
        locationState: string | null;
        locationZip: string | null;
        locationCountry: string | null;
        currencyCode: string | null;
        images: string | null;
        galleryCache: string | null;
        galleryCachedAt: Date | null;
        createDateTime: string | null;
        gridRow: string | null;
        makeOfferEligible: string | null;
        buyItNowPrice: import("@prisma/client-runtime-utils").Decimal | null;
        lastUpdatedTime: Date | null;
        rentals: string | null;
        wholesale: string | null;
        sellerName: string | null;
        offsiteAddress1: string | null;
        offsiteState: string | null;
        offsiteCity: string | null;
        offsiteZip: string | null;
        saleLight: string | null;
        autoGrade: string | null;
        announcements: string | null;
        sellerCategory: string | null;
        engineSizeL: import("@prisma/client-runtime-utils").Decimal | null;
        locationLat: number | null;
        locationLng: number | null;
        isStale: boolean;
        discarded: boolean;
        discardReason: string | null;
        discardedAt: Date | null;
        discardedById: string | null;
    }>;
    findByLotNumber(lotNumber: string): Promise<{
        lotNumber: string;
        inspectable: boolean;
        trim: string | null;
        createdAt: Date;
        updatedAt: Date;
        vehicleType: string | null;
        fuelType: string | null;
        vin: string | null;
        engine: string | null;
        cylinders: string | null;
        odometerBrand: string | null;
        yardName: string | null;
        yardNumber: number | null;
        yardId: string | null;
        make: string | null;
        damageDescription: string | null;
        year: number | null;
        lastSeenAt: Date | null;
        auctionName: string | null;
        copartId: number | null;
        saleDate: number | null;
        dayOfWeek: string | null;
        saleTime: string | null;
        timeZone: string | null;
        itemNumber: number | null;
        modelGroup: string | null;
        modelDetail: string | null;
        bodyStyle: string | null;
        color: string | null;
        secondaryDamage: string | null;
        saleTitleState: string | null;
        saleTitleType: string | null;
        hasKeys: string | null;
        lotCondCode: string | null;
        odometer: import("@prisma/client-runtime-utils").Decimal | null;
        estRetailValue: import("@prisma/client-runtime-utils").Decimal | null;
        repairCost: import("@prisma/client-runtime-utils").Decimal | null;
        drive: string | null;
        transmission: string | null;
        runsDrives: string | null;
        saleStatus: string | null;
        highBid: import("@prisma/client-runtime-utils").Decimal | null;
        specialNote: string | null;
        locationCity: string | null;
        locationState: string | null;
        locationZip: string | null;
        locationCountry: string | null;
        currencyCode: string | null;
        images: string | null;
        galleryCache: string | null;
        galleryCachedAt: Date | null;
        createDateTime: string | null;
        gridRow: string | null;
        makeOfferEligible: string | null;
        buyItNowPrice: import("@prisma/client-runtime-utils").Decimal | null;
        lastUpdatedTime: Date | null;
        rentals: string | null;
        wholesale: string | null;
        sellerName: string | null;
        offsiteAddress1: string | null;
        offsiteState: string | null;
        offsiteCity: string | null;
        offsiteZip: string | null;
        saleLight: string | null;
        autoGrade: string | null;
        announcements: string | null;
        sellerCategory: string | null;
        engineSizeL: import("@prisma/client-runtime-utils").Decimal | null;
        locationLat: number | null;
        locationLng: number | null;
        isStale: boolean;
        discarded: boolean;
        discardReason: string | null;
        discardedAt: Date | null;
        discardedById: string | null;
    }>;
}
