import { PrismaService } from '@htownautos/prisma';
import { QueryCopartDto } from './dto/query-copart.dto';
import { Prisma } from '@prisma/client';
import { TitleMappingService } from '../title-mapping/title-mapping.service';
export interface Facet {
    value: string;
    label: string;
    count: number;
}
export interface FacetNum {
    value: number;
    label: string;
    count: number;
}
export interface PortalFiltersResult {
    years: FacetNum[];
    makes: Facet[];
    models: Facet[];
    trims: Facet[];
    damageTypes: Facet[];
    saleStatuses: Facet[];
    titleTypes: Facet[];
    titleCategories: Facet[];
    sources: Facet[];
    colors: Facet[];
    cylinders: Facet[];
    drivetrains: Facet[];
    bodyStyles: Facet[];
    fuelTypes: Facet[];
    transmissions: Facet[];
    states: Facet[];
    keys: Facet[];
}
export declare class CopartService {
    private prisma;
    private titleMapping;
    constructor(prisma: PrismaService, titleMapping: TitleMappingService);
    findAll(query: QueryCopartDto): Promise<{
        data: {
            lotNumber: string;
            inspectable: boolean;
            trim: string | null;
            createdAt: Date;
            updatedAt: Date;
            vehicleType: string | null;
            fuelType: string | null;
            vin: string | null;
            engine: string | null;
            cylinders: string | null;
            odometerBrand: string | null;
            yardName: string | null;
            yardNumber: number | null;
            yardId: string | null;
            make: string | null;
            damageDescription: string | null;
            year: number | null;
            lastSeenAt: Date | null;
            auctionName: string | null;
            copartId: number | null;
            saleDate: number | null;
            dayOfWeek: string | null;
            saleTime: string | null;
            timeZone: string | null;
            itemNumber: number | null;
            modelGroup: string | null;
            modelDetail: string | null;
            bodyStyle: string | null;
            color: string | null;
            secondaryDamage: string | null;
            saleTitleState: string | null;
            saleTitleType: string | null;
            hasKeys: string | null;
            lotCondCode: string | null;
            odometer: Prisma.Decimal | null;
            estRetailValue: Prisma.Decimal | null;
            repairCost: Prisma.Decimal | null;
            drive: string | null;
            transmission: string | null;
            runsDrives: string | null;
            saleStatus: string | null;
            highBid: Prisma.Decimal | null;
            specialNote: string | null;
            locationCity: string | null;
            locationState: string | null;
            locationZip: string | null;
            locationCountry: string | null;
            currencyCode: string | null;
            images: string | null;
            galleryCache: string | null;
            galleryCachedAt: Date | null;
            createDateTime: string | null;
            gridRow: string | null;
            makeOfferEligible: string | null;
            buyItNowPrice: Prisma.Decimal | null;
            lastUpdatedTime: Date | null;
            rentals: string | null;
            wholesale: string | null;
            sellerName: string | null;
            offsiteAddress1: string | null;
            offsiteState: string | null;
            offsiteCity: string | null;
            offsiteZip: string | null;
            saleLight: string | null;
            autoGrade: string | null;
            announcements: string | null;
            sellerCategory: string | null;
            engineSizeL: Prisma.Decimal | null;
            locationLat: number | null;
            locationLng: number | null;
            isStale: boolean;
            discarded: boolean;
            discardReason: string | null;
            discardedAt: Date | null;
            discardedById: string | null;
        }[];
        meta: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNextPage: boolean;
            hasPreviousPage: boolean;
        };
    }>;
    findOne(id: string): Promise<{
        lotNumber: string;
        inspectable: boolean;
        trim: string | null;
        createdAt: Date;
        updatedAt: Date;
        vehicleType: string | null;
        fuelType: string | null;
        vin: string | null;
        engine: string | null;
        cylinders: string | null;
        odometerBrand: string | null;
        yardName: string | null;
        yardNumber: number | null;
        yardId: string | null;
        make: string | null;
        damageDescription: string | null;
        year: number | null;
        lastSeenAt: Date | null;
        auctionName: string | null;
        copartId: number | null;
        saleDate: number | null;
        dayOfWeek: string | null;
        saleTime: string | null;
        timeZone: string | null;
        itemNumber: number | null;
        modelGroup: string | null;
        modelDetail: string | null;
        bodyStyle: string | null;
        color: string | null;
        secondaryDamage: string | null;
        saleTitleState: string | null;
        saleTitleType: string | null;
        hasKeys: string | null;
        lotCondCode: string | null;
        odometer: Prisma.Decimal | null;
        estRetailValue: Prisma.Decimal | null;
        repairCost: Prisma.Decimal | null;
        drive: string | null;
        transmission: string | null;
        runsDrives: string | null;
        saleStatus: string | null;
        highBid: Prisma.Decimal | null;
        specialNote: string | null;
        locationCity: string | null;
        locationState: string | null;
        locationZip: string | null;
        locationCountry: string | null;
        currencyCode: string | null;
        images: string | null;
        galleryCache: string | null;
        galleryCachedAt: Date | null;
        createDateTime: string | null;
        gridRow: string | null;
        makeOfferEligible: string | null;
        buyItNowPrice: Prisma.Decimal | null;
        lastUpdatedTime: Date | null;
        rentals: string | null;
        wholesale: string | null;
        sellerName: string | null;
        offsiteAddress1: string | null;
        offsiteState: string | null;
        offsiteCity: string | null;
        offsiteZip: string | null;
        saleLight: string | null;
        autoGrade: string | null;
        announcements: string | null;
        sellerCategory: string | null;
        engineSizeL: Prisma.Decimal | null;
        locationLat: number | null;
        locationLng: number | null;
        isStale: boolean;
        discarded: boolean;
        discardReason: string | null;
        discardedAt: Date | null;
        discardedById: string | null;
    } | null>;
    findByLotNumber(lotNumber: string): Promise<{
        lotNumber: string;
        inspectable: boolean;
        trim: string | null;
        createdAt: Date;
        updatedAt: Date;
        vehicleType: string | null;
        fuelType: string | null;
        vin: string | null;
        engine: string | null;
        cylinders: string | null;
        odometerBrand: string | null;
        yardName: string | null;
        yardNumber: number | null;
        yardId: string | null;
        make: string | null;
        damageDescription: string | null;
        year: number | null;
        lastSeenAt: Date | null;
        auctionName: string | null;
        copartId: number | null;
        saleDate: number | null;
        dayOfWeek: string | null;
        saleTime: string | null;
        timeZone: string | null;
        itemNumber: number | null;
        modelGroup: string | null;
        modelDetail: string | null;
        bodyStyle: string | null;
        color: string | null;
        secondaryDamage: string | null;
        saleTitleState: string | null;
        saleTitleType: string | null;
        hasKeys: string | null;
        lotCondCode: string | null;
        odometer: Prisma.Decimal | null;
        estRetailValue: Prisma.Decimal | null;
        repairCost: Prisma.Decimal | null;
        drive: string | null;
        transmission: string | null;
        runsDrives: string | null;
        saleStatus: string | null;
        highBid: Prisma.Decimal | null;
        specialNote: string | null;
        locationCity: string | null;
        locationState: string | null;
        locationZip: string | null;
        locationCountry: string | null;
        currencyCode: string | null;
        images: string | null;
        galleryCache: string | null;
        galleryCachedAt: Date | null;
        createDateTime: string | null;
        gridRow: string | null;
        makeOfferEligible: string | null;
        buyItNowPrice: Prisma.Decimal | null;
        lastUpdatedTime: Date | null;
        rentals: string | null;
        wholesale: string | null;
        sellerName: string | null;
        offsiteAddress1: string | null;
        offsiteState: string | null;
        offsiteCity: string | null;
        offsiteZip: string | null;
        saleLight: string | null;
        autoGrade: string | null;
        announcements: string | null;
        sellerCategory: string | null;
        engineSizeL: Prisma.Decimal | null;
        locationLat: number | null;
        locationLng: number | null;
        isStale: boolean;
        discarded: boolean;
        discardReason: string | null;
        discardedAt: Date | null;
        discardedById: string | null;
    } | null>;
    getFilterOptions(): Promise<{
        makes: any;
        damageTypes: any;
        saleStatuses: any;
        states: any;
        years: any;
        titleTypes: any;
    }>;
    getPortalFilters(opts: {
        year?: number;
        make?: string;
        model?: string;
        trim?: string;
    }): Promise<PortalFiltersResult>;
    getStats(): Promise<{
        total: number;
        byDamage: (Prisma.PickEnumerable<Prisma.AuctionListingGroupByOutputType, "damageDescription"[]> & {
            _count: number;
        })[];
        byState: (Prisma.PickEnumerable<Prisma.AuctionListingGroupByOutputType, "locationState"[]> & {
            _count: number;
        })[];
    }>;
}
