import { PrismaService } from '@htownautos/prisma';
import { S3Service } from '@htownautos/common';
import { TranscriptionService } from './transcription.service';
import { TwilioService } from '../twilio/twilio.service';
import { PhoneCallEventsService } from '../presence/phone-call-events.service';
export interface CreateCallInput {
    tenantId: string;
    twilioCallSid: string;
    direction: 'inbound' | 'outbound';
    fromNumber: string;
    toNumber: string;
    status?: string;
    callerId?: string;
}
export interface UpdateCallInput {
    status?: string;
    answeredAt?: Date;
    endedAt?: Date;
    duration?: number;
    outcome?: string;
    notes?: string;
    recordingUrl?: string;
    recordingDuration?: number;
    twilioRecordingSid?: string;
    transcription?: string;
    transcriptionStatus?: string;
}
export declare class PhoneCallService {
    private readonly prisma;
    private readonly s3Service;
    private readonly transcriptionService;
    private readonly twilioService;
    private readonly phoneCallEventsService;
    private readonly logger;
    constructor(prisma: PrismaService, s3Service: S3Service, transcriptionService: TranscriptionService, twilioService: TwilioService, phoneCallEventsService: PhoneCallEventsService);
    private toCallEvent;
    createCall(input: CreateCallInput): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        buyerId: string | null;
        status: string;
        duration: number | null;
        callerId: string | null;
        direction: string;
        fromNumber: string;
        toNumber: string;
        startedAt: Date;
        answeredAt: Date | null;
        endedAt: Date | null;
        outcome: string | null;
        twilioCallSid: string | null;
        twilioRecordingSid: string | null;
        conferenceSid: string | null;
        conferenceName: string | null;
        segmentNumber: number;
        recordingUrl: string | null;
        recordingDuration: number | null;
        transcription: string | null;
        transcriptionStatus: string | null;
        aiSummary: string | null;
        aiSentiment: string | null;
        aiKeyPoints: import("@prisma/client/runtime/client").JsonValue | null;
        aiNextSteps: import("@prisma/client/runtime/client").JsonValue | null;
        transferredAt: Date | null;
        transferredToUserId: string | null;
        transferredFromUserId: string | null;
        transferReason: string | null;
        parentCallId: string | null;
    }>;
    updateCallByTwilioSid(twilioCallSid: string, input: UpdateCallInput): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        buyerId: string | null;
        status: string;
        duration: number | null;
        callerId: string | null;
        direction: string;
        fromNumber: string;
        toNumber: string;
        startedAt: Date;
        answeredAt: Date | null;
        endedAt: Date | null;
        outcome: string | null;
        twilioCallSid: string | null;
        twilioRecordingSid: string | null;
        conferenceSid: string | null;
        conferenceName: string | null;
        segmentNumber: number;
        recordingUrl: string | null;
        recordingDuration: number | null;
        transcription: string | null;
        transcriptionStatus: string | null;
        aiSummary: string | null;
        aiSentiment: string | null;
        aiKeyPoints: import("@prisma/client/runtime/client").JsonValue | null;
        aiNextSteps: import("@prisma/client/runtime/client").JsonValue | null;
        transferredAt: Date | null;
        transferredToUserId: string | null;
        transferredFromUserId: string | null;
        transferReason: string | null;
        parentCallId: string | null;
    } | null>;
    associateUserWithCall(twilioCallSid: string, userId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        buyerId: string | null;
        status: string;
        duration: number | null;
        callerId: string | null;
        direction: string;
        fromNumber: string;
        toNumber: string;
        startedAt: Date;
        answeredAt: Date | null;
        endedAt: Date | null;
        outcome: string | null;
        twilioCallSid: string | null;
        twilioRecordingSid: string | null;
        conferenceSid: string | null;
        conferenceName: string | null;
        segmentNumber: number;
        recordingUrl: string | null;
        recordingDuration: number | null;
        transcription: string | null;
        transcriptionStatus: string | null;
        aiSummary: string | null;
        aiSentiment: string | null;
        aiKeyPoints: import("@prisma/client/runtime/client").JsonValue | null;
        aiNextSteps: import("@prisma/client/runtime/client").JsonValue | null;
        transferredAt: Date | null;
        transferredToUserId: string | null;
        transferredFromUserId: string | null;
        transferReason: string | null;
        parentCallId: string | null;
    }>;
    getCallByTwilioSid(twilioCallSid: string): Promise<({
        buyer: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            leadSource: string | null;
            inquiryType: string | null;
            contactMethod: string | null;
            contactTime: string | null;
            tenantId: string | null;
            notes: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            businessName: string | null;
            email: string;
            firstName: string;
            middleName: string | null;
            lastName: string;
            suffix: string | null;
            dateOfBirth: Date;
            genderId: string | null;
            ssn: string | null;
            itin: string | null;
            citizenship: string | null;
            phoneMain: string;
            phoneSecondary: string | null;
            phoneMobile: string | null;
            preferredLanguageId: string | null;
            currentAddress: string;
            currentCity: string;
            currentState: string;
            currentZipCode: string;
            currentCountry: string;
            yearsAtAddress: number | null;
            monthsAtAddress: number | null;
            housingStatus: string | null;
            monthlyHousingCost: import("@prisma/client-runtime-utils").Decimal | null;
            previousAddress: string | null;
            previousCity: string | null;
            previousState: string | null;
            previousZipCode: string | null;
            previousCountry: string | null;
            yearsAtPreviousAddress: number | null;
            monthsAtPreviousAddress: number | null;
            idTypeId: string | null;
            idNumber: string | null;
            idStateId: string | null;
            idExpirationDate: Date | null;
            idIssueDate: Date | null;
            driversLicenseNumber: string | null;
            driversLicenseState: string | null;
            driversLicenseExpiration: Date | null;
            employmentStatusId: string | null;
            currentEmployer: string | null;
            employerPhone: string | null;
            occupationId: string | null;
            jobTitle: string | null;
            employerAddress: string | null;
            employerCity: string | null;
            employerState: string | null;
            employerZipCode: string | null;
            monthlyIncome: import("@prisma/client-runtime-utils").Decimal | null;
            yearsEmployed: number | null;
            monthsEmployed: number | null;
            additionalIncome: import("@prisma/client-runtime-utils").Decimal | null;
            additionalIncomeSource: string | null;
            previousEmployer: string | null;
            previousEmployerPhone: string | null;
            previousJobTitle: string | null;
            previousEmployerAddress: string | null;
            previousEmployerCity: string | null;
            previousEmployerState: string | null;
            previousEmployerZipCode: string | null;
            previousMonthlyIncome: import("@prisma/client-runtime-utils").Decimal | null;
            previousYearsEmployed: number | null;
            previousMonthsEmployed: number | null;
            bankName: string | null;
            bankAccountType: string | null;
            bankRoutingNumber: string | null;
            bankAccountNumber: string | null;
            yearsWithBank: number | null;
            monthsWithBank: number | null;
            creditScore: number | null;
            bankruptcyHistory: boolean;
            bankruptcyDate: Date | null;
            bankruptcyType: string | null;
            bankruptcyDischargeDate: Date | null;
            repoHistory: boolean;
            repoDate: Date | null;
            foreclosureHistory: boolean;
            foreclosureDate: Date | null;
            currentMonthlyDebts: import("@prisma/client-runtime-utils").Decimal | null;
            alimonyChildSupport: import("@prisma/client-runtime-utils").Decimal | null;
            reference1Name: string | null;
            reference1Phone: string | null;
            reference1Relation: string | null;
            reference1Address: string | null;
            reference1YearsKnown: number | null;
            reference2Name: string | null;
            reference2Phone: string | null;
            reference2Relation: string | null;
            reference2Address: string | null;
            reference2YearsKnown: number | null;
            reference3Name: string | null;
            reference3Phone: string | null;
            reference3Relation: string | null;
            reference3Address: string | null;
            reference3YearsKnown: number | null;
            reference4Name: string | null;
            reference4Phone: string | null;
            reference4Relation: string | null;
            reference4Address: string | null;
            reference4YearsKnown: number | null;
            reference5Name: string | null;
            reference5Phone: string | null;
            reference5Relation: string | null;
            reference5Address: string | null;
            reference5YearsKnown: number | null;
            isBusinessBuyer: boolean;
            businessType: string | null;
            businessEIN: string | null;
            businessYearsInBusiness: number | null;
            businessAnnualRevenue: import("@prisma/client-runtime-utils").Decimal | null;
            ofacCheckCompleted: boolean;
            ofacCheckDate: Date | null;
            ofacCheckResult: string | null;
            ofacNotes: string | null;
            identityVerified: boolean;
            identityVerifiedDate: Date | null;
            identityVerifiedBy: string | null;
            source: string | null;
            leadType: string | null;
            salesPersonId: string | null;
            bdcAgentId: string | null;
            stripeCustomerId: string | null;
            clerkUserId: string | null;
        } | null;
        caller: ({
            user: {
                name: string | null;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                metaValue: import("@prisma/client/runtime/client").JsonValue | null;
                email: string;
                phoneNumber: string | null;
                firstName: string | null;
                lastName: string | null;
                clerkUserId: string | null;
                avatar: string | null;
                emailVerified: boolean;
                lastActivityAt: Date | null;
                lastLoginAt: Date | null;
                lastSeenAt: Date | null;
                isOnline: boolean;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: import("@prisma/client/runtime/client").JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        buyerId: string | null;
        status: string;
        duration: number | null;
        callerId: string | null;
        direction: string;
        fromNumber: string;
        toNumber: string;
        startedAt: Date;
        answeredAt: Date | null;
        endedAt: Date | null;
        outcome: string | null;
        twilioCallSid: string | null;
        twilioRecordingSid: string | null;
        conferenceSid: string | null;
        conferenceName: string | null;
        segmentNumber: number;
        recordingUrl: string | null;
        recordingDuration: number | null;
        transcription: string | null;
        transcriptionStatus: string | null;
        aiSummary: string | null;
        aiSentiment: string | null;
        aiKeyPoints: import("@prisma/client/runtime/client").JsonValue | null;
        aiNextSteps: import("@prisma/client/runtime/client").JsonValue | null;
        transferredAt: Date | null;
        transferredToUserId: string | null;
        transferredFromUserId: string | null;
        transferReason: string | null;
        parentCallId: string | null;
    }) | null>;
    getCallByOriginalSidAndSegment(originalCallSid: string, segmentNumber: number): Promise<({
        buyer: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            leadSource: string | null;
            inquiryType: string | null;
            contactMethod: string | null;
            contactTime: string | null;
            tenantId: string | null;
            notes: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            businessName: string | null;
            email: string;
            firstName: string;
            middleName: string | null;
            lastName: string;
            suffix: string | null;
            dateOfBirth: Date;
            genderId: string | null;
            ssn: string | null;
            itin: string | null;
            citizenship: string | null;
            phoneMain: string;
            phoneSecondary: string | null;
            phoneMobile: string | null;
            preferredLanguageId: string | null;
            currentAddress: string;
            currentCity: string;
            currentState: string;
            currentZipCode: string;
            currentCountry: string;
            yearsAtAddress: number | null;
            monthsAtAddress: number | null;
            housingStatus: string | null;
            monthlyHousingCost: import("@prisma/client-runtime-utils").Decimal | null;
            previousAddress: string | null;
            previousCity: string | null;
            previousState: string | null;
            previousZipCode: string | null;
            previousCountry: string | null;
            yearsAtPreviousAddress: number | null;
            monthsAtPreviousAddress: number | null;
            idTypeId: string | null;
            idNumber: string | null;
            idStateId: string | null;
            idExpirationDate: Date | null;
            idIssueDate: Date | null;
            driversLicenseNumber: string | null;
            driversLicenseState: string | null;
            driversLicenseExpiration: Date | null;
            employmentStatusId: string | null;
            currentEmployer: string | null;
            employerPhone: string | null;
            occupationId: string | null;
            jobTitle: string | null;
            employerAddress: string | null;
            employerCity: string | null;
            employerState: string | null;
            employerZipCode: string | null;
            monthlyIncome: import("@prisma/client-runtime-utils").Decimal | null;
            yearsEmployed: number | null;
            monthsEmployed: number | null;
            additionalIncome: import("@prisma/client-runtime-utils").Decimal | null;
            additionalIncomeSource: string | null;
            previousEmployer: string | null;
            previousEmployerPhone: string | null;
            previousJobTitle: string | null;
            previousEmployerAddress: string | null;
            previousEmployerCity: string | null;
            previousEmployerState: string | null;
            previousEmployerZipCode: string | null;
            previousMonthlyIncome: import("@prisma/client-runtime-utils").Decimal | null;
            previousYearsEmployed: number | null;
            previousMonthsEmployed: number | null;
            bankName: string | null;
            bankAccountType: string | null;
            bankRoutingNumber: string | null;
            bankAccountNumber: string | null;
            yearsWithBank: number | null;
            monthsWithBank: number | null;
            creditScore: number | null;
            bankruptcyHistory: boolean;
            bankruptcyDate: Date | null;
            bankruptcyType: string | null;
            bankruptcyDischargeDate: Date | null;
            repoHistory: boolean;
            repoDate: Date | null;
            foreclosureHistory: boolean;
            foreclosureDate: Date | null;
            currentMonthlyDebts: import("@prisma/client-runtime-utils").Decimal | null;
            alimonyChildSupport: import("@prisma/client-runtime-utils").Decimal | null;
            reference1Name: string | null;
            reference1Phone: string | null;
            reference1Relation: string | null;
            reference1Address: string | null;
            reference1YearsKnown: number | null;
            reference2Name: string | null;
            reference2Phone: string | null;
            reference2Relation: string | null;
            reference2Address: string | null;
            reference2YearsKnown: number | null;
            reference3Name: string | null;
            reference3Phone: string | null;
            reference3Relation: string | null;
            reference3Address: string | null;
            reference3YearsKnown: number | null;
            reference4Name: string | null;
            reference4Phone: string | null;
            reference4Relation: string | null;
            reference4Address: string | null;
            reference4YearsKnown: number | null;
            reference5Name: string | null;
            reference5Phone: string | null;
            reference5Relation: string | null;
            reference5Address: string | null;
            reference5YearsKnown: number | null;
            isBusinessBuyer: boolean;
            businessType: string | null;
            businessEIN: string | null;
            businessYearsInBusiness: number | null;
            businessAnnualRevenue: import("@prisma/client-runtime-utils").Decimal | null;
            ofacCheckCompleted: boolean;
            ofacCheckDate: Date | null;
            ofacCheckResult: string | null;
            ofacNotes: string | null;
            identityVerified: boolean;
            identityVerifiedDate: Date | null;
            identityVerifiedBy: string | null;
            source: string | null;
            leadType: string | null;
            salesPersonId: string | null;
            bdcAgentId: string | null;
            stripeCustomerId: string | null;
            clerkUserId: string | null;
        } | null;
        caller: ({
            user: {
                name: string | null;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                metaValue: import("@prisma/client/runtime/client").JsonValue | null;
                email: string;
                phoneNumber: string | null;
                firstName: string | null;
                lastName: string | null;
                clerkUserId: string | null;
                avatar: string | null;
                emailVerified: boolean;
                lastActivityAt: Date | null;
                lastLoginAt: Date | null;
                lastSeenAt: Date | null;
                isOnline: boolean;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: import("@prisma/client/runtime/client").JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        buyerId: string | null;
        status: string;
        duration: number | null;
        callerId: string | null;
        direction: string;
        fromNumber: string;
        toNumber: string;
        startedAt: Date;
        answeredAt: Date | null;
        endedAt: Date | null;
        outcome: string | null;
        twilioCallSid: string | null;
        twilioRecordingSid: string | null;
        conferenceSid: string | null;
        conferenceName: string | null;
        segmentNumber: number;
        recordingUrl: string | null;
        recordingDuration: number | null;
        transcription: string | null;
        transcriptionStatus: string | null;
        aiSummary: string | null;
        aiSentiment: string | null;
        aiKeyPoints: import("@prisma/client/runtime/client").JsonValue | null;
        aiNextSteps: import("@prisma/client/runtime/client").JsonValue | null;
        transferredAt: Date | null;
        transferredToUserId: string | null;
        transferredFromUserId: string | null;
        transferReason: string | null;
        parentCallId: string | null;
    }) | null>;
    getLatestCallSegment(inputCallSid: string): Promise<{
        buyer: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            leadSource: string | null;
            inquiryType: string | null;
            contactMethod: string | null;
            contactTime: string | null;
            tenantId: string | null;
            notes: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            businessName: string | null;
            email: string;
            firstName: string;
            middleName: string | null;
            lastName: string;
            suffix: string | null;
            dateOfBirth: Date;
            genderId: string | null;
            ssn: string | null;
            itin: string | null;
            citizenship: string | null;
            phoneMain: string;
            phoneSecondary: string | null;
            phoneMobile: string | null;
            preferredLanguageId: string | null;
            currentAddress: string;
            currentCity: string;
            currentState: string;
            currentZipCode: string;
            currentCountry: string;
            yearsAtAddress: number | null;
            monthsAtAddress: number | null;
            housingStatus: string | null;
            monthlyHousingCost: import("@prisma/client-runtime-utils").Decimal | null;
            previousAddress: string | null;
            previousCity: string | null;
            previousState: string | null;
            previousZipCode: string | null;
            previousCountry: string | null;
            yearsAtPreviousAddress: number | null;
            monthsAtPreviousAddress: number | null;
            idTypeId: string | null;
            idNumber: string | null;
            idStateId: string | null;
            idExpirationDate: Date | null;
            idIssueDate: Date | null;
            driversLicenseNumber: string | null;
            driversLicenseState: string | null;
            driversLicenseExpiration: Date | null;
            employmentStatusId: string | null;
            currentEmployer: string | null;
            employerPhone: string | null;
            occupationId: string | null;
            jobTitle: string | null;
            employerAddress: string | null;
            employerCity: string | null;
            employerState: string | null;
            employerZipCode: string | null;
            monthlyIncome: import("@prisma/client-runtime-utils").Decimal | null;
            yearsEmployed: number | null;
            monthsEmployed: number | null;
            additionalIncome: import("@prisma/client-runtime-utils").Decimal | null;
            additionalIncomeSource: string | null;
            previousEmployer: string | null;
            previousEmployerPhone: string | null;
            previousJobTitle: string | null;
            previousEmployerAddress: string | null;
            previousEmployerCity: string | null;
            previousEmployerState: string | null;
            previousEmployerZipCode: string | null;
            previousMonthlyIncome: import("@prisma/client-runtime-utils").Decimal | null;
            previousYearsEmployed: number | null;
            previousMonthsEmployed: number | null;
            bankName: string | null;
            bankAccountType: string | null;
            bankRoutingNumber: string | null;
            bankAccountNumber: string | null;
            yearsWithBank: number | null;
            monthsWithBank: number | null;
            creditScore: number | null;
            bankruptcyHistory: boolean;
            bankruptcyDate: Date | null;
            bankruptcyType: string | null;
            bankruptcyDischargeDate: Date | null;
            repoHistory: boolean;
            repoDate: Date | null;
            foreclosureHistory: boolean;
            foreclosureDate: Date | null;
            currentMonthlyDebts: import("@prisma/client-runtime-utils").Decimal | null;
            alimonyChildSupport: import("@prisma/client-runtime-utils").Decimal | null;
            reference1Name: string | null;
            reference1Phone: string | null;
            reference1Relation: string | null;
            reference1Address: string | null;
            reference1YearsKnown: number | null;
            reference2Name: string | null;
            reference2Phone: string | null;
            reference2Relation: string | null;
            reference2Address: string | null;
            reference2YearsKnown: number | null;
            reference3Name: string | null;
            reference3Phone: string | null;
            reference3Relation: string | null;
            reference3Address: string | null;
            reference3YearsKnown: number | null;
            reference4Name: string | null;
            reference4Phone: string | null;
            reference4Relation: string | null;
            reference4Address: string | null;
            reference4YearsKnown: number | null;
            reference5Name: string | null;
            reference5Phone: string | null;
            reference5Relation: string | null;
            reference5Address: string | null;
            reference5YearsKnown: number | null;
            isBusinessBuyer: boolean;
            businessType: string | null;
            businessEIN: string | null;
            businessYearsInBusiness: number | null;
            businessAnnualRevenue: import("@prisma/client-runtime-utils").Decimal | null;
            ofacCheckCompleted: boolean;
            ofacCheckDate: Date | null;
            ofacCheckResult: string | null;
            ofacNotes: string | null;
            identityVerified: boolean;
            identityVerifiedDate: Date | null;
            identityVerifiedBy: string | null;
            source: string | null;
            leadType: string | null;
            salesPersonId: string | null;
            bdcAgentId: string | null;
            stripeCustomerId: string | null;
            clerkUserId: string | null;
        } | null;
        caller: ({
            user: {
                name: string | null;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                metaValue: import("@prisma/client/runtime/client").JsonValue | null;
                email: string;
                phoneNumber: string | null;
                firstName: string | null;
                lastName: string | null;
                clerkUserId: string | null;
                avatar: string | null;
                emailVerified: boolean;
                lastActivityAt: Date | null;
                lastLoginAt: Date | null;
                lastSeenAt: Date | null;
                isOnline: boolean;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: import("@prisma/client/runtime/client").JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        buyerId: string | null;
        status: string;
        duration: number | null;
        callerId: string | null;
        direction: string;
        fromNumber: string;
        toNumber: string;
        startedAt: Date;
        answeredAt: Date | null;
        endedAt: Date | null;
        outcome: string | null;
        twilioCallSid: string | null;
        twilioRecordingSid: string | null;
        conferenceSid: string | null;
        conferenceName: string | null;
        segmentNumber: number;
        recordingUrl: string | null;
        recordingDuration: number | null;
        transcription: string | null;
        transcriptionStatus: string | null;
        aiSummary: string | null;
        aiSentiment: string | null;
        aiKeyPoints: import("@prisma/client/runtime/client").JsonValue | null;
        aiNextSteps: import("@prisma/client/runtime/client").JsonValue | null;
        transferredAt: Date | null;
        transferredToUserId: string | null;
        transferredFromUserId: string | null;
        transferReason: string | null;
        parentCallId: string | null;
    }>;
    processRecording(twilioCallSid: string, twilioRecordingSid: string, recordingUrl: string, recordingDuration: number): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        buyerId: string | null;
        status: string;
        duration: number | null;
        callerId: string | null;
        direction: string;
        fromNumber: string;
        toNumber: string;
        startedAt: Date;
        answeredAt: Date | null;
        endedAt: Date | null;
        outcome: string | null;
        twilioCallSid: string | null;
        twilioRecordingSid: string | null;
        conferenceSid: string | null;
        conferenceName: string | null;
        segmentNumber: number;
        recordingUrl: string | null;
        recordingDuration: number | null;
        transcription: string | null;
        transcriptionStatus: string | null;
        aiSummary: string | null;
        aiSentiment: string | null;
        aiKeyPoints: import("@prisma/client/runtime/client").JsonValue | null;
        aiNextSteps: import("@prisma/client/runtime/client").JsonValue | null;
        transferredAt: Date | null;
        transferredToUserId: string | null;
        transferredFromUserId: string | null;
        transferReason: string | null;
        parentCallId: string | null;
    } | null>;
    processSegmentRecording(twilioCallSid: string, segmentNumber: number, twilioRecordingSid: string, recordingUrl: string, recordingDuration: number): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        buyerId: string | null;
        status: string;
        duration: number | null;
        callerId: string | null;
        direction: string;
        fromNumber: string;
        toNumber: string;
        startedAt: Date;
        answeredAt: Date | null;
        endedAt: Date | null;
        outcome: string | null;
        twilioCallSid: string | null;
        twilioRecordingSid: string | null;
        conferenceSid: string | null;
        conferenceName: string | null;
        segmentNumber: number;
        recordingUrl: string | null;
        recordingDuration: number | null;
        transcription: string | null;
        transcriptionStatus: string | null;
        aiSummary: string | null;
        aiSentiment: string | null;
        aiKeyPoints: import("@prisma/client/runtime/client").JsonValue | null;
        aiNextSteps: import("@prisma/client/runtime/client").JsonValue | null;
        transferredAt: Date | null;
        transferredToUserId: string | null;
        transferredFromUserId: string | null;
        transferReason: string | null;
        parentCallId: string | null;
    } | null>;
    updateConferenceInfo(originalCallSid: string, segmentNumber: number, conferenceSid: string, conferenceName: string): Promise<import("@prisma/client").Prisma.BatchPayload>;
    dialAgentIntoConference(originalCallSid: string, segmentNumber: number, conferenceName: string, tenantId: string): Promise<void>;
    private dialSingleAgentIntoConference;
    private constructTwilioCallSid;
    private storeAgentCallSid;
    private generateJoinConferenceTwiml;
    handleAgentJoinedConference(originalCallSid: string, segmentNumber: number, agentCallSid: string): Promise<{
        count: number;
    }>;
    terminatePendingAgentCalls(originalCallSid: string, segmentNumber: number): Promise<void>;
    wasCallAnswered(twilioCallSid: string): Promise<boolean>;
    terminateCallerCall(twilioCallSid: string): Promise<void>;
    redirectCallerCall(twilioCallSid: string, twiml: string): Promise<void>;
    handleAgentCallStatus(originalCallSid: string, segmentNumber: number, agentCallSid: string, callStatus: string): Promise<boolean>;
    private removeAgentCallSid;
    didConferenceAttemptFail(originalCallSid: string, segmentNumber: number): Promise<boolean>;
    clearConferenceAttemptFailed(originalCallSid: string, segmentNumber: number): Promise<void>;
    updateTranscription(twilioCallSid: string, transcription: string, status: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        buyerId: string | null;
        status: string;
        duration: number | null;
        callerId: string | null;
        direction: string;
        fromNumber: string;
        toNumber: string;
        startedAt: Date;
        answeredAt: Date | null;
        endedAt: Date | null;
        outcome: string | null;
        twilioCallSid: string | null;
        twilioRecordingSid: string | null;
        conferenceSid: string | null;
        conferenceName: string | null;
        segmentNumber: number;
        recordingUrl: string | null;
        recordingDuration: number | null;
        transcription: string | null;
        transcriptionStatus: string | null;
        aiSummary: string | null;
        aiSentiment: string | null;
        aiKeyPoints: import("@prisma/client/runtime/client").JsonValue | null;
        aiNextSteps: import("@prisma/client/runtime/client").JsonValue | null;
        transferredAt: Date | null;
        transferredToUserId: string | null;
        transferredFromUserId: string | null;
        transferReason: string | null;
        parentCallId: string | null;
    }>;
    private findBuyerByPhone;
    private normalizePhone;
    private uploadRecordingToS3;
    getCallsForTenant(tenantId: string, options?: {
        page?: number;
        limit?: number;
        direction?: string;
        buyerId?: string;
        callerId?: string;
        startDate?: Date;
        endDate?: Date;
    }): Promise<{
        data: ({
            buyer: {
                id: string;
                firstName: string;
                lastName: string;
                phoneMain: string;
            } | null;
            transferredFrom: ({
                user: {
                    id: string;
                    email: string;
                    firstName: string | null;
                    lastName: string | null;
                };
            } & {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                userId: string;
                status: string;
                username: string | null;
                tenantEmail: string | null;
                extension: string | null;
                permissions: import("@prisma/client/runtime/client").JsonValue | null;
                roleId: string;
                acceptedAt: Date | null;
                invitationCode: string | null;
                invitationSentAt: Date | null;
                invitedBy: string | null;
                removedAt: Date | null;
            }) | null;
            transferredTo: ({
                user: {
                    id: string;
                    email: string;
                    firstName: string | null;
                    lastName: string | null;
                };
            } & {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                userId: string;
                status: string;
                username: string | null;
                tenantEmail: string | null;
                extension: string | null;
                permissions: import("@prisma/client/runtime/client").JsonValue | null;
                roleId: string;
                acceptedAt: Date | null;
                invitationCode: string | null;
                invitationSentAt: Date | null;
                invitedBy: string | null;
                removedAt: Date | null;
            }) | null;
            caller: ({
                user: {
                    id: string;
                    email: string;
                    firstName: string | null;
                    lastName: string | null;
                };
            } & {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                userId: string;
                status: string;
                username: string | null;
                tenantEmail: string | null;
                extension: string | null;
                permissions: import("@prisma/client/runtime/client").JsonValue | null;
                roleId: string;
                acceptedAt: Date | null;
                invitationCode: string | null;
                invitationSentAt: Date | null;
                invitedBy: string | null;
                removedAt: Date | null;
            }) | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            notes: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            buyerId: string | null;
            status: string;
            duration: number | null;
            callerId: string | null;
            direction: string;
            fromNumber: string;
            toNumber: string;
            startedAt: Date;
            answeredAt: Date | null;
            endedAt: Date | null;
            outcome: string | null;
            twilioCallSid: string | null;
            twilioRecordingSid: string | null;
            conferenceSid: string | null;
            conferenceName: string | null;
            segmentNumber: number;
            recordingUrl: string | null;
            recordingDuration: number | null;
            transcription: string | null;
            transcriptionStatus: string | null;
            aiSummary: string | null;
            aiSentiment: string | null;
            aiKeyPoints: import("@prisma/client/runtime/client").JsonValue | null;
            aiNextSteps: import("@prisma/client/runtime/client").JsonValue | null;
            transferredAt: Date | null;
            transferredToUserId: string | null;
            transferredFromUserId: string | null;
            transferReason: string | null;
            parentCallId: string | null;
        })[];
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    }>;
    getCallsForBuyer(tenantId: string, buyerId: string): Promise<({
        transferredFrom: ({
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: import("@prisma/client/runtime/client").JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
        transferredTo: ({
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: import("@prisma/client/runtime/client").JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
        caller: ({
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: import("@prisma/client/runtime/client").JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        buyerId: string | null;
        status: string;
        duration: number | null;
        callerId: string | null;
        direction: string;
        fromNumber: string;
        toNumber: string;
        startedAt: Date;
        answeredAt: Date | null;
        endedAt: Date | null;
        outcome: string | null;
        twilioCallSid: string | null;
        twilioRecordingSid: string | null;
        conferenceSid: string | null;
        conferenceName: string | null;
        segmentNumber: number;
        recordingUrl: string | null;
        recordingDuration: number | null;
        transcription: string | null;
        transcriptionStatus: string | null;
        aiSummary: string | null;
        aiSentiment: string | null;
        aiKeyPoints: import("@prisma/client/runtime/client").JsonValue | null;
        aiNextSteps: import("@prisma/client/runtime/client").JsonValue | null;
        transferredAt: Date | null;
        transferredToUserId: string | null;
        transferredFromUserId: string | null;
        transferReason: string | null;
        parentCallId: string | null;
    })[]>;
    transferCall(twilioCallSid: string, transferToUserId: string, transferFromUserId: string, reason?: string): Promise<{
        transferredFrom: ({
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: import("@prisma/client/runtime/client").JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
        transferredTo: ({
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
            };
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            userId: string;
            status: string;
            username: string | null;
            tenantEmail: string | null;
            extension: string | null;
            permissions: import("@prisma/client/runtime/client").JsonValue | null;
            roleId: string;
            acceptedAt: Date | null;
            invitationCode: string | null;
            invitationSentAt: Date | null;
            invitedBy: string | null;
            removedAt: Date | null;
        }) | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        metaValue: import("@prisma/client/runtime/client").JsonValue | null;
        buyerId: string | null;
        status: string;
        duration: number | null;
        callerId: string | null;
        direction: string;
        fromNumber: string;
        toNumber: string;
        startedAt: Date;
        answeredAt: Date | null;
        endedAt: Date | null;
        outcome: string | null;
        twilioCallSid: string | null;
        twilioRecordingSid: string | null;
        conferenceSid: string | null;
        conferenceName: string | null;
        segmentNumber: number;
        recordingUrl: string | null;
        recordingDuration: number | null;
        transcription: string | null;
        transcriptionStatus: string | null;
        aiSummary: string | null;
        aiSentiment: string | null;
        aiKeyPoints: import("@prisma/client/runtime/client").JsonValue | null;
        aiNextSteps: import("@prisma/client/runtime/client").JsonValue | null;
        transferredAt: Date | null;
        transferredToUserId: string | null;
        transferredFromUserId: string | null;
        transferReason: string | null;
        parentCallId: string | null;
    }>;
    private generateTransferConferenceTwiml;
    getAvailableTransferTargets(tenantId: string, excludeUserId?: string): Promise<{
        id: string;
        name: string;
        email: string;
        avatar: string | null;
        role: string;
        extension: string | null;
    }[]>;
    resegmentTranscription(twilioCallSid: string): Promise<number>;
    resegmentAllTranscriptionsForTenant(tenantId: string): Promise<{
        processed: number;
        errors: number;
    }>;
}
