import { PartOrdersService } from './part-orders.service';
import { CreateOrderDto, UpdateOrderDto, CreateShipmentDto, BuyLabelDto, ChargeOrderDto, EstimateShippingDto } from './dto/order.dto';
export declare class PartOrdersController {
    private readonly service;
    constructor(service: PartOrdersService);
    findAll(tenantId: string, page?: string, limit?: string, status?: string, search?: string, buyerId?: string): Promise<{
        data: ({
            buyer: {
                id: string;
                email: string;
                firstName: string;
                lastName: string;
                phoneMain: string;
            };
            items: {
                id: string;
                createdAt: Date;
                partId: string;
                quantity: number;
                orderId: string;
                unitPrice: import("@prisma/client-runtime-utils").Decimal;
                totalPrice: import("@prisma/client-runtime-utils").Decimal;
                nameSnapshot: string;
                skuSnapshot: string | null;
            }[];
            shipments: {
                length: import("@prisma/client-runtime-utils").Decimal | null;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: string;
                width: import("@prisma/client-runtime-utils").Decimal | null;
                height: import("@prisma/client-runtime-utils").Decimal | null;
                cost: import("@prisma/client-runtime-utils").Decimal | null;
                weight: import("@prisma/client-runtime-utils").Decimal | null;
                cancelledAt: Date | null;
                deliveredAt: Date | null;
                carrier: string;
                distanceUnit: string | null;
                massUnit: string | null;
                orderId: string;
                parcelTemplateId: string | null;
                serviceLevel: string | null;
                serviceLevelName: string | null;
                shippoShipmentId: string | null;
                shippoTransactionId: string | null;
                shippoRateId: string | null;
                labelUrl: string | null;
                trackingNumber: string | null;
                trackingUrl: string | null;
                trackingStatus: string | null;
                purchasedAt: Date | null;
                shippedAt: Date | null;
            }[];
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            notes: string | null;
            createdById: string | null;
            buyerId: string;
            status: string;
            discount: import("@prisma/client-runtime-utils").Decimal;
            customerNotes: string | null;
            shippingCost: import("@prisma/client-runtime-utils").Decimal;
            tax: import("@prisma/client-runtime-utils").Decimal;
            cancelledAt: Date | null;
            paidAt: Date | null;
            orderNumber: string;
            subtotal: import("@prisma/client-runtime-utils").Decimal;
            taxRate: import("@prisma/client-runtime-utils").Decimal;
            total: import("@prisma/client-runtime-utils").Decimal;
            paymentMethod: string | null;
            paymentStatus: string;
            stripePaymentIntentId: string | null;
            stripeChargeId: string | null;
            shippingMethod: string | null;
            shipToName: string | null;
            shipToStreet1: string | null;
            shipToStreet2: string | null;
            shipToCity: string | null;
            shipToState: string | null;
            shipToZip: string | null;
            shipToCountry: string | null;
            shipToPhone: string | null;
            shipToEmail: string | null;
        })[];
        meta: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNextPage: boolean;
        };
    }>;
    findOne(tenantId: string, id: string): Promise<{
        buyer: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            leadSource: string | null;
            inquiryType: string | null;
            contactMethod: string | null;
            contactTime: string | null;
            tenantId: string | null;
            notes: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            businessName: string | null;
            email: string;
            firstName: string;
            middleName: string | null;
            lastName: string;
            suffix: string | null;
            dateOfBirth: Date;
            genderId: string | null;
            ssn: string | null;
            itin: string | null;
            citizenship: string | null;
            phoneMain: string;
            phoneSecondary: string | null;
            phoneMobile: string | null;
            preferredLanguageId: string | null;
            currentAddress: string;
            currentCity: string;
            currentState: string;
            currentZipCode: string;
            currentCountry: string;
            yearsAtAddress: number | null;
            monthsAtAddress: number | null;
            housingStatus: string | null;
            monthlyHousingCost: import("@prisma/client-runtime-utils").Decimal | null;
            previousAddress: string | null;
            previousCity: string | null;
            previousState: string | null;
            previousZipCode: string | null;
            previousCountry: string | null;
            yearsAtPreviousAddress: number | null;
            monthsAtPreviousAddress: number | null;
            idTypeId: string | null;
            idNumber: string | null;
            idStateId: string | null;
            idExpirationDate: Date | null;
            idIssueDate: Date | null;
            driversLicenseNumber: string | null;
            driversLicenseState: string | null;
            driversLicenseExpiration: Date | null;
            employmentStatusId: string | null;
            currentEmployer: string | null;
            employerPhone: string | null;
            occupationId: string | null;
            jobTitle: string | null;
            employerAddress: string | null;
            employerCity: string | null;
            employerState: string | null;
            employerZipCode: string | null;
            monthlyIncome: import("@prisma/client-runtime-utils").Decimal | null;
            yearsEmployed: number | null;
            monthsEmployed: number | null;
            additionalIncome: import("@prisma/client-runtime-utils").Decimal | null;
            additionalIncomeSource: string | null;
            previousEmployer: string | null;
            previousEmployerPhone: string | null;
            previousJobTitle: string | null;
            previousEmployerAddress: string | null;
            previousEmployerCity: string | null;
            previousEmployerState: string | null;
            previousEmployerZipCode: string | null;
            previousMonthlyIncome: import("@prisma/client-runtime-utils").Decimal | null;
            previousYearsEmployed: number | null;
            previousMonthsEmployed: number | null;
            bankName: string | null;
            bankAccountType: string | null;
            bankRoutingNumber: string | null;
            bankAccountNumber: string | null;
            yearsWithBank: number | null;
            monthsWithBank: number | null;
            creditScore: number | null;
            bankruptcyHistory: boolean;
            bankruptcyDate: Date | null;
            bankruptcyType: string | null;
            bankruptcyDischargeDate: Date | null;
            repoHistory: boolean;
            repoDate: Date | null;
            foreclosureHistory: boolean;
            foreclosureDate: Date | null;
            currentMonthlyDebts: import("@prisma/client-runtime-utils").Decimal | null;
            alimonyChildSupport: import("@prisma/client-runtime-utils").Decimal | null;
            reference1Name: string | null;
            reference1Phone: string | null;
            reference1Relation: string | null;
            reference1Address: string | null;
            reference1YearsKnown: number | null;
            reference2Name: string | null;
            reference2Phone: string | null;
            reference2Relation: string | null;
            reference2Address: string | null;
            reference2YearsKnown: number | null;
            reference3Name: string | null;
            reference3Phone: string | null;
            reference3Relation: string | null;
            reference3Address: string | null;
            reference3YearsKnown: number | null;
            reference4Name: string | null;
            reference4Phone: string | null;
            reference4Relation: string | null;
            reference4Address: string | null;
            reference4YearsKnown: number | null;
            reference5Name: string | null;
            reference5Phone: string | null;
            reference5Relation: string | null;
            reference5Address: string | null;
            reference5YearsKnown: number | null;
            isBusinessBuyer: boolean;
            businessType: string | null;
            businessEIN: string | null;
            businessYearsInBusiness: number | null;
            businessAnnualRevenue: import("@prisma/client-runtime-utils").Decimal | null;
            ofacCheckCompleted: boolean;
            ofacCheckDate: Date | null;
            ofacCheckResult: string | null;
            ofacNotes: string | null;
            identityVerified: boolean;
            identityVerifiedDate: Date | null;
            identityVerifiedBy: string | null;
            source: string | null;
            leadType: string | null;
            salesPersonId: string | null;
            bdcAgentId: string | null;
            stripeCustomerId: string | null;
            clerkUserId: string | null;
        };
        items: ({
            part: {
                mainImage: {
                    path: string | null;
                    url: string;
                    id: string;
                    title: string | null;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    tenantId: string | null;
                    description: string | null;
                    metaValue: import("@prisma/client/runtime/client").JsonValue | null;
                    buyerId: string | null;
                    vehicleId: string | null;
                    partId: string | null;
                    duration: number | null;
                    filename: string;
                    mimeType: string;
                    size: number;
                    width: number | null;
                    height: number | null;
                    alt: string | null;
                    mediaType: string;
                    category: string | null;
                    storageProvider: string | null;
                    storageBucket: string | null;
                    storageKey: string | null;
                    isPublic: boolean;
                    inspectionId: string | null;
                    inspectionChecklistItemId: string | null;
                    inspectionRequestItemId: string | null;
                    inspectionErrorCodeId: string | null;
                    carfaxReportId: string | null;
                } | null;
            } & {
                length: import("@prisma/client-runtime-utils").Decimal | null;
                name: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                description: string | null;
                notes: string | null;
                mainImageId: string | null;
                makeId: string | null;
                modelId: string | null;
                trimId: string | null;
                yearId: string | null;
                metaValue: import("@prisma/client/runtime/client").JsonValue | null;
                purchaseDate: Date | null;
                price: import("@prisma/client-runtime-utils").Decimal;
                width: import("@prisma/client-runtime-utils").Decimal | null;
                height: import("@prisma/client-runtime-utils").Decimal | null;
                partNumber: string | null;
                sku: string | null;
                categoryId: string | null;
                conditionId: string;
                statusId: string;
                cost: import("@prisma/client-runtime-utils").Decimal | null;
                quantity: number;
                minQuantity: number;
                location: string | null;
                warehouseSection: string | null;
                sourceVin: string | null;
                sourceMiles: number | null;
                sourceVehicleId: string | null;
                weight: import("@prisma/client-runtime-utils").Decimal | null;
                warrantyDays: number | null;
                warrantyNotes: string | null;
                supplier: string | null;
                supplierPartNumber: string | null;
                purchaseOrderNumber: string | null;
                brand: string | null;
                manufacturer: string | null;
                countryOfOrigin: string | null;
                isOem: boolean;
                isAftermarket: boolean;
                soldAt: Date | null;
                soldToId: string | null;
                soldPrice: import("@prisma/client-runtime-utils").Decimal | null;
                soldDealId: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            partId: string;
            quantity: number;
            orderId: string;
            unitPrice: import("@prisma/client-runtime-utils").Decimal;
            totalPrice: import("@prisma/client-runtime-utils").Decimal;
            nameSnapshot: string;
            skuSnapshot: string | null;
        })[];
        shipments: ({
            parcelTemplate: {
                length: import("@prisma/client-runtime-utils").Decimal;
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                width: import("@prisma/client-runtime-utils").Decimal;
                height: import("@prisma/client-runtime-utils").Decimal;
                carrier: string | null;
                shippoTemplateToken: string | null;
                distanceUnit: string;
                defaultWeight: import("@prisma/client-runtime-utils").Decimal | null;
                massUnit: string;
                isDefault: boolean;
            } | null;
        } & {
            length: import("@prisma/client-runtime-utils").Decimal | null;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: string;
            width: import("@prisma/client-runtime-utils").Decimal | null;
            height: import("@prisma/client-runtime-utils").Decimal | null;
            cost: import("@prisma/client-runtime-utils").Decimal | null;
            weight: import("@prisma/client-runtime-utils").Decimal | null;
            cancelledAt: Date | null;
            deliveredAt: Date | null;
            carrier: string;
            distanceUnit: string | null;
            massUnit: string | null;
            orderId: string;
            parcelTemplateId: string | null;
            serviceLevel: string | null;
            serviceLevelName: string | null;
            shippoShipmentId: string | null;
            shippoTransactionId: string | null;
            shippoRateId: string | null;
            labelUrl: string | null;
            trackingNumber: string | null;
            trackingUrl: string | null;
            trackingStatus: string | null;
            purchasedAt: Date | null;
            shippedAt: Date | null;
        })[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        createdById: string | null;
        buyerId: string;
        status: string;
        discount: import("@prisma/client-runtime-utils").Decimal;
        customerNotes: string | null;
        shippingCost: import("@prisma/client-runtime-utils").Decimal;
        tax: import("@prisma/client-runtime-utils").Decimal;
        cancelledAt: Date | null;
        paidAt: Date | null;
        orderNumber: string;
        subtotal: import("@prisma/client-runtime-utils").Decimal;
        taxRate: import("@prisma/client-runtime-utils").Decimal;
        total: import("@prisma/client-runtime-utils").Decimal;
        paymentMethod: string | null;
        paymentStatus: string;
        stripePaymentIntentId: string | null;
        stripeChargeId: string | null;
        shippingMethod: string | null;
        shipToName: string | null;
        shipToStreet1: string | null;
        shipToStreet2: string | null;
        shipToCity: string | null;
        shipToState: string | null;
        shipToZip: string | null;
        shipToCountry: string | null;
        shipToPhone: string | null;
        shipToEmail: string | null;
    }>;
    create(tenantId: string, user: any, dto: CreateOrderDto): Promise<{
        buyer: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            leadSource: string | null;
            inquiryType: string | null;
            contactMethod: string | null;
            contactTime: string | null;
            tenantId: string | null;
            notes: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            businessName: string | null;
            email: string;
            firstName: string;
            middleName: string | null;
            lastName: string;
            suffix: string | null;
            dateOfBirth: Date;
            genderId: string | null;
            ssn: string | null;
            itin: string | null;
            citizenship: string | null;
            phoneMain: string;
            phoneSecondary: string | null;
            phoneMobile: string | null;
            preferredLanguageId: string | null;
            currentAddress: string;
            currentCity: string;
            currentState: string;
            currentZipCode: string;
            currentCountry: string;
            yearsAtAddress: number | null;
            monthsAtAddress: number | null;
            housingStatus: string | null;
            monthlyHousingCost: import("@prisma/client-runtime-utils").Decimal | null;
            previousAddress: string | null;
            previousCity: string | null;
            previousState: string | null;
            previousZipCode: string | null;
            previousCountry: string | null;
            yearsAtPreviousAddress: number | null;
            monthsAtPreviousAddress: number | null;
            idTypeId: string | null;
            idNumber: string | null;
            idStateId: string | null;
            idExpirationDate: Date | null;
            idIssueDate: Date | null;
            driversLicenseNumber: string | null;
            driversLicenseState: string | null;
            driversLicenseExpiration: Date | null;
            employmentStatusId: string | null;
            currentEmployer: string | null;
            employerPhone: string | null;
            occupationId: string | null;
            jobTitle: string | null;
            employerAddress: string | null;
            employerCity: string | null;
            employerState: string | null;
            employerZipCode: string | null;
            monthlyIncome: import("@prisma/client-runtime-utils").Decimal | null;
            yearsEmployed: number | null;
            monthsEmployed: number | null;
            additionalIncome: import("@prisma/client-runtime-utils").Decimal | null;
            additionalIncomeSource: string | null;
            previousEmployer: string | null;
            previousEmployerPhone: string | null;
            previousJobTitle: string | null;
            previousEmployerAddress: string | null;
            previousEmployerCity: string | null;
            previousEmployerState: string | null;
            previousEmployerZipCode: string | null;
            previousMonthlyIncome: import("@prisma/client-runtime-utils").Decimal | null;
            previousYearsEmployed: number | null;
            previousMonthsEmployed: number | null;
            bankName: string | null;
            bankAccountType: string | null;
            bankRoutingNumber: string | null;
            bankAccountNumber: string | null;
            yearsWithBank: number | null;
            monthsWithBank: number | null;
            creditScore: number | null;
            bankruptcyHistory: boolean;
            bankruptcyDate: Date | null;
            bankruptcyType: string | null;
            bankruptcyDischargeDate: Date | null;
            repoHistory: boolean;
            repoDate: Date | null;
            foreclosureHistory: boolean;
            foreclosureDate: Date | null;
            currentMonthlyDebts: import("@prisma/client-runtime-utils").Decimal | null;
            alimonyChildSupport: import("@prisma/client-runtime-utils").Decimal | null;
            reference1Name: string | null;
            reference1Phone: string | null;
            reference1Relation: string | null;
            reference1Address: string | null;
            reference1YearsKnown: number | null;
            reference2Name: string | null;
            reference2Phone: string | null;
            reference2Relation: string | null;
            reference2Address: string | null;
            reference2YearsKnown: number | null;
            reference3Name: string | null;
            reference3Phone: string | null;
            reference3Relation: string | null;
            reference3Address: string | null;
            reference3YearsKnown: number | null;
            reference4Name: string | null;
            reference4Phone: string | null;
            reference4Relation: string | null;
            reference4Address: string | null;
            reference4YearsKnown: number | null;
            reference5Name: string | null;
            reference5Phone: string | null;
            reference5Relation: string | null;
            reference5Address: string | null;
            reference5YearsKnown: number | null;
            isBusinessBuyer: boolean;
            businessType: string | null;
            businessEIN: string | null;
            businessYearsInBusiness: number | null;
            businessAnnualRevenue: import("@prisma/client-runtime-utils").Decimal | null;
            ofacCheckCompleted: boolean;
            ofacCheckDate: Date | null;
            ofacCheckResult: string | null;
            ofacNotes: string | null;
            identityVerified: boolean;
            identityVerifiedDate: Date | null;
            identityVerifiedBy: string | null;
            source: string | null;
            leadType: string | null;
            salesPersonId: string | null;
            bdcAgentId: string | null;
            stripeCustomerId: string | null;
            clerkUserId: string | null;
        };
        items: ({
            part: {
                length: import("@prisma/client-runtime-utils").Decimal | null;
                name: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                description: string | null;
                notes: string | null;
                mainImageId: string | null;
                makeId: string | null;
                modelId: string | null;
                trimId: string | null;
                yearId: string | null;
                metaValue: import("@prisma/client/runtime/client").JsonValue | null;
                purchaseDate: Date | null;
                price: import("@prisma/client-runtime-utils").Decimal;
                width: import("@prisma/client-runtime-utils").Decimal | null;
                height: import("@prisma/client-runtime-utils").Decimal | null;
                partNumber: string | null;
                sku: string | null;
                categoryId: string | null;
                conditionId: string;
                statusId: string;
                cost: import("@prisma/client-runtime-utils").Decimal | null;
                quantity: number;
                minQuantity: number;
                location: string | null;
                warehouseSection: string | null;
                sourceVin: string | null;
                sourceMiles: number | null;
                sourceVehicleId: string | null;
                weight: import("@prisma/client-runtime-utils").Decimal | null;
                warrantyDays: number | null;
                warrantyNotes: string | null;
                supplier: string | null;
                supplierPartNumber: string | null;
                purchaseOrderNumber: string | null;
                brand: string | null;
                manufacturer: string | null;
                countryOfOrigin: string | null;
                isOem: boolean;
                isAftermarket: boolean;
                soldAt: Date | null;
                soldToId: string | null;
                soldPrice: import("@prisma/client-runtime-utils").Decimal | null;
                soldDealId: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            partId: string;
            quantity: number;
            orderId: string;
            unitPrice: import("@prisma/client-runtime-utils").Decimal;
            totalPrice: import("@prisma/client-runtime-utils").Decimal;
            nameSnapshot: string;
            skuSnapshot: string | null;
        })[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        createdById: string | null;
        buyerId: string;
        status: string;
        discount: import("@prisma/client-runtime-utils").Decimal;
        customerNotes: string | null;
        shippingCost: import("@prisma/client-runtime-utils").Decimal;
        tax: import("@prisma/client-runtime-utils").Decimal;
        cancelledAt: Date | null;
        paidAt: Date | null;
        orderNumber: string;
        subtotal: import("@prisma/client-runtime-utils").Decimal;
        taxRate: import("@prisma/client-runtime-utils").Decimal;
        total: import("@prisma/client-runtime-utils").Decimal;
        paymentMethod: string | null;
        paymentStatus: string;
        stripePaymentIntentId: string | null;
        stripeChargeId: string | null;
        shippingMethod: string | null;
        shipToName: string | null;
        shipToStreet1: string | null;
        shipToStreet2: string | null;
        shipToCity: string | null;
        shipToState: string | null;
        shipToZip: string | null;
        shipToCountry: string | null;
        shipToPhone: string | null;
        shipToEmail: string | null;
    }>;
    update(tenantId: string, id: string, dto: UpdateOrderDto): Promise<{
        buyer: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            leadSource: string | null;
            inquiryType: string | null;
            contactMethod: string | null;
            contactTime: string | null;
            tenantId: string | null;
            notes: string | null;
            metaValue: import("@prisma/client/runtime/client").JsonValue | null;
            businessName: string | null;
            email: string;
            firstName: string;
            middleName: string | null;
            lastName: string;
            suffix: string | null;
            dateOfBirth: Date;
            genderId: string | null;
            ssn: string | null;
            itin: string | null;
            citizenship: string | null;
            phoneMain: string;
            phoneSecondary: string | null;
            phoneMobile: string | null;
            preferredLanguageId: string | null;
            currentAddress: string;
            currentCity: string;
            currentState: string;
            currentZipCode: string;
            currentCountry: string;
            yearsAtAddress: number | null;
            monthsAtAddress: number | null;
            housingStatus: string | null;
            monthlyHousingCost: import("@prisma/client-runtime-utils").Decimal | null;
            previousAddress: string | null;
            previousCity: string | null;
            previousState: string | null;
            previousZipCode: string | null;
            previousCountry: string | null;
            yearsAtPreviousAddress: number | null;
            monthsAtPreviousAddress: number | null;
            idTypeId: string | null;
            idNumber: string | null;
            idStateId: string | null;
            idExpirationDate: Date | null;
            idIssueDate: Date | null;
            driversLicenseNumber: string | null;
            driversLicenseState: string | null;
            driversLicenseExpiration: Date | null;
            employmentStatusId: string | null;
            currentEmployer: string | null;
            employerPhone: string | null;
            occupationId: string | null;
            jobTitle: string | null;
            employerAddress: string | null;
            employerCity: string | null;
            employerState: string | null;
            employerZipCode: string | null;
            monthlyIncome: import("@prisma/client-runtime-utils").Decimal | null;
            yearsEmployed: number | null;
            monthsEmployed: number | null;
            additionalIncome: import("@prisma/client-runtime-utils").Decimal | null;
            additionalIncomeSource: string | null;
            previousEmployer: string | null;
            previousEmployerPhone: string | null;
            previousJobTitle: string | null;
            previousEmployerAddress: string | null;
            previousEmployerCity: string | null;
            previousEmployerState: string | null;
            previousEmployerZipCode: string | null;
            previousMonthlyIncome: import("@prisma/client-runtime-utils").Decimal | null;
            previousYearsEmployed: number | null;
            previousMonthsEmployed: number | null;
            bankName: string | null;
            bankAccountType: string | null;
            bankRoutingNumber: string | null;
            bankAccountNumber: string | null;
            yearsWithBank: number | null;
            monthsWithBank: number | null;
            creditScore: number | null;
            bankruptcyHistory: boolean;
            bankruptcyDate: Date | null;
            bankruptcyType: string | null;
            bankruptcyDischargeDate: Date | null;
            repoHistory: boolean;
            repoDate: Date | null;
            foreclosureHistory: boolean;
            foreclosureDate: Date | null;
            currentMonthlyDebts: import("@prisma/client-runtime-utils").Decimal | null;
            alimonyChildSupport: import("@prisma/client-runtime-utils").Decimal | null;
            reference1Name: string | null;
            reference1Phone: string | null;
            reference1Relation: string | null;
            reference1Address: string | null;
            reference1YearsKnown: number | null;
            reference2Name: string | null;
            reference2Phone: string | null;
            reference2Relation: string | null;
            reference2Address: string | null;
            reference2YearsKnown: number | null;
            reference3Name: string | null;
            reference3Phone: string | null;
            reference3Relation: string | null;
            reference3Address: string | null;
            reference3YearsKnown: number | null;
            reference4Name: string | null;
            reference4Phone: string | null;
            reference4Relation: string | null;
            reference4Address: string | null;
            reference4YearsKnown: number | null;
            reference5Name: string | null;
            reference5Phone: string | null;
            reference5Relation: string | null;
            reference5Address: string | null;
            reference5YearsKnown: number | null;
            isBusinessBuyer: boolean;
            businessType: string | null;
            businessEIN: string | null;
            businessYearsInBusiness: number | null;
            businessAnnualRevenue: import("@prisma/client-runtime-utils").Decimal | null;
            ofacCheckCompleted: boolean;
            ofacCheckDate: Date | null;
            ofacCheckResult: string | null;
            ofacNotes: string | null;
            identityVerified: boolean;
            identityVerifiedDate: Date | null;
            identityVerifiedBy: string | null;
            source: string | null;
            leadType: string | null;
            salesPersonId: string | null;
            bdcAgentId: string | null;
            stripeCustomerId: string | null;
            clerkUserId: string | null;
        };
        items: ({
            part: {
                length: import("@prisma/client-runtime-utils").Decimal | null;
                name: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                tenantId: string;
                description: string | null;
                notes: string | null;
                mainImageId: string | null;
                makeId: string | null;
                modelId: string | null;
                trimId: string | null;
                yearId: string | null;
                metaValue: import("@prisma/client/runtime/client").JsonValue | null;
                purchaseDate: Date | null;
                price: import("@prisma/client-runtime-utils").Decimal;
                width: import("@prisma/client-runtime-utils").Decimal | null;
                height: import("@prisma/client-runtime-utils").Decimal | null;
                partNumber: string | null;
                sku: string | null;
                categoryId: string | null;
                conditionId: string;
                statusId: string;
                cost: import("@prisma/client-runtime-utils").Decimal | null;
                quantity: number;
                minQuantity: number;
                location: string | null;
                warehouseSection: string | null;
                sourceVin: string | null;
                sourceMiles: number | null;
                sourceVehicleId: string | null;
                weight: import("@prisma/client-runtime-utils").Decimal | null;
                warrantyDays: number | null;
                warrantyNotes: string | null;
                supplier: string | null;
                supplierPartNumber: string | null;
                purchaseOrderNumber: string | null;
                brand: string | null;
                manufacturer: string | null;
                countryOfOrigin: string | null;
                isOem: boolean;
                isAftermarket: boolean;
                soldAt: Date | null;
                soldToId: string | null;
                soldPrice: import("@prisma/client-runtime-utils").Decimal | null;
                soldDealId: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            partId: string;
            quantity: number;
            orderId: string;
            unitPrice: import("@prisma/client-runtime-utils").Decimal;
            totalPrice: import("@prisma/client-runtime-utils").Decimal;
            nameSnapshot: string;
            skuSnapshot: string | null;
        })[];
        shipments: {
            length: import("@prisma/client-runtime-utils").Decimal | null;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: string;
            width: import("@prisma/client-runtime-utils").Decimal | null;
            height: import("@prisma/client-runtime-utils").Decimal | null;
            cost: import("@prisma/client-runtime-utils").Decimal | null;
            weight: import("@prisma/client-runtime-utils").Decimal | null;
            cancelledAt: Date | null;
            deliveredAt: Date | null;
            carrier: string;
            distanceUnit: string | null;
            massUnit: string | null;
            orderId: string;
            parcelTemplateId: string | null;
            serviceLevel: string | null;
            serviceLevelName: string | null;
            shippoShipmentId: string | null;
            shippoTransactionId: string | null;
            shippoRateId: string | null;
            labelUrl: string | null;
            trackingNumber: string | null;
            trackingUrl: string | null;
            trackingStatus: string | null;
            purchasedAt: Date | null;
            shippedAt: Date | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        createdById: string | null;
        buyerId: string;
        status: string;
        discount: import("@prisma/client-runtime-utils").Decimal;
        customerNotes: string | null;
        shippingCost: import("@prisma/client-runtime-utils").Decimal;
        tax: import("@prisma/client-runtime-utils").Decimal;
        cancelledAt: Date | null;
        paidAt: Date | null;
        orderNumber: string;
        subtotal: import("@prisma/client-runtime-utils").Decimal;
        taxRate: import("@prisma/client-runtime-utils").Decimal;
        total: import("@prisma/client-runtime-utils").Decimal;
        paymentMethod: string | null;
        paymentStatus: string;
        stripePaymentIntentId: string | null;
        stripeChargeId: string | null;
        shippingMethod: string | null;
        shipToName: string | null;
        shipToStreet1: string | null;
        shipToStreet2: string | null;
        shipToCity: string | null;
        shipToState: string | null;
        shipToZip: string | null;
        shipToCountry: string | null;
        shipToPhone: string | null;
        shipToEmail: string | null;
    }>;
    cancel(tenantId: string, id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        createdById: string | null;
        buyerId: string;
        status: string;
        discount: import("@prisma/client-runtime-utils").Decimal;
        customerNotes: string | null;
        shippingCost: import("@prisma/client-runtime-utils").Decimal;
        tax: import("@prisma/client-runtime-utils").Decimal;
        cancelledAt: Date | null;
        paidAt: Date | null;
        orderNumber: string;
        subtotal: import("@prisma/client-runtime-utils").Decimal;
        taxRate: import("@prisma/client-runtime-utils").Decimal;
        total: import("@prisma/client-runtime-utils").Decimal;
        paymentMethod: string | null;
        paymentStatus: string;
        stripePaymentIntentId: string | null;
        stripeChargeId: string | null;
        shippingMethod: string | null;
        shipToName: string | null;
        shipToStreet1: string | null;
        shipToStreet2: string | null;
        shipToCity: string | null;
        shipToState: string | null;
        shipToZip: string | null;
        shipToCountry: string | null;
        shipToPhone: string | null;
        shipToEmail: string | null;
    }>;
    removeBulk(tenantId: string, body: {
        ids: string[];
    }): Promise<{
        message: string;
        count: number;
    }>;
    remove(tenantId: string, id: string): Promise<{
        message: string;
    }>;
    charge(tenantId: string, user: any, id: string, dto: ChargeOrderDto): Promise<{
        id: string;
        status: import("stripe").Stripe.PaymentIntent.Status;
        amount: number;
        clientSecret: string | null;
    } | {
        sent: boolean;
        url: string;
    }>;
    markPaid(tenantId: string, id: string, body: {
        method?: string;
    }): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        notes: string | null;
        createdById: string | null;
        buyerId: string;
        status: string;
        discount: import("@prisma/client-runtime-utils").Decimal;
        customerNotes: string | null;
        shippingCost: import("@prisma/client-runtime-utils").Decimal;
        tax: import("@prisma/client-runtime-utils").Decimal;
        cancelledAt: Date | null;
        paidAt: Date | null;
        orderNumber: string;
        subtotal: import("@prisma/client-runtime-utils").Decimal;
        taxRate: import("@prisma/client-runtime-utils").Decimal;
        total: import("@prisma/client-runtime-utils").Decimal;
        paymentMethod: string | null;
        paymentStatus: string;
        stripePaymentIntentId: string | null;
        stripeChargeId: string | null;
        shippingMethod: string | null;
        shipToName: string | null;
        shipToStreet1: string | null;
        shipToStreet2: string | null;
        shipToCity: string | null;
        shipToState: string | null;
        shipToZip: string | null;
        shipToCountry: string | null;
        shipToPhone: string | null;
        shipToEmail: string | null;
    }>;
    estimateShipping(tenantId: string, dto: EstimateShippingDto): Promise<{
        amount: number;
        currency: any;
        provider: any;
        serviceLevel: any;
        serviceLevelName: any;
    }>;
    getRates(tenantId: string, id: string, dto: CreateShipmentDto): Promise<{
        shipmentId: string;
        rates: {
            id: any;
            provider: any;
            serviceLevel: any;
            serviceLevelName: any;
            amount: any;
            currency: any;
            estimatedDays: any;
            durationTerms: any;
        }[];
    }>;
    buyLabel(tenantId: string, id: string, dto: BuyLabelDto & CreateShipmentDto & {
        parcelTemplateId?: string;
    }): Promise<{
        length: import("@prisma/client-runtime-utils").Decimal | null;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        width: import("@prisma/client-runtime-utils").Decimal | null;
        height: import("@prisma/client-runtime-utils").Decimal | null;
        cost: import("@prisma/client-runtime-utils").Decimal | null;
        weight: import("@prisma/client-runtime-utils").Decimal | null;
        cancelledAt: Date | null;
        deliveredAt: Date | null;
        carrier: string;
        distanceUnit: string | null;
        massUnit: string | null;
        orderId: string;
        parcelTemplateId: string | null;
        serviceLevel: string | null;
        serviceLevelName: string | null;
        shippoShipmentId: string | null;
        shippoTransactionId: string | null;
        shippoRateId: string | null;
        labelUrl: string | null;
        trackingNumber: string | null;
        trackingUrl: string | null;
        trackingStatus: string | null;
        purchasedAt: Date | null;
        shippedAt: Date | null;
    }>;
    refreshTracking(tenantId: string, id: string, shipmentId: string): Promise<{
        length: import("@prisma/client-runtime-utils").Decimal | null;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        width: import("@prisma/client-runtime-utils").Decimal | null;
        height: import("@prisma/client-runtime-utils").Decimal | null;
        cost: import("@prisma/client-runtime-utils").Decimal | null;
        weight: import("@prisma/client-runtime-utils").Decimal | null;
        cancelledAt: Date | null;
        deliveredAt: Date | null;
        carrier: string;
        distanceUnit: string | null;
        massUnit: string | null;
        orderId: string;
        parcelTemplateId: string | null;
        serviceLevel: string | null;
        serviceLevelName: string | null;
        shippoShipmentId: string | null;
        shippoTransactionId: string | null;
        shippoRateId: string | null;
        labelUrl: string | null;
        trackingNumber: string | null;
        trackingUrl: string | null;
        trackingStatus: string | null;
        purchasedAt: Date | null;
        shippedAt: Date | null;
    }>;
}
