import { PrismaService } from '@htownautos/prisma';
import { CreateDealDto } from './dto/create-deal.dto';
import { QueryDealDto } from './dto/query-deal.dto';
import { Prisma } from '@prisma/client';
export declare class DealService {
    private prisma;
    private readonly logger;
    constructor(prisma: PrismaService);
    private generateDealNumber;
    create(createDealDto: CreateDealDto, tenantId: string): Promise<{
        dealStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        };
        financeType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        buyer: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
        };
        vehicle: {
            model: {
                name: string;
                id: string;
                slug: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                makeId: string;
                metaValue: Prisma.JsonValue | null;
            };
            id: string;
            stockNumber: string | null;
            make: {
                name: string;
                id: string;
                slug: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                yearId: string;
                metaValue: Prisma.JsonValue | null;
            };
            year: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                metaValue: Prisma.JsonValue | null;
                year: number;
            };
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        notes: string | null;
        metaValue: Prisma.JsonValue | null;
        buyerId: string;
        vehicleId: string;
        ipAddress: string | null;
        userAgent: string | null;
        creditScore: number | null;
        source: string | null;
        salesPersonId: string | null;
        coBuyerId: string | null;
        dealNumber: string;
        dealStatusId: string;
        financeTypeId: string | null;
        dealDate: Date;
        deliveryDate: Date | null;
        fundedDate: Date | null;
        vehiclePrice: Prisma.Decimal;
        sellingPrice: Prisma.Decimal;
        discount: Prisma.Decimal | null;
        rebate: Prisma.Decimal | null;
        hasTradeIn: boolean;
        tradeInYear: number | null;
        tradeInMake: string | null;
        tradeInModel: string | null;
        tradeInVin: string | null;
        tradeInMileage: number | null;
        tradeInActualValue: Prisma.Decimal | null;
        tradeInAllowance: Prisma.Decimal | null;
        tradeInPayoff: Prisma.Decimal | null;
        tradeInLienHolder: string | null;
        tradeInEquity: Prisma.Decimal | null;
        salesTax: Prisma.Decimal | null;
        docFee: Prisma.Decimal | null;
        titleFee: Prisma.Decimal | null;
        registrationFee: Prisma.Decimal | null;
        otherFees: Prisma.Decimal | null;
        totalFees: Prisma.Decimal | null;
        totalCashPrice: Prisma.Decimal | null;
        downPayment: Prisma.Decimal | null;
        amountFinanced: Prisma.Decimal | null;
        apr: Prisma.Decimal | null;
        term: number | null;
        monthlyPayment: Prisma.Decimal | null;
        totalOfPayments: Prisma.Decimal | null;
        financeCharge: Prisma.Decimal | null;
        lenderName: string | null;
        lenderId: string | null;
        lenderRate: Prisma.Decimal | null;
        dealerReserve: Prisma.Decimal | null;
        buyRate: Prisma.Decimal | null;
        sellRate: Prisma.Decimal | null;
        hasWarranty: boolean;
        warrantyProvider: string | null;
        warrantyCost: Prisma.Decimal | null;
        warrantyTerm: number | null;
        warrantyDeductible: Prisma.Decimal | null;
        hasGap: boolean;
        gapProvider: string | null;
        gapCost: Prisma.Decimal | null;
        hasMaintenancePlan: boolean;
        maintenanceProvider: string | null;
        maintenanceCost: Prisma.Decimal | null;
        hasTheftProtection: boolean;
        theftProtectionCost: Prisma.Decimal | null;
        hasPaintProtection: boolean;
        paintProtectionCost: Prisma.Decimal | null;
        totalAftermarketProducts: Prisma.Decimal | null;
        loanToValue: Prisma.Decimal | null;
        paymentToIncome: Prisma.Decimal | null;
        debtToIncome: Prisma.Decimal | null;
        creditCheckConsent: boolean;
        creditCheckDate: Date | null;
        termsAccepted: boolean;
        termsAcceptedDate: Date | null;
        privacyPolicyAccepted: boolean;
        electronicDisclosureConsent: boolean;
        creditReportPulled: boolean;
        creditReportDate: Date | null;
        creditReportProvider: string | null;
        applicationStatus: string | null;
        applicationDate: Date | null;
        approvalDate: Date | null;
        denialDate: Date | null;
        denialReason: string | null;
        stipulations: string | null;
        dealertrackAppId: string | null;
        dealertrackStatus: string | null;
        dealertrackSubmittedDate: Date | null;
        routeoneAppId: string | null;
        routeoneStatus: string | null;
        routeoneSubmittedDate: Date | null;
        cudlAppId: string | null;
        cudlStatus: string | null;
        cudlSubmittedDate: Date | null;
        cashTransactionOver10k: boolean;
        form8300Filed: boolean;
        form8300FiledDate: Date | null;
        redFlagsChecked: boolean;
        redFlagsNotes: string | null;
        activeLoan1Type: string | null;
        activeLoan1Creditor: string | null;
        activeLoan1Balance: Prisma.Decimal | null;
        activeLoan1Payment: Prisma.Decimal | null;
        activeLoan2Type: string | null;
        activeLoan2Creditor: string | null;
        activeLoan2Balance: Prisma.Decimal | null;
        activeLoan2Payment: Prisma.Decimal | null;
        activeLoan3Type: string | null;
        activeLoan3Creditor: string | null;
        activeLoan3Balance: Prisma.Decimal | null;
        activeLoan3Payment: Prisma.Decimal | null;
        salesManagerId: string | null;
        financeManagerId: string | null;
        internalNotes: string | null;
        customerNotes: string | null;
        applicationLanguage: string | null;
    }>;
    findAll(query: QueryDealDto, tenantId: string): Promise<{
        data: any;
        meta: {
            total: any;
            page: number;
            limit: number;
            totalPages: number;
            hasNextPage: boolean;
            hasPreviousPage: boolean;
        };
    }>;
    findOne(id: string, tenantId: string): Promise<{
        dealStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        };
        financeType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        buyer: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            leadSource: string | null;
            inquiryType: string | null;
            contactMethod: string | null;
            contactTime: string | null;
            tenantId: string | null;
            notes: string | null;
            metaValue: Prisma.JsonValue | null;
            businessName: string | null;
            email: string;
            firstName: string;
            middleName: string | null;
            lastName: string;
            suffix: string | null;
            dateOfBirth: Date;
            genderId: string | null;
            ssn: string | null;
            itin: string | null;
            citizenship: string | null;
            phoneMain: string;
            phoneSecondary: string | null;
            phoneMobile: string | null;
            preferredLanguageId: string | null;
            currentAddress: string;
            currentCity: string;
            currentState: string;
            currentZipCode: string;
            currentCountry: string;
            yearsAtAddress: number | null;
            monthsAtAddress: number | null;
            housingStatus: string | null;
            monthlyHousingCost: Prisma.Decimal | null;
            previousAddress: string | null;
            previousCity: string | null;
            previousState: string | null;
            previousZipCode: string | null;
            previousCountry: string | null;
            yearsAtPreviousAddress: number | null;
            monthsAtPreviousAddress: number | null;
            idTypeId: string | null;
            idNumber: string | null;
            idStateId: string | null;
            idExpirationDate: Date | null;
            idIssueDate: Date | null;
            driversLicenseNumber: string | null;
            driversLicenseState: string | null;
            driversLicenseExpiration: Date | null;
            employmentStatusId: string | null;
            currentEmployer: string | null;
            employerPhone: string | null;
            occupationId: string | null;
            jobTitle: string | null;
            employerAddress: string | null;
            employerCity: string | null;
            employerState: string | null;
            employerZipCode: string | null;
            monthlyIncome: Prisma.Decimal | null;
            yearsEmployed: number | null;
            monthsEmployed: number | null;
            additionalIncome: Prisma.Decimal | null;
            additionalIncomeSource: string | null;
            previousEmployer: string | null;
            previousEmployerPhone: string | null;
            previousJobTitle: string | null;
            previousEmployerAddress: string | null;
            previousEmployerCity: string | null;
            previousEmployerState: string | null;
            previousEmployerZipCode: string | null;
            previousMonthlyIncome: Prisma.Decimal | null;
            previousYearsEmployed: number | null;
            previousMonthsEmployed: number | null;
            bankName: string | null;
            bankAccountType: string | null;
            bankRoutingNumber: string | null;
            bankAccountNumber: string | null;
            yearsWithBank: number | null;
            monthsWithBank: number | null;
            creditScore: number | null;
            bankruptcyHistory: boolean;
            bankruptcyDate: Date | null;
            bankruptcyType: string | null;
            bankruptcyDischargeDate: Date | null;
            repoHistory: boolean;
            repoDate: Date | null;
            foreclosureHistory: boolean;
            foreclosureDate: Date | null;
            currentMonthlyDebts: Prisma.Decimal | null;
            alimonyChildSupport: Prisma.Decimal | null;
            reference1Name: string | null;
            reference1Phone: string | null;
            reference1Relation: string | null;
            reference1Address: string | null;
            reference1YearsKnown: number | null;
            reference2Name: string | null;
            reference2Phone: string | null;
            reference2Relation: string | null;
            reference2Address: string | null;
            reference2YearsKnown: number | null;
            reference3Name: string | null;
            reference3Phone: string | null;
            reference3Relation: string | null;
            reference3Address: string | null;
            reference3YearsKnown: number | null;
            reference4Name: string | null;
            reference4Phone: string | null;
            reference4Relation: string | null;
            reference4Address: string | null;
            reference4YearsKnown: number | null;
            reference5Name: string | null;
            reference5Phone: string | null;
            reference5Relation: string | null;
            reference5Address: string | null;
            reference5YearsKnown: number | null;
            isBusinessBuyer: boolean;
            businessType: string | null;
            businessEIN: string | null;
            businessYearsInBusiness: number | null;
            businessAnnualRevenue: Prisma.Decimal | null;
            ofacCheckCompleted: boolean;
            ofacCheckDate: Date | null;
            ofacCheckResult: string | null;
            ofacNotes: string | null;
            identityVerified: boolean;
            identityVerifiedDate: Date | null;
            identityVerifiedBy: string | null;
            source: string | null;
            leadType: string | null;
            salesPersonId: string | null;
            bdcAgentId: string | null;
            stripeCustomerId: string | null;
            clerkUserId: string | null;
        };
        vehicle: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
            vin: string;
            stockNumber: string | null;
            mileage: number | null;
            exteriorColor: string | null;
            interiorColor: string | null;
            vehicleTypeId: string | null;
            bodyTypeId: string | null;
            fuelTypeId: string | null;
            driveTypeId: string | null;
            transmissionTypeId: string | null;
            vehicleConditionId: string | null;
            vehicleStatusId: string | null;
            sourceId: string | null;
            costPrice: Prisma.Decimal | null;
            listPrice: Prisma.Decimal | null;
            salePrice: Prisma.Decimal | null;
            engine: string | null;
            cylinders: number | null;
            doors: number | null;
            passengers: number | null;
            description: string | null;
            features: string | null;
            notes: string | null;
            mainImageId: string | null;
            makeId: string;
            modelId: string;
            trimId: string | null;
            yearId: string;
            metaValue: Prisma.JsonValue | null;
            createdById: string | null;
            titleBrandId: string | null;
            advertisingPrice: Prisma.Decimal | null;
            askingPrice: Prisma.Decimal | null;
            bidIncrement: Prisma.Decimal | null;
            buyNowPrice: Prisma.Decimal | null;
            floorPrice: Prisma.Decimal | null;
            minDepositAmount: Prisma.Decimal | null;
            minDepositPercent: Prisma.Decimal | null;
            minDepositType: string | null;
            minDownAmount: Prisma.Decimal | null;
            minDownPercent: Prisma.Decimal | null;
            minDownType: string | null;
            msrp: Prisma.Decimal | null;
            purchaseDate: Date | null;
            specialPrice: Prisma.Decimal | null;
            specialPriceEndDate: Date | null;
            specialPriceStartDate: Date | null;
            startBid: Prisma.Decimal | null;
            startBidEqualsFloor: boolean;
            vehicleCost: Prisma.Decimal;
            wholesalePrice: Prisma.Decimal | null;
            mileageUnitId: string | null;
            bodySubtypeId: string | null;
            engineId: string | null;
        };
        coBuyer: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            leadSource: string | null;
            inquiryType: string | null;
            contactMethod: string | null;
            contactTime: string | null;
            tenantId: string | null;
            notes: string | null;
            metaValue: Prisma.JsonValue | null;
            businessName: string | null;
            email: string;
            firstName: string;
            middleName: string | null;
            lastName: string;
            suffix: string | null;
            dateOfBirth: Date;
            genderId: string | null;
            ssn: string | null;
            itin: string | null;
            citizenship: string | null;
            phoneMain: string;
            phoneSecondary: string | null;
            phoneMobile: string | null;
            preferredLanguageId: string | null;
            currentAddress: string;
            currentCity: string;
            currentState: string;
            currentZipCode: string;
            currentCountry: string;
            yearsAtAddress: number | null;
            monthsAtAddress: number | null;
            housingStatus: string | null;
            monthlyHousingCost: Prisma.Decimal | null;
            previousAddress: string | null;
            previousCity: string | null;
            previousState: string | null;
            previousZipCode: string | null;
            previousCountry: string | null;
            yearsAtPreviousAddress: number | null;
            monthsAtPreviousAddress: number | null;
            idTypeId: string | null;
            idNumber: string | null;
            idStateId: string | null;
            idExpirationDate: Date | null;
            idIssueDate: Date | null;
            driversLicenseNumber: string | null;
            driversLicenseState: string | null;
            driversLicenseExpiration: Date | null;
            employmentStatusId: string | null;
            currentEmployer: string | null;
            employerPhone: string | null;
            occupationId: string | null;
            jobTitle: string | null;
            employerAddress: string | null;
            employerCity: string | null;
            employerState: string | null;
            employerZipCode: string | null;
            monthlyIncome: Prisma.Decimal | null;
            yearsEmployed: number | null;
            monthsEmployed: number | null;
            additionalIncome: Prisma.Decimal | null;
            additionalIncomeSource: string | null;
            previousEmployer: string | null;
            previousEmployerPhone: string | null;
            previousJobTitle: string | null;
            previousEmployerAddress: string | null;
            previousEmployerCity: string | null;
            previousEmployerState: string | null;
            previousEmployerZipCode: string | null;
            previousMonthlyIncome: Prisma.Decimal | null;
            previousYearsEmployed: number | null;
            previousMonthsEmployed: number | null;
            bankName: string | null;
            bankAccountType: string | null;
            bankRoutingNumber: string | null;
            bankAccountNumber: string | null;
            yearsWithBank: number | null;
            monthsWithBank: number | null;
            creditScore: number | null;
            bankruptcyHistory: boolean;
            bankruptcyDate: Date | null;
            bankruptcyType: string | null;
            bankruptcyDischargeDate: Date | null;
            repoHistory: boolean;
            repoDate: Date | null;
            foreclosureHistory: boolean;
            foreclosureDate: Date | null;
            currentMonthlyDebts: Prisma.Decimal | null;
            alimonyChildSupport: Prisma.Decimal | null;
            reference1Name: string | null;
            reference1Phone: string | null;
            reference1Relation: string | null;
            reference1Address: string | null;
            reference1YearsKnown: number | null;
            reference2Name: string | null;
            reference2Phone: string | null;
            reference2Relation: string | null;
            reference2Address: string | null;
            reference2YearsKnown: number | null;
            reference3Name: string | null;
            reference3Phone: string | null;
            reference3Relation: string | null;
            reference3Address: string | null;
            reference3YearsKnown: number | null;
            reference4Name: string | null;
            reference4Phone: string | null;
            reference4Relation: string | null;
            reference4Address: string | null;
            reference4YearsKnown: number | null;
            reference5Name: string | null;
            reference5Phone: string | null;
            reference5Relation: string | null;
            reference5Address: string | null;
            reference5YearsKnown: number | null;
            isBusinessBuyer: boolean;
            businessType: string | null;
            businessEIN: string | null;
            businessYearsInBusiness: number | null;
            businessAnnualRevenue: Prisma.Decimal | null;
            ofacCheckCompleted: boolean;
            ofacCheckDate: Date | null;
            ofacCheckResult: string | null;
            ofacNotes: string | null;
            identityVerified: boolean;
            identityVerifiedDate: Date | null;
            identityVerifiedBy: string | null;
            source: string | null;
            leadType: string | null;
            salesPersonId: string | null;
            bdcAgentId: string | null;
            stripeCustomerId: string | null;
            clerkUserId: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        notes: string | null;
        metaValue: Prisma.JsonValue | null;
        buyerId: string;
        vehicleId: string;
        ipAddress: string | null;
        userAgent: string | null;
        creditScore: number | null;
        source: string | null;
        salesPersonId: string | null;
        coBuyerId: string | null;
        dealNumber: string;
        dealStatusId: string;
        financeTypeId: string | null;
        dealDate: Date;
        deliveryDate: Date | null;
        fundedDate: Date | null;
        vehiclePrice: Prisma.Decimal;
        sellingPrice: Prisma.Decimal;
        discount: Prisma.Decimal | null;
        rebate: Prisma.Decimal | null;
        hasTradeIn: boolean;
        tradeInYear: number | null;
        tradeInMake: string | null;
        tradeInModel: string | null;
        tradeInVin: string | null;
        tradeInMileage: number | null;
        tradeInActualValue: Prisma.Decimal | null;
        tradeInAllowance: Prisma.Decimal | null;
        tradeInPayoff: Prisma.Decimal | null;
        tradeInLienHolder: string | null;
        tradeInEquity: Prisma.Decimal | null;
        salesTax: Prisma.Decimal | null;
        docFee: Prisma.Decimal | null;
        titleFee: Prisma.Decimal | null;
        registrationFee: Prisma.Decimal | null;
        otherFees: Prisma.Decimal | null;
        totalFees: Prisma.Decimal | null;
        totalCashPrice: Prisma.Decimal | null;
        downPayment: Prisma.Decimal | null;
        amountFinanced: Prisma.Decimal | null;
        apr: Prisma.Decimal | null;
        term: number | null;
        monthlyPayment: Prisma.Decimal | null;
        totalOfPayments: Prisma.Decimal | null;
        financeCharge: Prisma.Decimal | null;
        lenderName: string | null;
        lenderId: string | null;
        lenderRate: Prisma.Decimal | null;
        dealerReserve: Prisma.Decimal | null;
        buyRate: Prisma.Decimal | null;
        sellRate: Prisma.Decimal | null;
        hasWarranty: boolean;
        warrantyProvider: string | null;
        warrantyCost: Prisma.Decimal | null;
        warrantyTerm: number | null;
        warrantyDeductible: Prisma.Decimal | null;
        hasGap: boolean;
        gapProvider: string | null;
        gapCost: Prisma.Decimal | null;
        hasMaintenancePlan: boolean;
        maintenanceProvider: string | null;
        maintenanceCost: Prisma.Decimal | null;
        hasTheftProtection: boolean;
        theftProtectionCost: Prisma.Decimal | null;
        hasPaintProtection: boolean;
        paintProtectionCost: Prisma.Decimal | null;
        totalAftermarketProducts: Prisma.Decimal | null;
        loanToValue: Prisma.Decimal | null;
        paymentToIncome: Prisma.Decimal | null;
        debtToIncome: Prisma.Decimal | null;
        creditCheckConsent: boolean;
        creditCheckDate: Date | null;
        termsAccepted: boolean;
        termsAcceptedDate: Date | null;
        privacyPolicyAccepted: boolean;
        electronicDisclosureConsent: boolean;
        creditReportPulled: boolean;
        creditReportDate: Date | null;
        creditReportProvider: string | null;
        applicationStatus: string | null;
        applicationDate: Date | null;
        approvalDate: Date | null;
        denialDate: Date | null;
        denialReason: string | null;
        stipulations: string | null;
        dealertrackAppId: string | null;
        dealertrackStatus: string | null;
        dealertrackSubmittedDate: Date | null;
        routeoneAppId: string | null;
        routeoneStatus: string | null;
        routeoneSubmittedDate: Date | null;
        cudlAppId: string | null;
        cudlStatus: string | null;
        cudlSubmittedDate: Date | null;
        cashTransactionOver10k: boolean;
        form8300Filed: boolean;
        form8300FiledDate: Date | null;
        redFlagsChecked: boolean;
        redFlagsNotes: string | null;
        activeLoan1Type: string | null;
        activeLoan1Creditor: string | null;
        activeLoan1Balance: Prisma.Decimal | null;
        activeLoan1Payment: Prisma.Decimal | null;
        activeLoan2Type: string | null;
        activeLoan2Creditor: string | null;
        activeLoan2Balance: Prisma.Decimal | null;
        activeLoan2Payment: Prisma.Decimal | null;
        activeLoan3Type: string | null;
        activeLoan3Creditor: string | null;
        activeLoan3Balance: Prisma.Decimal | null;
        activeLoan3Payment: Prisma.Decimal | null;
        salesManagerId: string | null;
        financeManagerId: string | null;
        internalNotes: string | null;
        customerNotes: string | null;
        applicationLanguage: string | null;
    }>;
    update(id: string, data: Partial<CreateDealDto>, tenantId: string): Promise<{
        dealStatus: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string | null;
        };
        financeType: {
            id: string;
            slug: string;
            title: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        buyer: {
            id: string;
            firstName: string;
            lastName: string;
        };
        vehicle: {
            model: {
                name: string;
                id: string;
                slug: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                makeId: string;
                metaValue: Prisma.JsonValue | null;
            };
            id: string;
            stockNumber: string | null;
            make: {
                name: string;
                id: string;
                slug: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                yearId: string;
                metaValue: Prisma.JsonValue | null;
            };
            year: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                metaValue: Prisma.JsonValue | null;
                year: number;
            };
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        notes: string | null;
        metaValue: Prisma.JsonValue | null;
        buyerId: string;
        vehicleId: string;
        ipAddress: string | null;
        userAgent: string | null;
        creditScore: number | null;
        source: string | null;
        salesPersonId: string | null;
        coBuyerId: string | null;
        dealNumber: string;
        dealStatusId: string;
        financeTypeId: string | null;
        dealDate: Date;
        deliveryDate: Date | null;
        fundedDate: Date | null;
        vehiclePrice: Prisma.Decimal;
        sellingPrice: Prisma.Decimal;
        discount: Prisma.Decimal | null;
        rebate: Prisma.Decimal | null;
        hasTradeIn: boolean;
        tradeInYear: number | null;
        tradeInMake: string | null;
        tradeInModel: string | null;
        tradeInVin: string | null;
        tradeInMileage: number | null;
        tradeInActualValue: Prisma.Decimal | null;
        tradeInAllowance: Prisma.Decimal | null;
        tradeInPayoff: Prisma.Decimal | null;
        tradeInLienHolder: string | null;
        tradeInEquity: Prisma.Decimal | null;
        salesTax: Prisma.Decimal | null;
        docFee: Prisma.Decimal | null;
        titleFee: Prisma.Decimal | null;
        registrationFee: Prisma.Decimal | null;
        otherFees: Prisma.Decimal | null;
        totalFees: Prisma.Decimal | null;
        totalCashPrice: Prisma.Decimal | null;
        downPayment: Prisma.Decimal | null;
        amountFinanced: Prisma.Decimal | null;
        apr: Prisma.Decimal | null;
        term: number | null;
        monthlyPayment: Prisma.Decimal | null;
        totalOfPayments: Prisma.Decimal | null;
        financeCharge: Prisma.Decimal | null;
        lenderName: string | null;
        lenderId: string | null;
        lenderRate: Prisma.Decimal | null;
        dealerReserve: Prisma.Decimal | null;
        buyRate: Prisma.Decimal | null;
        sellRate: Prisma.Decimal | null;
        hasWarranty: boolean;
        warrantyProvider: string | null;
        warrantyCost: Prisma.Decimal | null;
        warrantyTerm: number | null;
        warrantyDeductible: Prisma.Decimal | null;
        hasGap: boolean;
        gapProvider: string | null;
        gapCost: Prisma.Decimal | null;
        hasMaintenancePlan: boolean;
        maintenanceProvider: string | null;
        maintenanceCost: Prisma.Decimal | null;
        hasTheftProtection: boolean;
        theftProtectionCost: Prisma.Decimal | null;
        hasPaintProtection: boolean;
        paintProtectionCost: Prisma.Decimal | null;
        totalAftermarketProducts: Prisma.Decimal | null;
        loanToValue: Prisma.Decimal | null;
        paymentToIncome: Prisma.Decimal | null;
        debtToIncome: Prisma.Decimal | null;
        creditCheckConsent: boolean;
        creditCheckDate: Date | null;
        termsAccepted: boolean;
        termsAcceptedDate: Date | null;
        privacyPolicyAccepted: boolean;
        electronicDisclosureConsent: boolean;
        creditReportPulled: boolean;
        creditReportDate: Date | null;
        creditReportProvider: string | null;
        applicationStatus: string | null;
        applicationDate: Date | null;
        approvalDate: Date | null;
        denialDate: Date | null;
        denialReason: string | null;
        stipulations: string | null;
        dealertrackAppId: string | null;
        dealertrackStatus: string | null;
        dealertrackSubmittedDate: Date | null;
        routeoneAppId: string | null;
        routeoneStatus: string | null;
        routeoneSubmittedDate: Date | null;
        cudlAppId: string | null;
        cudlStatus: string | null;
        cudlSubmittedDate: Date | null;
        cashTransactionOver10k: boolean;
        form8300Filed: boolean;
        form8300FiledDate: Date | null;
        redFlagsChecked: boolean;
        redFlagsNotes: string | null;
        activeLoan1Type: string | null;
        activeLoan1Creditor: string | null;
        activeLoan1Balance: Prisma.Decimal | null;
        activeLoan1Payment: Prisma.Decimal | null;
        activeLoan2Type: string | null;
        activeLoan2Creditor: string | null;
        activeLoan2Balance: Prisma.Decimal | null;
        activeLoan2Payment: Prisma.Decimal | null;
        activeLoan3Type: string | null;
        activeLoan3Creditor: string | null;
        activeLoan3Balance: Prisma.Decimal | null;
        activeLoan3Payment: Prisma.Decimal | null;
        salesManagerId: string | null;
        financeManagerId: string | null;
        internalNotes: string | null;
        customerNotes: string | null;
        applicationLanguage: string | null;
    }>;
    remove(id: string, tenantId: string): Promise<{
        message: string;
    }>;
}
